### ISSUE TITLE
Thai lunar date functions may need refactoring - currently too complex

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#1017]
### Description

Ruff warns that two of the functions for Thai lunar date are too complex.

It may possible to convert the long if/else to some values in arrays and compute according to values in the arrays.

### Expected results

Simpler/shorter functions

### Current results

> pythainlp/util/thai_lunar_date.py:251:5: C901 `calculate_f_year_f_dev` is too complex (113 > 40)

> pythainlp/util/thai_lunar_date.py:614:5: C901 `to_lunar_date` is too complex (108 > 40)

### Steps to reproduce

Run ruff against the code 

(currently already inside this workflow: https://github.com/PyThaiNLP/pythainlp/blob/dev/.github/workflows/lint.yml )

### PyThaiNLP version

5.0.4

### Python version

Any

### Operating system and version

Any

**Comment by bkktimber** [comment]
I want to help on this issue.

Just curious, is there any specific reason why we start adjusting the deviation from 1901 BE?

**Comment by bact** [comment]
Thank you!

For the year, I have no idea at all.
@wannaphong do you have any idea?

**Comment by wannaphong** [comment]
> I want to help on this issue.
> 
> Just curious, is there any specific reason why we start adjusting the deviation from 1901 BE?

> เนื่องจาก Excel รองรับข้อมูลวันที่จากปี 1900 เป็นต้นไป และจากการตรวจสอบพบว่า ปี 1902 ของปฏิทินหลวงมีความคลาดเคลื่อนจากการคำนวณ

from https://pantip.com/topic/41786522

**Comment by bkktimber** [comment]
Thanks for the clarification 👍🏼

**Comment by bact** [comment]
PR #1031 addressed complexity in`calculate_f_year_f_dev` and `to_lunar_date`, please help review.
