### ISSUE TITLE
ตัดคำที่มีอักษรซ้ำยาวๆ ด้วย word_tokenize ไม่ได้ครับ

### ISSUE THREAD

**Issue by tamato1** [PyThaiNLP/pythainlp#111]
ใช้ตัว word_tokenize จะใช้เวลานานมากกว่าผลจะออกมาครับ จาก code ข้างล่างผมใช้เวลาไป 5 ชั่วโมง(เฉพาะคำนี้คำเดียว) ก็ยังไม่เสร็จครับ โดยที่ไม่ขึ้น error อะไรเลย
```
from pythainlp.tokenize import word_tokenize 

text = 'ฮือออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ'
print(word_tokenize(text))
```
เมื่อลองวัดเวลาที่ใช้ในการตัดคำด้วย code ข้างล่าง

```
from pythainlp.tokenize import word_tokenize
import time
def speedtest(text):
    start_time = time.time()
    
    print(word_tokenize(text))
    
    print(time.time() - start_time,' sec \n')

text_list = ['ฮือออ', 'ฮืออออออ', 'ฮือออออออออออออออ', 'ฮือออออออออออออออออออออออ', 'ฮือออออออออออออออออออออออออออออออ', 
        'ฮือออออออออออออออออออออออออออออออออออออออ', 'ฮือออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ', 
        'ฮือออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ']

for text in text_list:
    speedtest(text)
```

ได้ผลลัพธ์ดังนี้ครับ
```
['ฮือ', 'ออ']
0.00032782554626464844  sec 

['ฮือ', 'อ', 'ออ', 'ออ']
0.00013303756713867188  sec 

['ฮือ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ']
0.00030422210693359375  sec 

['ฮือ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ']
0.0036551952362060547  sec 

['ฮือ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ']
0.22919106483459473  sec 

['ฮือ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ']
66.015704870224  sec 
```

หลังจากคำที่ 6 เป็นต้นไปใช้เวลานานมากผมเลยกด stop ก่อน  จะเห็นว่าเวลาที่ใช้ของคำสุดท้ายกระโดดไปที่ 66 วินาที/ข้อความ จึงคาดว่าที่ไม่ขึ้น error อะไรเลยคงเพราะยังคงทำงานอยู่แต่ใช้เวลานาน

**Comment by bact** [comment]
ผมเข้าใจว่ากรณีนี้ bfs_paths_graph() ที่จะถูกสร้างขึ้น มันทวีคูณขึ้นไปเยอะมาก (อ จะไปอยู่ตรงไหนของคำก็ได้) 

ผมนึกวิธีแก้แบบ hackๆ ออกอันนึงคือ ใช้ regular expression จับ \w{6,} เจอตัวอักษรไหนซ้ำกันมากกว่า 6 ตัว
(5 ตัวมีกรณีแบบ "เอออออย่างนั้น") ให้ split ตั้งแต่ตัวที่ 6 ออกมาเลย
แล้ว take มันเป็น unknown ไป ส่วนที่เหลือก็ตัดตามปกติ

ตัวอย่างเช่น

"เอออออออออออออออ"
v
ตัดหางแถวของตัวอักษรซ้ำๆ ออกมาก่อน
v
"เอออออ", "ออออออออออ"
v
เอาส่วนแรกเข้า newmm ตัดคำปกติ
v
"เออ", "ออ", "อ", "ออออออออออ"
v
ถ้ามีเศษคำความยาว 1 ตัวอักษร ให้เอาไปรวมกับ unknown ด้านท้าย
"เออ", "ออ", "อออออออออออ"
v
จบ

เท่ากับว่าไม่ต้องเขียน newmm ข้างในใหม่ แต่ทำตัวครอบเอาไว้
เพื่อสกรีนกรณีที่จะทำให้เกิด graph ขนาดใหญ่ออกไปก่อน

**Comment by bact** [comment]
ผมลองทำตามไอเดียที่เสนอนะครับ เป็นแบบ hack มากๆ

```python3

from pythainlp.tokenize import word_tokenize
import re
import time

RE_DUP = re.compile(r"(\D)(\1{4})(\1{1,})")

def ignore_long_dups_tokenize(text):
    tokens = list()
    last_char = 0
    for m in RE_DUP.finditer(text):
        token = ""
        if m.start() > last_char:
            token = token + text[last_char:m.start()]
        token = token + m.group(1) + m.group(2)
        first_part = word_tokenize(token)
        second_part = m.group(3)

        if first_part[-1] == second_part[0]:
            print(first_part[-1], second_part[0])
            second_part = first_part[-1] + second_part
            first_part = first_part[:-1]

        tokens.extend(first_part)
        tokens.append(second_part)
        last_char = m.end()
    
    if last_char == 0: # RE_DUP matches nothing, just use plain word_tokenize()
        return word_tokenize(text)

    if last_char < len(text):
        tokens.append(text[last_char:])

    return tokens


# Test
text_list = [
    'แงฮืออออแงออออ',
    'แงฮืออออออออแงออออออออออออ',
    'แงฮืออออออออออออแงออออออออออออ',
    'แงฮืออออออออออออออออแงออออออออออออ',
    'แงฮืออออออออออออออออออออแงออออออออออออ', 
    'แงฮืออออออออออออออออออออออออแงออออออออออออ',
    'แงฮืออออออออออออออออออออออออออออแงออออออออออออ', 
    'แงฮืออออออออออออออออออออออออออออออออแงออออออออออออ',
]

for text in text_list:
    start_time = time.time()
    print("Original tokenize:", word_tokenize(text))
    print("Original tokenize:", time.time() - start_time, "secs\n")

    start_time = time.time()
    print("Ignore long dups :", ignore_long_dups_tokenize(text))
    print("Ignore long dups :", time.time() - start_time, "secs\n")

```

ผลลัพธ์ครับ

Original tokenize: ['แง', 'ฮือ', 'อ', 'ออ', 'แง', 'ออ', 'ออ']
Original tokenize: 0.0009222030639648438 secs

Ignore long dups : ['แง', 'ฮือ', 'อ', 'ออ', 'แง', 'ออ', 'ออ']
Ignore long dups : 0.0007569789886474609 secs

[...]

Original tokenize: ['แง', 'ฮือ', 'อ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'แง', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ']
Original tokenize: 0.2095508575439453 secs

Ignore long dups : ['แง', 'ฮือ', 'ออ', 'ออ', 'อออออออออออออออออออออออ', 'แง', 'อ', 'ออ', 'ออ', 'อออออออ']
Ignore long dups : 0.00024580955505371094 secs

Original tokenize: ['แง', 'ฮือ', 'อ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'แง', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ', 'ออ']
Original tokenize: 0.46811914443969727 secs

Ignore long dups : ['แง', 'ฮือ', 'ออ', 'ออ', 'อออออออออออออออออออออออออออ', 'แง', 'อ', 'ออ', 'ออ', 'อออออออ']
Ignore long dups : 0.00023126602172851562 secs

คิดว่าที่ดีควรจะไปหาทางแก้ใน newmm onecut ให้จัดการ edge case ลักษณะนี้
แต่อันนี้เป็น hack ไปก่อนครับ เผื่อใครเจอปัญหาก็ใช้ไปก่อนได้ เขียน wrap word_tokenize() ไว้อีกที

**Comment by wannaphongcom** [comment]
ตอนนี้ผมได้แก้ไขเรียบร้อยแล้วครับ
![newmm in PyThaiNLP 1.7](https://i.imgur.com/itLCznV.png)

**Comment by bact** [comment]
โอเค ใช้วิธีตัด อักษรเดี่ยว ออกไปจากพจนานุกรม ทำให้ไม่เกิดกรณีที่ว่า

**Comment by bact** [comment]
เจอเคสนี้ก็ตายเหมือนกันครับ

"อิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิอิ"

**Comment by wannaphongcom** [comment]
@bact แก้ไขตัดคำออกแล้วครับ https://github.com/PyThaiNLP/pythainlp/commit/a234c5799e3afccb96ffffcf57e86b0174462cb2

**Comment by wannaphongcom** [comment]
Close https://github.com/PyThaiNLP/pythainlp/pull/117/
