### ISSUE TITLE
"newmm" engine takes too long to tokenize words.

### ISSUE THREAD

**Issue by pcrete** [PyThaiNLP/pythainlp#121]
# "newmm" engine takes too long to tokenize words
## Compare performance between **old** and **new** maximum matching algorithms
This example shows that **newmm** is about > 1000 times slower.
### Old MM
![image](https://user-images.githubusercontent.com/24978039/46490648-c42cf200-c832-11e8-8585-c119e732bc7e.png)
### New MM
![image](https://user-images.githubusercontent.com/24978039/46490937-8381a880-c833-11e8-81aa-c7446bf5408e.png)

**Comment by bact** [comment]
Same issue as #111.
Fixed with #117 - PyThaiNLP 1.7.
