### ISSUE TITLE
Keyword extraction

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#145]
Add Keyword extraction to PyThaiNLP

**Comment by cstorm125** [comment]
Is this the same as NER?

**Comment by wannaphongcom** [comment]
@cstorm125 No. such as TextRank and more.

**Comment by bact** [comment]
> Is this the same as NER?

Not really. Keywords can be extracted without much knowledge about their meaning or grammatical role. TextRank, for example, relies solely on co-occurance, looking to all the words only at their surface level.

**Comment by heytitle** [comment]
btw, what does `todo: ` in the title mean? can we remove it as use the corresponding label instead?

**Comment by heytitle** [comment]
imho, one way to do key word extraction might be based on problems.

In particular, given a sentence, one might want to extract keywords based on its sentiment ( generally speaking classification prediction). In this case, the algorithm will pick a number of words that are highly relevant to the sentiment prediction the most.

For example, we build a generic sentiment classifier (possibly neural network models) and apply an interpretation method to the model. We will get interpretations as shown below (red indicates high relevance):
<img width="856" alt="image" src="https://user-images.githubusercontent.com/1214890/66685795-c31c7500-ec7d-11e9-8c9c-b5f850bb565a.png">
Then, we select the keywords from its relevance values.

More details about the method can be found at : https://github.com/albermax/innvestigate/blob/master/examples/notebooks/sentiment_analysis.ipynb.

Alternatively, we can also build an attention models and select the keywords based on the attention values instead.
