### ISSUE TITLE
PyThaiNLP 1.8 -> PyThaiNLP 2.0

### ISSUE THREAD

**Issue by wannaphongcom** [PyThaiNLP/pythainlp#154]
เนื่องจาก PyThaiNLP กำลังมีการเปลี่ยนแปลงโครงสร้างและ API จำนวนมาก ผมจึงเสนอให้เวชั่นถัดไปของ PyThaiNLP เริ่มต้นที่ 2.0 แทน 1.8 เพื่อไม่ให้สับสนใช้ API ตัวเดิมที่ถูกเปลี่ยน

**Comment by bact** [comment]
สำหรับรายการความเปลี่ยนแปลง ดูได้ที่ #118 ครับ
