### ISSUE TITLE
[artagger] UnicodeDecodeError when read Thai.RDR file on Windows

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#155]
artagger fails to read Thai.RDR file on Windows, due to Unicode error (can't decode byte 0x8d in position 417)
https://ci.appveyor.com/project/wannaphongcom/pythainlp-9y1ch/builds/20163741

```
======================================================================
ERROR: test_pos_tag (tests.TestUM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\pythainlp-9y1ch\tests\__init__.py", line 277, in test_pos_tag
    str(type(pos_tag(word_tokenize("ผมรักคุณ"), engine="artagger"))),
  File "c:\projects\pythainlp-9y1ch\pythainlp\tag\__init__.py", line 36, in pos_tag
    return _tag(words, corpus=corpus)
  File "c:\projects\pythainlp-9y1ch\pythainlp\tag\__init__.py", line 29, in _tag
    words = Tagger().tag(" ".join(text))
  File "C:\Python36\lib\site-packages\artagger\__init__.py", line 43, in __init__
    self.load_model()
  File "C:\Python36\lib\site-packages\artagger\__init__.py", line 47, in load_model
    "rdr": open(os.path.join(os.path.dirname(__file__), "Models", "POS", "Thai.RDR"), "r").readlines(),
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 417: character maps to <undefined>
----------------------------------------------------------------------
```

The same code works well in Travis test (Linux).

**Comment by bact** [comment]
Still facing the same problem:
https://ci.appveyor.com/project/wannaphongcom/pythainlp-9y1ch/builds/20179054

**Comment by wannaphongcom** [comment]
artagger ต้องโหลดจาก GitHub ผม https://github.com/wannaphongcom/artagger เท่านั้นครับ ผมส่ง https://github.com/franziz/artagger/pull/5 เข้าไปหลายเดือนแล้วเขายังไม่รับครับ

**Comment by bact** [comment]
ขอบคุณครับ อืมม แบบนี้จะใช้ท่าไหนใน setup.py ดี

**Comment by bact** [comment]
- Need this fix to be merged to the main distribution (on PyPI) https://github.com/franziz/artagger/pull/5 in order to being able to use standard ```pip install artagger```
- Or should we modify setup.py somehow to download it for the user?

**Comment by bact** [comment]
Workaround #157 : ```pip install https://github.com/wannaphongcom/artagger/tarball/master#egg=artagger``` before ```pip install pythainlp[artagger]``` - this will make it possible to do test on AppVeyor (Windows environment).

Windows users should be aware this for their own installation -- already updated README.md.

**Comment by bact** [comment]
artagger issue. follow franziz/artagger#5 

close here for now.
