### ISSUE TITLE
[Documentation Improvement]: Difference between "etcc" vs "tcc"

### ISSUE THREAD

**Issue by c4n** [PyThaiNLP/pythainlp#188]
https://thainlp.org/pythainlp/docs/2.0/api/tokenize.html ในนี้ไม่บอกอะไรเลยอะครับ

**Comment by wannaphongcom** [comment]
ตามนี้ครับ https://www.researchgate.net/profile/Chonlasith_Jucksriporn/publication/262335479_Thai_Text_Phonetic_Transcription_Using_Thai_Minimum_Cluster/links/00463537504f048191000000/Thai-Text-Phonetic-Transcription-Using-Thai-Minimum-Cluster.pdf

**Comment by c4n** [comment]
> ตามนี้ครับ https://www.researchgate.net/profile/Chonlasith_Jucksriporn/publication/262335479_Thai_Text_Phonetic_Transcription_Using_Thai_Minimum_Cluster/links/00463537504f048191000000/Thai-Text-Phonetic-Transcription-Using-Thai-Minimum-Cluster.pdf

หาต้นฉบับ Inrut et al. 2001  ไม่เจอ T_T
วันนี้ลองเล่นดูเหมือน etcc มันพังๆอะครับตัดอะไรไม่ค่อยได้

**Comment by c4n** [comment]
ลองไปดูDocumentation ที่แก้เพิ่มได้ในนี้ครับ https://github.com/PyThaiNLP/pythainlp/pull/190  + ทำให้ subword_tokenize เรียก etcc ได้ด้วย
