### ISSUE TITLE
PyThaiNLP in Jython

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#19]
รัน PyThaiNLP ใน Jython ได้

ไม่กำหนดเวลาเริ่ม และ เส้นตาย

**Comment by wannaphongcom** [comment]
ปัญหาติดที่ PyICU , marisa_trie และ langdetect

**Comment by bact** [comment]
> ปัญหาติดที่ PyICU , marisa_trie และ langdetect

langdetect นี่ ถ้าอยากใช้ มีตัว cld3 ซึ่งเป็นรุ่นที่พัฒนาต่อมาจาก langdetect เดิมใน Chrome
https://github.com/google/cld3

มีคนพอร์ตเป็น Python ไว้ที่
https://github.com/Elizafox/cld3

แล้วก็มีคน fork มาแก้ต่อๆ กัน เพราะเหมือนตัวที่ Elizafox จะไม่ค่อยได้ดูแลต่อ
ผม fork มาแก้ doc ให้ชัดเจนถึงวิธีติดตั้งที่นี่ ถ้าต้องการใช้ฟังก์ชันการตรวจหาภาษาครับ
https://github.com/ThothMedia/cld3

**Comment by wannaphongcom** [comment]
ตอนนี้ trie รันใน python แล้วครับ ส่วนตัดคำน่าจะใช้งานใน jython ได้ แต่ดูเหมือนว่า jython 3 เหมือนจะไม่เสร็จสักทีแม้ผ่านมานานแล้ว https://github.com/jython/jython3 ไม่แน่ issue นี้อาจจะถูกปิดไปก่อนดีกว่าครับ

**Comment by heytitle** [comment]
is there any mandatory requirement that we should do this? 

Maybe providing an API Docker is sufficient for other languages.

**Comment by bact** [comment]
Close for now?

**Comment by wannaphong** [comment]
Jython 3 not further developed.
