### ISSUE TITLE
Fastcut : Fast Thai word tokenization using Deep Learning

### ISSUE THREAD

**Issue by wannaphongcom** [PyThaiNLP/pythainlp#210]
Fastcut : Fast Thai word tokenization using Deep Learning

**Comment by heytitle** [comment]
@cstorm125  are you working on this? I can help take a look on this issue.

**Comment by attapol** [comment]
@heytitle is working with me to look into different approaches to make thai word tokenization more robust (against typos, changes in genres) and speedy.

**Comment by wannaphongcom** [comment]
Build a word tokenizer that is comparable in speed to newmm but gets at least 90% accuracy based on BEST -  @cstorm125

**Comment by sakares** [comment]
Question: Do you have kind of benchmark in terms of inference speed from **newmm**, **deepcut** and so on? I am also developing on it too.

**Comment by heytitle** [comment]
hi,

I've done such a benchmark. Here is the plot. You can also find the code on [Colab][ref1].

![Unknown-3](https://user-images.githubusercontent.com/1214890/60240867-3d4a0900-98dc-11e9-97e9-9572850f9904.png)

Let me know if you have any further questions.
[ref1]: https://colab.research.google.com/drive/1SuNYLiwEkOln_WGP_BekumGP4CxRm9rp#scrollTo=Df2OPVVEFpbc

**Comment by heytitle** [comment]
Quoting from AttaCut's document. 


It's significantly faster than DeepCut but still not as fast as PyThaiNLP.

IMHO, this issue might be closed for now.

![](https://pythainlp.github.io/attacut/_images/speed-benchmark-ec2.png)

https://pythainlp.github.io/attacut/benchmark.html#speed

**Comment by cstorm125** [comment]
closing since AttaCut is out.
