### ISSUE TITLE
Thai dependency parser

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#218]
We require a thai treebank corpus for dependency parser. If you are interested, please contact back in this issue.

**Comment by heytitle** [comment]
could you please explain a bit more about what needed to be done here?

**Comment by wannaphongcom** [comment]
I require build dependency parsing for thai language to PyThaiNLP , but I hasn't a thai treebank corpus for dependency parser.

**Comment by KoichiYasuoka** [comment]
I've just tried to make a dependency parser for Thai with `pythainlp` and `UDPipe`, and released it as [spaCy-Thai](https://github.com/KoichiYasuoka/spaCy-Thai). I'm vague that its outputs are precise or not, but the word-lengths seem different between `pythainlp` and [UD_Thai-PUD](https://github.com/UniversalDependencies/UD_Thai-PUD). Umm...

**Comment by korakot** [comment]
As I understand, spaCy-Thai combines 3 parts into a pipeline
- spaCy for word tokenization (use pythainlp default internally)
- pyhainlp default pos_tag (=orchid) for POS
- UDPipe 1.2 trained on PUD for dependency parsing.

Word-length difference comes from the first part. We may need to use custom word list so the tokenization has the same word lengths. Maybe you can use pythainlp tokenization directly instead of through spaCy.

**Comment by wannaphong** [comment]
We have part of speech model with Parallel Universal Dependencies (PUD) treebanks. pos_tag (=pud)  https://www.thainlp.org/pythainlp/docs/2.2/api/tag.html#pythainlp.tag.pos_tag

I think that would be appropriate for your job.

**Comment by KoichiYasuoka** [comment]
In [th_pud-ud-orchid.conllu](https://raw.githubusercontent.com/KoichiYasuoka/spaCy-Thai/master/th_pud-ud-orchid.conllu) of [spaCy-Thai](https://github.com/KoichiYasuoka/spaCy-Thai) I use both PUD-origin UPOS-tags and pythainlp-origin ORCHID-tags. As shown in [train.sh](https://github.com/KoichiYasuoka/spaCy-Thai/blob/master/train.sh) I use hyper-parameters `embedding_upostag=10` for UPOS-tags and `embedding_xpostag=30` for ORCHID-tags. I've tried some other parameters, but either PUD-only or ORCHID-only was worse.

**Comment by wannaphong** [comment]
Have you tried LST20 corpus (tags mapped to Universal POS tags) yet? pos_tag (lst20_ud) (PyThaiNLP 2.2.4+ Only)
https://www.thainlp.org/pythainlp/docs/2.2/api/tag.html#pythainlp.tag.pos_tag

I haven't sent any new tags to spaCy.
> 
> 
> In [th_pud-ud-orchid.conllu](https://raw.githubusercontent.com/KoichiYasuoka/spaCy-Thai/master/th_pud-ud-orchid.conllu) of [spaCy-Thai](https://github.com/KoichiYasuoka/spaCy-Thai) I use both PUD-origin UPOS-tags and pythainlp-origin ORCHID-tags. As shown in [train.sh](https://github.com/KoichiYasuoka/spaCy-Thai/blob/master/train.sh) I use hyper-parameters `embedding_upostag=10` for UPOS-tags and `embedding_xpostag=30` for ORCHID-tags. I've tried some other parameters, but either PUD-only or ORCHID-only was worse.

**Comment by KoichiYasuoka** [comment]
>Have you tried LST20 corpus (tags mapped to Universal POS tags) yet?

No, I have not. I've first started with [tag_map.py](https://github.com/explosion/spaCy/blob/master/spacy/lang/th/tag_map.py) of `spacy.lang.th` so I've been using ORCHID and UPOS. Do you have a plan to include LST20 tag_map for official release of spaCy in the future?

**Comment by wannaphong** [comment]
> 
> 
> > Have you tried LST20 corpus (tags mapped to Universal POS tags) yet?
> 
> No, I have not. I've first started with [tag_map.py](https://github.com/explosion/spaCy/blob/master/spacy/lang/th/tag_map.py) of `spacy.lang.th` so I've been using ORCHID and UPOS. Do you have a plan to include LST20 tag_map for official release of spaCy in the future?

I working about this pull request. https://github.com/explosion/spaCy/pull/6163

**Comment by wannaphong** [comment]
@KoichiYasuoka  They're phasing out tag maps in the core spacy library in v3. https://github.com/explosion/spaCy/pull/6163#issuecomment-704803365

**Comment by KoichiYasuoka** [comment]
I'm not so familiar with the "v3" of spaCy, but here I understand that spaCy's `Token.tag_` and `Token.pos_` are now free from one another. I had given up to use `train` of spaCy for [th_pud-ud-orchid.conllu](https://raw.githubusercontent.com/KoichiYasuoka/spaCy-Thai/master/th_pud-ud-orchid.conllu), then... well... how will I change my spaCy-Thai when the "v3" launch...

**Comment by korakot** [comment]
If there's a problem with Thai Tokenizer. You can use a custom tokenizer with your own word list. Here's how to change it in spaCy.

```python
!pip install pythainlp
import pythainlp
from pythainlp.corpus import ttc

# create custom tokenizer
min_words = [w for w,_ in ttc.word_freqs()]  # can add to it
tok = pythainlp.Tokenizer(min_words)

from spacy.lang.th import Thai
nlp = Thai()
nlp.tokenizer.word_tokenize = tok.word_tokenize # change to custom
list(nlp('ฝนตกที่ทะเล'))  
# ['ฝน', 'ตก', 'ที่', 'ทะเล']  because no 'ฝนตก' in min_words
```

**Comment by wannaphong** [comment]
I will close this issues and I will add `spaCy-Thai` recommend for `Thai dependency parser` to PyThaiNLP Documentation.

Thank you @KoichiYasuoka for `dependency parser`

**Comment by wannaphong** [comment]
Done.

Notebook: https://github.com/PyThaiNLP/tutorials/blob/master/source/notebooks/Thai_Dependency_Parser.ipynb
Website: https://pythainlp.github.io/tutorials/notebooks/Thai_Dependency_Parser.html
