### ISSUE TITLE
Elementary discourse unit segmentation

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#225]
Elementary discourse unit (EDU) is a linguistic unit that larger than a word and smaller than sentence. It contains one piece of information. EDUs and their relationships are basis for constructing discourse structure.

Listed here are papers that discuss how to do Thai EDU segmentation computationally:
- https://www.aclweb.org/anthology/Y13-1052
- http://arts.tu.ac.th/file/PDF_15.pdf
- https://arts.tu.ac.th/file/Jpdf_1.pdf
- https://pdfs.semanticscholar.org/0d21/ab73b44872434358d042a4bc8eb4c303c62a.pdf
- http://www.arts.chula.ac.th/~ling/thesis/2556MA-LING-Nalinee.pdf
- http://dric.nrct.go.th/Search/SearchDetail/177303

We may start this by compiling a list of Thai discourse markers.

Related to #73 (Sentence tokenizer for Thai)

**Comment by cstorm125** [comment]
We should compile these markers. It'd be useful for #337 also.

**Comment by bact** [comment]
> We should compile these markers. It'd be useful for #337 also.

Agree. I have add few more words to STARTERS and ENDERS. But I think that will require us to retrain the model?

**Comment by wannaphong** [comment]
Now, PyThaiNLP has a clause segmentation from LST20 corpus.  I thinks we should close this issue.

**Comment by bact** [comment]
Discourse unit is not necessarily equal to clause. 
But we can close this for now.

**Comment by wannaphong** [comment]
> 
> 
> Discourse unit is not necessarily equal to clause.
> But we can close this for now.

OK
