### ISSUE TITLE
Questions on the implementation of syllable_tokenize

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp#229]
**Describe the bug**
According to the current implementation, [`syllable_tokenize`][st] firstly uses `word_tokenize`, breaking the string into words then do the actual syllable tokenization.

I'm wondering whether the use of `word_tokenize` is necessary. IMHO, we could immediately perform syllable tokenization on the given input. For example, we might do the following:
**Proposed Source Code**
```
def modified_syllable_tokenize(text: str) -> List[str]:
    """
    :param str text: input string to be tokenized
    :return: list of syllables
    """

    if not text or not isinstance(text, str):
        return []

    trie = dict_trie(dict_source=thai_syllables())
    return word_tokenize(text=text, custom_dict=trie)
```

With this change, the current implementation takes ~30ms to syllable-tokenise ~2000 characters text, while the proposed version takes only ~23ms. 

Indeed, more throughout evaluation is required and this change would definitely affect the quality of syllable tokenisation. One issue that I've found is the split of `(` in front of `noun`. For example, 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/1214890/58688380-7448ff80-83ae-11e9-8f42-41f805f8c2f3.png">

[st]: https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tokenize/__init__.py#L153

**Comment by heytitle** [comment]
@wannaphongcom 

I've performed a benchmark comparing the execution of the two syllable tokenisations. I would say the new proposed version is at least **20% faster**, measuring on 200-char text, and the improvement is gradually significant for longer texts. 

Please see the results here:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1214890/58743200-54214b00-8457-11e9-9379-34a8c9402e62.png">

[Link to Colab][1]

[1]: https://colab.research.google.com/drive/13ULZs-xsO4RAkOF9lu_BKApLV-KHeK5y

**Comment by heytitle** [comment]
Hi,

I've tested whether the behaviour of the modified syllable tokeniser is the same. Using [this set of commands][1], I found that there are a couple of issues that the two versions produce different syllable lists.

```
$ diff  original-sy-token.txt new-sy-token.txt
5c5
< ผม~ว่า~ ~(~บท~ความ~)~นี้~สนุก~มาก
---
> ผม~ว่า~ ~(บท~ความ~)~นี้~สนุก~มาก
33c33
< ใน~ทาง~จิต~วิทยา~ ~เคย~มี~คน~พูด~ถึง~ภา~วะ~ที่~เรียก~ว่า~ ~‘~Post~ ~Commencement~ ~Stress~ ~Disorder~’~ ~(~PCSD~)~ ~หรือ~อา~การ~ความ~เศร้า~ที่~เกิด~ขึ้น~หลัง~จาก~เรียน~จบ~ ~ซึ่ง~จะ~เกิด~ขึ้น~เพราะ~ไม่~รู้~ว่า~ ~ชี~วิต~หลัง~จาก~เรียน~จบ~จะ~เดิน~ไป~ทาง~ไหน~ต่อ~ดี~ ~เมื่อ~ต้อง~เดิน~ออก~จาก~พื้น~ที่~ปลอด~ภัย~ที่~เรียก~ว่า~มหา~วิทยา~ลัย~ไป~แล้ว
---
> ใน~ทาง~จิต~วิทยา~ ~เคย~มี~คน~พูด~ถึง~ภา~วะ~ที่~เรีย~กว่า~ ~‘~Post~ ~Commencement~ ~Stress~ ~Disorder~’~ ~(~PCSD~)~ ~หรือ~อา~การ~ความ~เศร้า~ที่~เกิด~ขึ้น~หลัง~จาก~เรียน~จบ~ ~ซึ่ง~จะ~เกิด~ขึ้น~เพราะ~ไม่~รู้~ว่า~ ~ชี~วิต~หลัง~จาก~เรียน~จบ~จะ~เดิน~ไป~ทาง~ไหน~ต่อ~ดี~ ~เมื่อ~ต้อง~เดิน~ออก~จาก~พื้น~ที่~ปลอด~ภัย~ที่~เรีย~กว่า~มหา~วิทยา~ลัย~ไป~แล้ว

```

What do you think about the results?
[1]: https://gist.github.com/heytitle/f1ca4e7d85b587c596a3b00bfa388ccc

**Comment by wannaphongcom** [comment]
@heytitle I think you should add rules to tokenize syllables. ex (บท~ความ~) -> (~บท~ความ~)

**Comment by heytitle** [comment]
is this issue still relevant?

**Comment by bact** [comment]
Should we close this as we now happy with ssg?

**Comment by heytitle** [comment]
@bact yep, I'm closing it now.
