### ISSUE TITLE
Alternative syllable tokenizer 

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp#237]
Hi,

@ponrawee has made a syllable tokeniser using CRF, codenamed `ssg`. Its performance is comparable to PyThaiNLP's algorithm, but faster.  

## [Performance Comparison][result]
PyThaiNLP's algorithm is used ground truth.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/1214890/61200948-3826ef80-a70d-11e9-87a9-be6247295be3.png">

## [Speed Comparison][notebook]
- Without newline splitting
<img width="523" alt="image" src="https://user-images.githubusercontent.com/1214890/61200759-b8008a00-a70c-11e9-8c63-f38dcccc19b8.png">

~~Nevertheless, we suspect that ssg's featurizer is not optimal, causing its speed on long text is much lower than PyThaiNLP.~~

- With newline splitting
<img width="509" alt="image" src="https://user-images.githubusercontent.com/1214890/61201428-ad46f480-a70e-11e9-9511-dfcab77591ef.png">

Repository: https://github.com/ponrawee/ssg

[notebook]: https://colab.research.google.com/drive/1ssqHG5EZ5hHL6ZjlxOuvbNlwC7ZxDe7x#scrollTo=Df2OPVVEFpbc

[result]: https://pythainlp.github.io/tokenization-benchmark-visualization/?experiment-name=Syllable-Tokenisation-PyThaiNLP-vs-CRF&q=%E0%B8%88%E0%B8%A3%E0%B8%A3%E0%B8%A2%E0%B8%B2

**Comment by heytitle** [comment]
hi, 

`ssg` is now available via `pip` with CI-integrated and unit-tests added.  
```
$ pip install ssg
```

**Comment by wannaphongcom** [comment]
@heytitle You can add `ssg` like deepcut in `subword_tokenize`, `syllable_tokenize`.

**Comment by heytitle** [comment]
^ cc: @ponrawee
