### ISSUE TITLE
newmm tokenizer bug/problem ?

### ISSUE THREAD

**Issue by dogterbox** [PyThaiNLP/pythainlp#239]
```
from pythainlp.tokenize.newmm import segment
# PyThaiNLP 2.0.6

text = 'ชั้ลเครียสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสส'

tokens = segment(text)
print(tokens)
```

ที่มาก็คือว่า ผมทำโปรเจ็ควิเคราะห์ Text อยู่โปรเจ็คหนึ่ง
ตอนแรกเข้าใจว่าข้อมูลมันค่อนข้างเยอะ อาจจะใช้เวลาตัดคำนานหน่อย
แต่ทว่าพอรอนานๆเข้า รู้สึกว่ามัน**นานผิดปกติ**เกินไปแล้ว
สุดท้ายเลยตัดสินใจปริ้นเช็ครัวๆ ปรากฏว่ามันไปติดอยู่ตรงข้อความนี้

```
ชั้ลเครียสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสสส
```

ทำเอาผมนี่เครียสสสสสเลยครับ55555
แต่ทดลองใช้ longest แล้วมันก็ออกนะครับ
ไม่แน่ใจว่ามันติดตรง TCC หรือป่าวครับ
ขอบคุณมากครับ 😁🙏

**Comment by heytitle** [comment]
@dogterbox ขอบคุณครับ เดี๋ยวจะลองดูให้นะครับ

 ในกรณีนี้อาจจะลองทำ preprocess ไปก่อนด้วย
```
ชั้ลเครียสสสส -> ชั้ลเครียส
``

**Comment by cstorm125** [comment]
You can also use something like `pythainlp.ulmfit.replace_rep_after` to clean up.
