### ISSUE TITLE
pythainlp.word_tokenize ปัญหาตัดคำประโยคที่ยาวต่อเนื่องโดยไม่มี space [newmm]

### ISSUE THREAD

**Issue by espressofx** [PyThaiNLP/pythainlp#241]
**Describe the bug**
มีปัญหา execute ใช้เวลานานมาก กับประโยคที่ยาวต่อเนื่องโดยไม่มี space แบ่ง
เช่น ประโยค

ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า

แต่ถ้ามีการแบ่งประโยคโดยมี space จะไม่มีปัญหา เช่น

ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า ด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้าด้านหน้า

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Python 3.6
 - Pythainlp 2.0.5

**Comment by espressofx** [comment]
จาก notebook ต้อง interrupt kernel

![Screenshot from 2019-07-26 17-17-46](https://user-images.githubusercontent.com/1804119/61945099-5b815280-afc9-11e9-9b7d-fd20f71dfd03.png)

**Comment by bact** [comment]
My need some rule to stop generating word graphs when reaching a threshold. 

คิดว่าในโค้ดที่พยายามสร้างทางที่เป็นไปได้ที่จะตัดคำ น่าจะต้องมีกำหนดไว้ ว่าจะทำถึงแค่ไหน เกินนี้จะบังคับหยุด ไม่งั้นมันจะสร้างไปเรื่อยๆ จนช้ามากๆ

**Comment by wannaphongcom** [comment]
Colab : https://colab.research.google.com/drive/1MOZ7GZ9x_P75wUQtz0C2Fl52GPRhJO4g

**Comment by heytitle** [comment]
I guess this result comes from `newmm`? Should we label it with `newmm`?

**Comment by bact** [comment]
Proposal for the fix:
- break the input text into smaller chunks (100±25)
  - chunking strategy should take into account the invalid token separation point (this can be either word or syllable)
- tokenizes each chunks and combine tokens together

See code here 
https://github.com/PyThaiNLP/pythainlp/tree/fix-newmm-longtext

Warn that this may make the tokenization slower.

Current chunk size is 100
(Have tried 400, too slow).

Current window to scan possible break points between chunks is 25+25 = 50
(the longest word in dictionary is 70 chars)

Please comment

**Comment by bact** [comment]
A new segmentation "engine" has been proposed for this, one can now use `newmm-safe` engine to avoid the problem of waiting too long for text like one in the example above. Now available in `fix-newmm-longtext` branch and will soon in `dev` branch.

ต่อไปจะมี engine ใหม่ชื่อ `newmm-safe` เพื่อแก้ปัญหานี้ครับ
