### ISSUE TITLE
Merge tokenization-benchmark to PyThaiNLP

### ISSUE THREAD

**Issue by wannaphongcom** [PyThaiNLP/pythainlp#247]
from [tokenization-benchmark](https://github.com/PyThaiNLP/tokenization-benchmark), We will merge tokenization benchmark to PyThaiNLP.

tokenization-benchmark Developed by @heytitle

**Comment by heytitle** [comment]
One issue that might arise is the fact that the module has a CLI interface. We might need to write a wrapper from PyThaiNLP for using the interface.

**Comment by wannaphongcom** [comment]
Done https://github.com/PyThaiNLP/pythainlp/pull/248
