### ISSUE TITLE
[Question] Is this an expected behavior for soundex lk82? [ไทย, ไท, ทัย, ทาย]

### ISSUE THREAD

**Issue by charleech** [PyThaiNLP/pythainlp#256]
**Question**
I'm using the `pythainlp.soundex.soundex()` with `lk82` and found some confusion that the `ภาษาไทย` is not equal to `ภาษาทัย`, while `ไทย` is equal to `ทัย`.

The `ไทย`, `ไท` and `ทัย` give us `ท7000`, while the `ภาษาไทย` give us `พ9397`, but `ภาษาทัย` give us `พ9393`. Is this an expected behavior?

I understand that the `ภาษาไทย` and `ภาษาทัย` should give us the same result as  `พ9397`. Could you please help to advise?

**To Reproduce**
1. `from pythainlp.soundex import soundex`
2. `soundex("ไทย","lk82"), soundex("ไท","lk82"),  soundex("ทัย","lk82"), soundex("ทาย","lk82")`
    - result = `('ท7000', 'ท7000', 'ท7000', 'ท9700')`
3. `soundex("ภาษาไทย","lk82"), soundex("ภาษาไท","lk82"),  soundex("ภาษาทัย","lk82"), soundex("ภาษาทาย","lk82")`
    - result = `('พ9397', 'พ9397', 'พ9393', 'พ9393')`

**Desktop :**
 - OS: `Windows 10 Home 1903 `
 - Python Version 
    - `Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]`
 - Version `pythainlp==2.0.7`

**Comment by korakot** [comment]
It works as expected in the paper.

It detects if the first char is consonant, and switch with the second character if not.

So, ไทย -> ทไย, which is similar to ทัย. But if it is not the first char. There is no switching.(though you could implement it on your own if you like).
