### ISSUE TITLE
เรียกใช้ sentiment ไม่ได้ครับ

### ISSUE THREAD

**Issue by taechasit** [PyThaiNLP/pythainlp#257]
`from pythainlp.sentiment import sentiment`
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-eef4718bb252> in <module>
----> 1 from pythainlp.sentiment import sentiment

ModuleNotFoundError: No module named 'pythainlp.sentiment'

PyThaiNLP 2.0.7

ผมลองดูจากในเน็ตก็โค้ดเดียวกันแต่ไม่ได้ครับ
ช่วยผมด้วยนะครับ ผมเป็นมือใหม่อยู่

**Comment by heytitle** [comment]
สวัสดีครับ

`module sentiment` ได้ถูกเอาออกจาก PyThaiNLP ไปแล้วครับ ([อ้างอิง][ref]). 

ตัวอย่างเกี่ยวกับการทำ Sentiment Analysis สามารถดูได้ที่ [PyThaiNLP/Tutorial/Sentiment-Analysis][url]

ผมขอปิดตัว issue นะครับ

[ref]: https://github.com/PyThaiNLP/pythainlp/releases/tag/2.0
[url]: https://www.thainlp.org/pythainlp/tutorials/notebooks/sentiment_analysis.html
