### ISSUE TITLE
Integrate AttaCut to PyThaiNLP

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp#258]
[AttaCut][attacut] has been recently released. It would be great if we can integrate it into PyThaiNLP's ecosystem. 

Below is the speed benchmark of AttaCut comparing to PyThaiNLP and DeepCut:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/1214890/63656479-84496300-c794-11e9-8b0b-dce2a362aaa0.png">
**Note**: 
- AttaCut-SC uses syllable and character features, while AttaCut-C uses only character features.
- This benchmark is done on [Colab][colab] and results on actual production environments might be different.

From what I see, the integration is quite straightforward because AttaCut already has an higher-level API that one can import and use its functionalities. 

```
from attacut import Tokenizer

atta = Tokenizer(model="attacut-sc")
atta.tokenizer(txt)
```

More information can be found at: https://github.com/heytitle/attacut#higher-level-inferface.

Related to #210 

[colab]: https://colab.research.google.com/drive/1SuNYLiwEkOln_WGP_BekumGP4CxRm9rp#scrollTo=Df2OPVVEFpbc
[attacut]: https://github.com/heytitle/attacut

**Comment by bkktimber** [comment]
I added `attacut` already. Do you have any contribution guideline so I can follow before push to github?

thx

**Comment by heytitle** [comment]
@bkktimber I've published a new version of AttaCut with `tokenize` fuction that instantiates only one tokenizer.  Please see the document on how to use it. 

https://pythainlp.github.io/attacut/#higher-level-interface

Could you please update the PR accordingly? :)

**Comment by bkktimber** [comment]
sure. will do over this weekend.

thank you

**Comment by wannaphongcom** [comment]
Done

**Comment by bact** [comment]
- attacut wrapper is at https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tokenize/attacut.py
- `engine="attacut"` is now available for `pythainlp.tokenize.word_tokenize()`
