### ISSUE TITLE
ERROR: Command errored out with exit status 1 & ERROR: Failed building wheel for marisa-trie

### ISSUE THREAD

**Issue by NamOrawan** [PyThaiNLP/pythainlp#260]
**Describe the bug**
ERROR: Command errored out with exit status 1
ERROR: Failed building wheel for marisa-trie
 2 error ค่ะ

เพิ่งใช้ pip install pythinlp ครั้งแรกค่ะกดรันแล้วก็เป็นตามภาพเลย
เป็นมือใหม่อยู่ค่ะ รบกวนช่วยหนูหน่อยนะคะ จะใช้ทำโปรเจคจบค่ะ
![pythainlp 1](https://user-images.githubusercontent.com/54061141/63953342-5d986e80-caab-11e9-941f-a01ae3615702.jpg)
![pythainlp 2](https://user-images.githubusercontent.com/54061141/63953343-5d986e80-caab-11e9-81b9-2c7943496103.jpg)

**Comment by wannaphongcom** [comment]
ให้โหลด https://github.com/PyThaiNLP/pythainlp/blob/dev/install_pythainlp.bat แล้วดับเบิ้ลคลิก install_pythainlp.bat แล้วมันจะติดตั้งให้เองครับ

**Comment by NamOrawan** [comment]
ได้แล้วค่ะ ขอบคุณมากๆนะคะ :)
