### ISSUE TITLE
C extension not loaded, training will be slow

### ISSUE THREAD

**Issue by NamOrawan** [PyThaiNLP/pythainlp#263]
ตามหัวข้อเลยค่ะ รัน Training model นานมากๆ ต้องแก้ยังไงคะ
**แนบรูปตอนรันกับสเปคคอมมาค่ะ
![69277757_744834919281550_4740387101453844480_n](https://user-images.githubusercontent.com/54061141/64078228-1a840880-cd02-11e9-83cb-45ca81a32081.png)
![Inked69945103_2490738017918810_6792629536132431872_n_LI](https://user-images.githubusercontent.com/54061141/64078229-1bb53580-cd02-11e9-930c-3e2311cde6c1.jpg)

**Comment by wannaphongcom** [comment]
ขอดูโค้ด train_word2vec_model.py ได้ไหมครับ

**Comment by NamOrawan** [comment]
![image](https://user-images.githubusercontent.com/54061141/64078856-65a21980-cd0a-11e9-89ab-84a127cb454a.png)
นี่ค่ะ

**Comment by heytitle** [comment]
ดูจาก ตัว `train_word2vec_model.py` เหมือนจะไม่เกี่ยวกับ PyThaiNLP เพราะเห็นมีแค่ใช้งาน `Gensims`

**Comment by bact** [comment]
เป็นเพราะตอนติดตั้ง gensim ในเครื่องเรายังไม่มี C compiler ครับ
ตัว gensim เลยไม่สามารถคอมไพล์ให้เป็นตัวที่เร็วได้
ทางแก้ก็คือ ติดตั้ง C compiler ก่อน แล้วค่อยติดตั้ง gensim อีกที

บน Windows มีวิธีแก้อยู่ครับ ตามนี้ https://stackoverflow.com/a/55797783

ขออนุญาตปิด issue นะครับ
