### ISSUE TITLE
Tokenization benchmark miscalculate word-level metrics

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp#268]
Reported by @korakot, as described in [the benchmark document][url], the correct counting at word-level should be ✗✗✓✗, not ✓✗✓✗.

![](https://www.thainlp.org/pythainlp/docs/dev/_images/evaluation.png)

[url]: https://www.thainlp.org/pythainlp/docs/dev/api/benchmarks.html

**Comment by heytitle** [comment]
It turns out that the code is correct.  The PR is about refactoring some part of the code that is redundant. 

After merging,  please also **rebuild** the document as I've updated the tokenization benchmark figure.

**Comment by wannaphongcom** [comment]
@heytitle It's automatically build/deploy documentation after merge PR.

**Comment by heytitle** [comment]
@wannaphongcom  great I didn't know that. could you please review it?

**Comment by wannaphongcom** [comment]
Now, I merge this PR.

**Comment by bact** [comment]
Fixed with https://github.com/PyThaiNLP/pythainlp/pull/269
