### ISSUE TITLE
Remove /notebooks directory, as they moved to "tutorials" repo already

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#270]
This directory should be removed
- https://github.com/PyThaiNLP/pythainlp/tree/dev/notebooks

as they already moved to this repo: https://github.com/PyThaiNLP/tutorials

All future official tutorials (including Jupyter notebooks) should be at https://github.com/PyThaiNLP/tutorials

**Comment by cstorm125** [comment]
@artificiala I think we can do this as discussed. Can you make sure the tutorials will update from https://github.com/PyThaiNLP/tutorials? Not high priority.

**Comment by artificiala** [comment]
Now, all the notebooks in `PyThaiNLP/tutorials` are the same as notebooks listed in `PyThaiNLP/pythainlp/tree/dev/notebooks`

We could remove the directory `notebooks` from this repo.
