### ISSUE TITLE
numeric string gives "ใน" as output in some length of string.

### ISSUE THREAD

**Issue by nawaphonOHM** [PyThaiNLP/pythainlp#276]
**Describe the bug**
I used `correct` module in `spell` package. It gave incorrect outputs where the input-strings have length-string less than or equal 2 of its.

**To Reproduce**
1. `from pythainlp.spell import correct.`
2. try give inputs in this set ->  **{'0', '1', '2', ..., '99'}** or whatever numeric-strings which have length <= 2.

**Expected behavior**
Should return output same as the input where the inputs are numeric.

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version 3.6.8
 - Version pythainlp 2.0.7

**Comment by Peradon** [comment]
#288 I just submitted the PR

**Comment by bact** [comment]
Fixed by #288
