### ISSUE TITLE
cannot import name 'stopwords' from 'pythainlp.corpus' .......

### ISSUE THREAD

**Issue by wirapong** [PyThaiNLP/pythainlp#286]
![image](https://user-images.githubusercontent.com/3756553/66096391-095e3e00-e5c5-11e9-8421-cc0508c9b274.png)

**Comment by wannaphongcom** [comment]
You can import `stopword` from `pythainlp.corpus.common.thai_words()`. https://www.thainlp.org/pythainlp/docs/dev/api/corpus.html#pythainlp.corpus.common.thai_stopwords

**Comment by bact** [comment]
Solved?

**Comment by wirapong** [comment]
No, problem can not fix.

**Comment by bact** [comment]
`from pythainlp.corpus import thai_stopwords`

**Comment by wirapong** [comment]
OK, I got it. Thanks.
