### ISSUE TITLE
ERROR: Failed building wheel for marisa-trie ตอน pip install บน MacOS

### ISSUE THREAD

**Issue by Planxnx** [PyThaiNLP/pythainlp#289]
พิมคำสั่ง ` pip install pythainlp`
แล้วขึ้นตามรูปเลยครับ ลองแก้ตาม https://github.com/PyThaiNLP/pythainlp/issues/260#issuecomment-526238698 ก็ไม่ได้ครับ

![messageImage_1570112991805](https://user-images.githubusercontent.com/37617738/66139414-9687ae00-e62a-11e9-84dc-57d09e15aa99.jpg)

> * OS: macOS Catalina 10.15 beta (19A578c)
> * Python 3.7
> * Pythainlp 2.0.7

รบกวนด้วยครับ ตอนนี้กำลังทำโปรเจคแล้วติดที่ตอนลง lib อย่างเดียวเลยครับ

**Comment by wannaphongcom** [comment]
ลอง `pip install --pre pythainlp` ดูนะครับ เป็นเวชั่นสำหรับนักพัฒนาก่อนปล่อยเวชั่นจริง 2.1 โดยเราลบ `marisa-trie` ออกไปจาก PyThaiNLP แล้วครับ

**Comment by Planxnx** [comment]
> ลอง `pip install --pre pythainlp` ดูนะครับ เป็นเวชั่นสำหรับนักพัฒนาก่อนปล่อยเวชั่นจริง 2.1 โดยเราลบ `marisa-trie` ออกไปจาก PyThaiNLP แล้วครับ

ลงได้แล้วครับ แต่ตอน import ไลบรารี่แล้ว Error ครับ 
![messageImage_1570118491518](https://user-images.githubusercontent.com/37617738/66147170-7c54cc80-e638-11e9-85ca-f8dd773d951a.jpg)

![messageImage_1570121663825](https://user-images.githubusercontent.com/37617738/66147660-76abb680-e639-11e9-8899-047434e8026b.jpg)

**Comment by wannaphongcom** [comment]
ลอง `pip install pandas` ครับ

**Comment by Planxnx** [comment]
ได้แล้วครับ ขอบคุณมากครับ
