### ISSUE TITLE
ERROR: Command errored out with exit status 1: 

### ISSUE THREAD

**Issue by Bas10699** [PyThaiNLP/pythainlp#301]
ใช้ pip install pythinlp แล้วไม่ได้ครับ
ลองใช้ pip install --pre pythainlp แล้วครับ แต่ก็ยัง No module named 'pythainlp' ครับ

Collecting pythainlp
  Using cached https://files.pythonhosted.org/packages/37/94/1ca5c23bfdbc0f27fa26e5eeda47d8ff422cbbd3f38c0b8a160fa17a2583/pythainlp-2.0.7-py3-none-any.whl
Requirement already satisfied: tinydb in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from pythainlp) (3.14.2)
Requirement already satisfied: pytz in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from pythainlp) (2019.2)
Requirement already satisfied: nltk>=3.2.2 in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from pythainlp) (3.4.4)
Collecting marisa-trie (from pythainlp)
  Using cached https://files.pythonhosted.org/packages/20/95/d23071d0992dabcb61c948fb118a90683193befc88c23e745b050a29e7db/marisa-trie-0.7.5.tar.gz
Requirement already satisfied: dill in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from pythainlp) (0.3.1.1)
Requirement already satisfied: tqdm in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from pythainlp) (4.36.1)
Requirement already satisfied: requests in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from pythainlp) (2.22.0)
Requirement already satisfied: six in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from nltk>=3.2.2->pythainlp) (1.12.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from requests->pythainlp) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from requests->pythainlp) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from requests->pythainlp) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tony_b\appdata\local\programs\python\python37-32\lib\site-packages (from requests->pythainlp) (2019.6.16)
Installing collected packages: marisa-trie, pythainlp
  Running setup.py install for marisa-trie: started
    Running setup.py install for marisa-trie: finished with status 'error'

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Tony_B\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tony_B\\AppData\\Local\\Temp\\pycharm-packaging\\marisa-trie\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tony_B\\AppData\\Local\\Temp\\pycharm-packaging\\marisa-trie\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tony_B\AppData\Local\Temp\pip-record-xjm0beik\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Tony_B\AppData\Local\Temp\pycharm-packaging\marisa-trie\
    Complete output (5 lines):
    running install
    running build
    running build_clib
    building 'libmarisa-trie' library
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Tony_B\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tony_B\\AppData\\Local\\Temp\\pycharm-packaging\\marisa-trie\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tony_B\\AppData\\Local\\Temp\\pycharm-packaging\\marisa-trie\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tony_B\AppData\Local\Temp\pip-record-xjm0beik\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by wannaphongcom** [comment]
ผมรบกวนขอ log เวลาเรียกใช้คำสั่งติดตั้ง `pip install --pre pythainlp` ด้วยครับ

**Comment by Bas10699** [comment]
ได้แล้วครับ
ผมติดตั้ง Microsoft Visual C++ 14.0 ใหม่ 
https://visualstudio.microsoft.com/visual-cpp-build-tools/
ขอบคุณครับ
