### ISSUE TITLE
การทำ Word2Vec. 

### ISSUE THREAD

**Issue by NamOrawan** [PyThaiNLP/pythainlp#313]
อยากทราบถามว่าเราสามารถนำไฟล์ .text ที่ตัดคำจาก pythainlp ไป train model โดยใช้ gensim ได้เลยไหมคะ หรือต้องแก้ไขโค้ดยังไงคะ พอดีอยากได้คำและค่าเวกเตอร์ออกมาค่ะ

ไฟล์ที่ตัดคำแล้ว 
![Annotation 2019-10-23 224950](https://user-images.githubusercontent.com/54061141/67487936-04a71a00-f699-11e9-8f3e-d9e3669003c5.png)

ไฟล์การ train model 
![Annotation 2019-10-23 224825](https://user-images.githubusercontent.com/54061141/67487976-21dbe880-f699-11e9-80ca-7af6b7b222da.png)

**Comment by wannaphongcom** [comment]
โหลดทุกบรรทัดมาใส่ใน list แล้ว train ได้ครับ

**ตัวอย่าง**

```
>>> from gensim.models import Word2Vec
>>> sentences = [["cat", "say", "meow"], ["dog", "say", "woof"]] # load ทุกประโยคเป็น list
>>> model = Word2Vec(sentences, min_count=1)
```

จาก https://radimrehurek.com/gensim/models/word2vec.html
