### ISSUE TITLE
Website improvement

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp#314]
Consider a new user. At the moment, it takes a couple of steps util he/she can see the latest document. These are my suggestions:
1. remove the first two pages. if their content is considered meaningful, we might bring the content become part of the document.
2. Redirect the main url to the stable document. Development and previous version documents should also be accessible from the stable document. 

Doing these will let the document be only one access point of the project. It might also help PythaiNLP's SEO presence.

![image](https://user-images.githubusercontent.com/1214890/67898290-54d22080-fb60-11e9-89ca-f96ed67e4700.png)

**Comment by wannaphong** [comment]
I add PyThaiNLP Logo on https://github.com/PyThaiNLP/pythainlp/commit/588921ad7e114ed5ac6bf55b1300ca5019c8fe16.

**Comment by wannaphong** [comment]
Done

Website: [pythainlp.github.io](https://pythainlp.github.io)
GitHub:  [PyThaiNLP/pythainlp.github.io](https://github.com/PyThaiNLP/pythainlp.github.io)
