### ISSUE TITLE
เกิด error การตัดคำโดยใช้ deepcut 

### ISSUE THREAD

**Issue by NamOrawan** [PyThaiNLP/pythainlp#320]
![Annotation 2019-11-06 214024](https://user-images.githubusercontent.com/54061141/68308991-5b244780-00e0-11ea-8487-566fb61e984a.png)
![Annotation 2019-11-06 214121](https://user-images.githubusercontent.com/54061141/68308992-5b244780-00e0-11ea-831a-7245d2306c82.png)
โค้ดที่ใช้รัน deepcut ค่ะ ทั้ง2โค้ดนี้พอรันแล้วเกิด error คล้ายๆกัน ต้องแก้ไข้ยังไงคะ 

![Annotation 2019-11-06 213716](https://user-images.githubusercontent.com/54061141/68309080-7db66080-00e0-11ea-8179-544641456b51.png)

**Comment by heytitle** [comment]
สวัสดีครับ

อันนี้น่าจะเป็น error จากทาง DeepCut ไม่ใช่จากทาง PyThaiNLP 

อาจจะต้องอัพเดทตัว DeepCut ครับ ดูรายละเอียดเพิ่มเติมได้ที่ https://github.com/rkcosmos/deepcut/pull/63.

**Comment by heytitle** [comment]
เอาอาจจะปิดคำถามนี้ไปก่อน?

**Comment by wannaphongcom** [comment]
@NamOrawan ถ้ายังเกิดปัญหานี้ให้ reopen issues นี้นะครับ
