### ISSUE TITLE
Should we merge syllable_tokenize() and subword_tokenize() together?

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#322]
They are both subword level. 

Currently we have 2 level of analysis and 4 kinds of implementations ("engines"):

- TCC-based
  - Original TCC
  - Extended TCC
- Syllable
  - Using syllable dictionary
  - Using CRF (ssg)

Should we call them all "subword"?

Note: currently "ssg" is available as an option in both syllable_tokenize() and subword_tokenize().

**Comment by wannaphong** [comment]
We should probably combine these two things into subword.
