### ISSUE TITLE
บางคำประโยคติด Loop ครับ ที่  _bfs_paths_graph

### ISSUE THREAD

**Issue by lolgolflol** [PyThaiNLP/pythainlp#326]
**Describe the bug**

**To Reproduce**
1. import '...'
from pythainlp import word_tokenize
2. input '....'
word_tokenize("ชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิ")

**Expected behavior**
- ออกมาเป็นอะไรก็ได้ครับ  เช่น ออกมาเป็น ชิชิชิชิชิ หรือมีวิธีดักเคส ในกรณีติด loop บางไหมครับ 
**Source Code**
If applicable, add source code to help explain your problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows,Linux]
     -  Linux
 - Python Version [e.g. 2.7, 3.6]
      - Python3
     - version 2.0.6

**Additional context**
เอาข้อมูล chat มาวิเคราะห์ด้วยการตัดคำออกมา พอดี chat มีการพิมพ์เบิลคำบ่อย ทำให้เกิด บัก อย่างที่ว่า

**Comment by heytitle** [comment]
@bact ถ้าลงตัวที่พี่ทำใหม่จะแก้ได้ไหมน่ะ?

**Comment by wannaphongcom** [comment]
แก้ไขใน https://github.com/PyThaiNLP/pythainlp/commit/3921e66efaafd68079bb18ee77cb8fc64d6e5a13 แล้วครับ โดยลบ "ชิชิ" ออกจากพจนานุกรมครับ

**Comment by wannaphongcom** [comment]
ทดลองผ่าน `pip install https://github.com/PyThaiNLP/pythainlp/archive/dev.zip` ดูนะครับ

**Comment by bact** [comment]
> @bact ถ้าลงตัวที่พี่ทำใหม่จะแก้ได้ไหมน่ะ?

ได้และไม่ได้ lol

ถ้าใช้ตัวเลข `_TEXT_LIMIT` ตัดที่ 120 ตัวอักษรแบบปัจจุบัน จะวนลูปยาวนานอยู่ดี เพราะ ชิชิ-ชิ มันวนหนักมาก

แต่ถ้าลดตัวเลข _TEXT_LIMIT ลงมา ก็จะพอได้

แต่พอเจอแบบนี้แล้ว คิดว่าเดี๋ยวไปหาทางแก้ใน `_onecut()` เลยดีกว่า 
ให้มันเช็คว่า ถ้าของใน heap queue มันเยอะเกินจุดหนึ่ง แล้วให้มันพอ แนวๆ นี้

**Comment by bact** [comment]
ปัญหาเดียวกับบั๊ก #241

**Comment by bact** [comment]
ลองแก้ด้วย PR #333 คิดว่าน่าจะได้แล้วครับ ยังไงฝากทดสอบด้วยครับ 

`pip install --upgrade --pre pythainlp`

```python
from pythainlp import word_tokenize
from pythainlp.tokenize import dict_trie

text = "ชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิชิ"
word_tokenize(text, custom_dict=dict_trie(["ชิ", "ชิชิ"]))
```

**Comment by lolgolflol** [comment]
โอเคครับ เด๋วผมลองให้อีกรอบครับ

**Comment by bact** [comment]
เพิ่ง merge ไป 
ลองได้ด้วย `pip install --upgrade --pre pythainlp` เลยครับ
