### ISSUE TITLE
PyThaiNLP 2.2 change log

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#330]
**Schedule**
- First development release: 1 May 2020 - [2.2.0-dev0](https://github.com/PyThaiNLP/pythainlp/releases/tag/v2.2.0-dev0)
- Beta release: 15 June 2020 - [2.2.0-beta1](https://github.com/PyThaiNLP/pythainlp/releases/tag/v2.2.0-beta1)
- Production release: 24 June 2020 - [2.2.0](https://github.com/PyThaiNLP/pythainlp/releases/tag/v2.2.0)

See [2.2 Milestone](https://github.com/PyThaiNLP/pythainlp/milestone/12).

## Tokenization
- #333 Add graph size limit in **newmm**'s `_onecut()` to avoid long wait for ambiguous text (also back ported to [2.1.1](https://github.com/PyThaiNLP/pythainlp/releases/tag/2.1.1))
- #357 Fix **longest** engine, last character is now consumed -- thanks @ciaranbyrne for the report
- #337 #380 Add **CRFCut** sentence segmentation -- thanks @opalchonlapat for the improved model

## Transliteration
- #377 Add Thai Grapheme-to-Phoneme (Thai G2P) deep learning sequence-to-sequence model

## Normalization
- #372, #373, #374 Add more normalize functions, like remove zero-width characters, remove duplicate spaces, etc.

## Utilities
- #334 Add `thaiword_to_date()` and `thaiword_to_time()`
- #398 Fix `countthai()` to handle a case where the text has only numbers and symbols -- thanks @opalthailand for the report

## Command line
- #342 update command and sub-command syntax - see [command line docs](https://github.com/PyThaiNLP/pythainlp/blob/dev/docs/notes/command_line.rst)

## Deprecation and other API changes
- #376 Deprecation: Remove deprecated functions:
  - `thaicheck()` -- use `is_native_thai()` instead
  - `deletetone()` -- use `remove_tonemark()`
  - `dict_word_tokenize()` -- use `word_tokenize(custom_dict=)`
- #379, #381 Trie API change:
  - Deprecating `pythainlp.tokenize.Trie`, use `pythainlp.util.Trie` instead
  - Add `add()` to `Trie` class. Now can add more words after the instantiation of Trie object

## Dependencies
- #353 Remove `numpy` and `pandas` requirements from base install -- thanks @mmaybeno and @PNNutkung for the report
- #400 Remove `nltk` requirements from base install. WordNet API needs NLTK, to use it `pip install pythainlp[wordnet]`
- #404, #407 Remove `sklearn-crfsuite` requirements. Port Thai NER from `sklearn-crfsuite` to `python-crfsuite`.
- #405 Remove `dill` requirements
- #406 Remove `tqdm` requirements. tqdm will be use to show progress bar when found. If not found, use a fallback progress report

## Others
- #378, #388, #394 Code improvement: Move non-init code out of `__init__.py` files, etc.
- #396, #438 Refactor `NorvigSpellChecker` class, add more type supports for `custom_dict` in the constructor
- #401 Remove dependency: Unigram POS tagger no longer need `NLTK` module
- #414 Refactor get_corpus_path() and update its logic to guarantee that the corpus will be downloaded as intended
- #434 Add more words to `words_th.txt` (used in dictionary-based word segmentation)

**Comment by korntawat** [comment]
how I can install pythainlp 2.2 ?

**Comment by p16i** [comment]
Hi @korntawat, 

We can use this approach:
```
pip install --upgrade https://github.com/PyThaiNLP/pythainlp/archive/<BRANCH-NAME>
```
In this case, as those referred issues have been merged  to `dev` already. So, you can just do
```
pip install --upgrade https://github.com/PyThaiNLP/pythainlp/archive/dev
```
@bact @wannaphong please correct me if I'm wrong.

**Comment by wannaphong** [comment]
Tentative release date: 24 June 2020

**Comment by bact** [comment]
2.2.0 production release: 24 June 2020 https://github.com/PyThaiNLP/pythainlp/releases/tag/v2.2.0
