### ISSUE TITLE
CLI commands should be verbs/actions

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#342]
Current pythainlp commands are `['corpus', 'tokenization', 'soundex', 'tagging']`, which are
- not verbs
- not consistent with module names (`.corpus`, `.tokenize`, `.transliterate`, `.tag`)
(see: https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/cli/__init__.py )

Verb commands are more intuitive (and many time also shorter). 

Example of verb commands:
- git add
- git commit
- git push
- git pull

We should try to use verb commands when possible.
Work in progress in https://github.com/PyThaiNLP/pythainlp/tree/verb-commands 

## Todo:
- `thainlp data purge` to remove all downloaded datasets
- Add `benchmark` command: https://github.com/PyThaiNLP/pythainlp/blob/dev/bin/word-tokenization-benchmark
- Write testcases (maybe using subprocess)
- Update document at https://github.com/PyThaiNLP/pythainlp/blob/verb-commands/docs/notes/command_line.rst
- Record usage demo with https://asciinema.org

**Comment by bact** [comment]
DRAFT DESIGN for soundex
====

- `thainlp soundex -h` - help
- `thainlp soundex TEXT` - get soundex of TEXT, using default algorithm (udom83)
- `thainlp soundex -a ALGO TEXT` - get soundex of TEXT, using ALGO algorithm

**Comment by bact** [comment]
DRAFT DESIGN for data (formerly corpus)
====

- `thainlp data catalog` - print dataset/corpus available for download (download the list from internet)
  - `thainlp data ls` ? show dataset downloaded/available locally? **NOT IMPLEMENTED YET**
- `thainlp data info DATASET_NAME` - show information about DATASET
- `thainlp data get DATASET_NAME` - download DATASET
- `thainlp data rm DATASET_NAME` - remove DATASET
  - `thainlp data del` ?
- `thainlp data path` - print path for local dataset

**Comment by bact** [comment]
DRAFT DESIGN for tokenize
====
(NOT YET IMPLEMENTED, comments are very welcome)

- `thainlp tokenize TEXT` - tokenize TEXT at word level (default)
- `thainlp tokenize -kw TEXT` - tokenize TEXT at word level and keep whitespaces
- `thainlp tokenize -sub -word -sent TEXT` - tokenize TEXT at subword, word, and sentence levels
  - should be very straightforward to implement, but the issue is about the output representation like which character to use for separator of each level?
- `thainlp tokenize -worda ALGO -s : TEXT` - tokenize TEXT at word level using ALGO as algorithm, and using : as seperator
  - `-word` argument is assumed if `-worda` exists
- `thainlp tokenize --infile INPUT_FILENAME` - tokenize text from INPUT_FILE and print output to stdout
- `thainlp tokenize -i INPUT_FILE -o OUTPUT_FILE`

**Comment by bact** [comment]
DRAFT DESIGN for tag
====
(NOT YET IMPLEMENTED, comments are very welcome)

- `thainlp tag -pos TEXT`
- `thainlp tag -pos -ne TEXT`
- `thainlp tag -pos --infile INPUT_FILE --outfile OUTPUT_FILE`

IMPLEMENTED
====

- `thainlp tag pos -s . การ.เดินทาง.ไกล`
```
การ / FIXN
เดินทาง / VACT
ไกล / ADVN
```

**Comment by p16i** [comment]
We also have a benchmark command here:
https://github.com/PyThaiNLP/pythainlp/blob/dev/bin/word-tokenization-benchmark.

For `data` command, we might also have `purge` to remove all downloaded datasets.

**Comment by p16i** [comment]
One idea. We might use https://asciinema.org to advertise + show how to leverage this functionality.

**Comment by p16i** [comment]
I guess we can close this issue now?

**Comment by bact** [comment]
I think we've implemented most of the stuffs we can do for now. Let's file another issue for any enhancement.
