### ISSUE TITLE
[DEP] NumPy required in base install

### ISSUE THREAD

**Issue by mmaybeno** [PyThaiNLP/pythainlp#353]
**Describe the bug**
The base installation requires numpy. Specifically importing the main package calls `__init__.py` which imports `benchmarks` which imports `numpy`. This was noticed in a downstream package that has `PyThaiNLP` as a requirement.

**To Reproduce**
```
# Install with no extras
pip install pythainlp

>>> python
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythainlp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maybeno/workspace/Envs/newspaper-nvz7rtlC/lib/python3.7/site-packages/pythainlp/__init__.py", line 26, in <module>
    from pythainlp.benchmarks import benchmark
  File "/Users/maybeno/workspace/Envs/newspaper-nvz7rtlC/lib/python3.7/site-packages/pythainlp/benchmarks/__init__.py", line 1, in <module>
    from .word_tokenization import benchmark
  File "/Users/maybeno/workspace/Envs/newspaper-nvz7rtlC/lib/python3.7/site-packages/pythainlp/benchmarks/word_tokenization.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Expected behavior**
Run `import pythainlp` without error.

**Source Code**
https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/__init__.py#L26

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python Version 3.7
 - Version 2.1.3

**Additional context**

**Comment by wannaphong** [comment]
Thanks for your report. We will fix the issue in the next release.

**Comment by bact** [comment]
Or I think we can consider as well to remove `from pythainlp.benchmarks import benchmark` from `pythainlp/__init__.py`.

When install with `pip install pythainlp[benchmarks]`, `["numpy>=1.16", "pandas>=0.24"]` will be auotmatically installed.

**Comment by mmaybeno** [comment]
Ya I think having a the default package without numpy dependencies would be ideal. Numpy is great but kind of overkill if you're not using the benchmarks. Some added messaging if you try to import benchmark without numpy would be great. Thanks again!

**Comment by bact** [comment]
Thank you. Good idea for the message. Will try to do that.
I think we can use `ModuleNotFoundError` here.

**Comment by PNNutkung** [comment]
There is another problem.

The base installation requires `pandas`. Specifically importing the main package calls __init__.py which imports benchmarks which `import pandas as pd`. This was noticed in a downstream package that has PyThaiNLP as a requirement.  

```
ModuleNotFoundError: No module named 'pandas'
```

**Comment by bact** [comment]
> The base installation requires `pandas`. Specifically importing the main package calls **init**.py which imports benchmarks which `import pandas as pd`. This was noticed in a downstream package that has PyThaiNLP as a requirement.
> 
> ```
> ModuleNotFoundError: No module named 'pandas'
> ```

Thanks. Do you mean this file? https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/__init__.py If that the case, the `from pythainlp.benchmarks import benchmark` has been removed.

**Comment by PNNutkung** [comment]
> > The base installation requires `pandas`. Specifically importing the main package calls **init**.py which imports benchmarks which `import pandas as pd`. This was noticed in a downstream package that has PyThaiNLP as a requirement.
> > ```
> > ModuleNotFoundError: No module named 'pandas'
> > ```
> 
> Thanks. Do you mean this file? https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/__init__.py If that the case, the `from pythainlp.benchmarks import benchmark` has been removed.

Yes, it is. Did it release on PyPI?

**Comment by bact** [comment]
> > Thanks. Do you mean this file? https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/__init__.py If that the case, the `from pythainlp.benchmarks import benchmark` has been removed.
> 
> Yes, it is. Did it release on PyPI?

Not yet. It was fixed in `dev` branch, so you can try
`pip install https://github.com/PyThaiNLP/pythainlp/archive/dev.zip`

For PyPI,
We hope we can release it to 2.1 together with another fix soon.
The PR is here: https://github.com/PyThaiNLP/pythainlp/pull/360

**Comment by bact** [comment]
Version 2.1.4, with the fix, is now on PyPI.
Thanks for reporting the issue.
