### ISSUE TITLE
'NoneType' object has no attribute 'tag'

### ISSUE THREAD

**Issue by jallynme** [PyThaiNLP/pythainlp#364]
I used "get_ner" method seems like it's not working

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-9faa90abb220> in <module>
      1 from pythainlp.tag.named_entity import ThaiNameTagger
      2 ner = ThaiNameTagger()
----> 3 ner.get_ner("วันที่ 15 ก.ย. 61 ทดสอบระบบเวลา 14:49 น.")

~/anaconda3/lib/python3.7/site-packages/pythainlp/tag/named_entity.py in get_ner(self, text, pos)
    123             ('ก.ย.', 'NOUN', 'I-DATE'), (' ', 'PUNCT', 'I-DATE'),
    124             ('61', 'NUM', 'I-DATE'), (' ', 'PUNCT', 'O'),
--> 125             ('ทดสอบ', 'VERB', 'O'), ('ระบบ', 'NOUN', 'O'),
    126             ('เวลา', 'NOUN', 'O'), (' ', 'PUNCT', 'O'),
    127             ('14', 'NOUN', 'B-TIME'), (':', 'PUNCT', 'I-TIME'),

~/anaconda3/lib/python3.7/site-packages/sklearn_crfsuite/estimator.py in predict_single(self, xseq)
    365 
    366         """
--> 367         return self.tagger_.tag(xseq)
    368 
    369     def predict_marginals(self, X):

AttributeError: 'NoneType' object has no attribute 'tag'`

**Comment by p16i** [comment]
hi, thanks for reporting the issue. 

Could you please provide us the version of your pythainlp?

The latest version seems working fine with your code. Please see https://colab.research.google.com/drive/1NM-JBdVWrGr8jRnP77lwaGORISYmo6MD#scrollTo=yIK5xg9E2stY.


Maybe upgrading to the latest version might solve the problem?

**Comment by jallynme** [comment]
@heytitle  okay  thank you krub maybe I messed up with pythainlp and python 3.7
