### ISSUE TITLE
Can i find Thai consonant in pythainlp ?

### ISSUE THREAD

**Issue by punnoket** [PyThaiNLP/pythainlp#370]
Such as input "ความ" and then return "ค"

**Comment by cstorm125** [comment]
Do you mean only the first consonant of the syllable or any consonant? Which one do you want?
1. "ผู้นำโง่เราจะตายกันหมด" -> "ผนงรจตกม"
2. "ผู้นำโง่เราจะตายกันหมด" -> "ผนงรจตยกนหมด"

**Comment by punnoket** [comment]
> Do you mean only the first consonant of the syllable or any consonant? Which one do you want?
> 
> 1. "ผู้นำโง่เราจะตายกันหมด" -> "ผนงรจตกม"
> 2. "ผู้นำโง่เราจะตายกันหมด" -> "ผนงรจตยกนหมด"

I mean choice no.1 
haha I like your example it is fits the situation now. But i don't expected the result is exactly 100 percent na.

**Comment by cstorm125** [comment]
You can apply our `syllable_tokenize` function for this task:

```
from pythainlp.tokenize import syllable_tokenize
import re

txt = 'ผู้นำโง่เราจะตายกันหมด'
pattern = r'[ก-ฮ]'
''.join([re.findall(pattern,i)[0] for i in syllable_tokenize(txt)])
```

Although this won't solve something like `ห` appearing for `หมด` instead of `ม` yet.

**Comment by punnoket** [comment]
> You can apply our `syllable_tokenize` function for this task:
> 
> ```
> from pythainlp.tokenize import syllable_tokenize
> import re
> 
> txt = 'ผู้นำโง่เราจะตายกันหมด'
> pattern = r'[ก-ฮ]'
> ''.join([re.findall(pattern,i)[0] for i in syllable_tokenize(txt)])
> ```
> 
> Although this won't solve something like `ห` appearing for `หมด` instead of `ม` yet.

It's simple way!
Big thanks for your response :))

**Comment by cstorm125** [comment]
A better version that solves the issue I mentioned above

```
from pythainlp.tokenize import syllable_tokenize
from pythainlp.transliterate import royin
from pythainlp.transliterate import romanize
import re

def first_consonant(syl):
    first_roman = re.split('[aeiouy]',romanize(syl ,engine='royin'))[0]
    candidates = [k for k in royin._CONSONANTS if first_roman in royin._CONSONANTS[k]]
    if not candidates:
        candidates = [k for k in royin._CONSONANTS if first_roman[0] in royin._CONSONANTS[k]]
    first_thai = [c for c in candidates if c in re.findall(pattern,syl)][0]
    return first_thai

txt = 'ผู้นำโง่เราจะตายกันหมด'
pattern = r'[ก-ฮ]'
''.join([first_consonant(i) for i in syllable_tokenize(txt)])
```

A little hacky but it works in most cases. @korakot will probably know a better way and we'll include that in the library in next minor patch.
