### ISSUE TITLE
Add a more advanced normalize function

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#374]
Common normalize function that do more than reordering of Thai characters. Something that can be used quickly for matching, searching, sorting, and preparing data for classification tasks.

Some ideas;

- Remove non-visible characters, like zero-width chars #373 
- Remove unnecessary spaces
- Normalize repetitions
- Normalize "obvious" mistakes like
  - consonant + tonemark A + tonemark B <--- may be we can remove tonemark A

Note that for [Unicode normalization](https://en.wikipedia.org/wiki/Unicode_equivalence), Python does already have [`unicodedata.normalize()`](https://docs.python.org/3.8/library/unicodedata.html).

**Comment by p16i** [comment]
How about the case of `ำ`? I sometimes see PDF parsers return it as  `◌̊` and `า`.

**Comment by bact** [comment]
Current normalize() will group Nikhahit and Sara Aa together and emit Sara Am
