### ISSUE TITLE
Reduce Trie __init__ complexity

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#381]
Current initialize code of Trie has a deep Node creation loop.

Propose to move most of them to a separated method to reduce code complexity. Was partially done in 30b4ad1.

- `add()` method will be added to `Trie`, this can be used at the initialization stage and also after the instance has been created (so a trie can has more word added later)
- `__len__` method will also be added, so a trie can use `len()` function to find its length (based on the length of internal set of words)

**Comment by korakot** [comment]
I think the old one is easier to understand. A node can add just 1 char as a child. Adding a word is quite complex. But I don't mind if you prefer it.

You could make a separate add_word(...), instead using the same add(..) and change its semantic.

**Comment by bact** [comment]
I moved the add() from Node to Trie now, agreed that a word-level operation should be at Trie.

Also add len() to Trie.
