### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [PyThaiNLP/pythainlp#394]
**Describe the bug**

Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

**To Reproduce**

```
find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./pythainlp/benchmarks/word_tokenization.py:21: DeprecationWarning: invalid escape sequence \/
  TAG_RX = re.compile("<\/?[A-Z]+>")
./pythainlp/benchmarks/word_tokenization.py:125: DeprecationWarning: invalid escape sequence \s
  txt = re.sub("\s+", "", txt)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version : 3.8
 - Version : dev branch

**Comment by bact** [comment]
Thank you for the report. Will fix with PR #395
