### ISSUE TITLE
countthai not cover all cases

### ISSUE THREAD

**Issue by opalthailand** [PyThaiNLP/pythainlp#398]
**Describe the bug**
Input countthai('123') or countthai(' ') or countthai('1 2 3 4') create error instead of zero? 

**To Reproduce**
1. from pythainlp.util import countthai
2. input either '123' or ' '

**Expected behavior**
it should return zero?

**Comment by bact** [comment]
Thank you for reporting. 
Fixed. Will be available in the next release.
