### ISSUE TITLE
[DEP] Review for the removal of NLTK from requirements

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#400]
`nltk` module is now use in two places: 
1) WordNet (exact API copy of NLTK WordNet API) https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/corpus/wordnet.py 
2) <s>Unigram POS tagger https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tag/unigram.py</s>

## WordNet
I think we can drop the WordNet code in PyThaiNLP since it is the exact copy and users can use NLTK directly.

## Unigram POS Tagger

For this, I propose four options:

1) <s>Keep Unigram POS tagger and NLTK requirement as it is</s>
2) <s>Keep Unigram POS tagger as it is, but make it (and its NLTK requirement) optional (at the installation time)</s>
3) Re-implement Unigram POS tagger without the NLTK requirement
4) <s>Drop Unigram POS tagger entirely (if alternatives like Perceptron tagger or other new tagger is good enough)</s>

Maybe it is also time to consider seriously about effort on POS tagger.

Update: @wannaphong re-implement the tagger without NLTK at #401 (so we now go with option (3))

**Comment by p16i** [comment]
What does `DIET` mean?

**Comment by bact** [comment]
Non-standard term lol. Trying to come up with something about reducing the size of total installation, thus diet :p

**Comment by wannaphong** [comment]
This issue is #400. ⭐

**Comment by bact** [comment]
ส่วนโคลนของ WordNet นี่เอาไงดี
What do you think about the copy/wrap of WordNet?

**Comment by wannaphong** [comment]
> 
> 
> ส่วนโคลนของ WordNet นี่เอาไงดี
> What do you think about the copy/wrap of WordNet?

ประกาศเป็นโค้ดส่วนที่ถ้าต้องการใช้งานต้องโหลด nltk มาติดตั้งเอง เหมือน deepcut ดีไหมครับ

**Comment by bact** [comment]
ซึ่งตอน test ก็ยังต้อง test อยู่

ใจตอนนี้คือว่า ถ้ามันไม่ทำให้การ test นานขึ้น ก็น่าจะโอเค
แต่ถ้ามันจะทำให้ทดสอบนาน ก็รู้สึกว่าต้องมาชั่งน้ำหนัก

ทั้ง deepcut และ nltk ตอนติดตั้งเพื่อทดสอบจะมีการโหลดข้อมูลเพิ่มเติม นอกเหนือไปจาก dependency ซึ่งจะเสียเวลากับตรงนั้น เวลาที่ใช้รอเครือข่าย

หรือถ้ามี option ว่าให้ข้ามการทดสอบส่วนของ deepcut และ nltk ไป ในรอบ CI ปกติ (แต่สามารถบังคับให้ทดสอบได้ ก่อน release) ก็อาจจะช่วย
