### ISSUE TITLE
[DEP] Remove dill dependency

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#405]
Currently, `pythainlp.tag.perceptron` is the only submodule that uses `dill`.

`dill` is an extended version of `pickle`.

Looks like we currently use a very basic functionality of of serialization that the standard `pickle` may able to handle and there's no need for `dill`.

https://github.com/PyThaiNLP/pythainlp/blob/d2b67e00a85c42212b668cb535dcfaaf010663e9/pythainlp/tag/perceptron.py#L19

Propose to investigate more and see if we can move from `dill` to `pickle` and reduce the number of mandatory dependencies by one.

**Comment by wannaphong** [comment]
`NLTK` is used code from A Good Part-of-Speech Tagger in about 200 Lines of Python https://explosion.ai/blog/part-of-speech-pos-tagger-in-python

NLTK https://www.nltk.org/_modules/nltk/tag/perceptron.html
