### ISSUE TITLE
[DEP] Provide tqdm fallback for progress bar

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#406]
Current progress bar for download use `tqdm`.

https://github.com/PyThaiNLP/pythainlp/blob/c227976d02420b5f47382e12695f58831353e7be/pythainlp/corpus/core.py#L142

Propose to keep `tqdm` code but remove it from requirements.txt/setup.py.

The download code should check if `tqdm` exists (maybe with `ImportError`). Use it if exists, but use fallback if not.

**Comment by wannaphong** [comment]
👍
