### ISSUE TITLE
Test cases needed for document_vector() and merge_wgts() in ulmfit

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#426]
These two functions need at least one test case:

https://github.com/PyThaiNLP/pythainlp/blob/ee678690aeab5fe3944bbb99552fd50cb6ea2acc/pythainlp/ulmfit/core.py#L140 

https://github.com/PyThaiNLP/pythainlp/blob/ee678690aeab5fe3944bbb99552fd50cb6ea2acc/pythainlp/ulmfit/core.py#L198

**Comment by wannaphong** [comment]
Now, document_vector test case is in #579

**Comment by wannaphong** [comment]
Done. Add test_merge_wgts https://github.com/PyThaiNLP/pythainlp/commit/57f06e88966483818d9739cc0915cf56f79530fd
