### ISSUE TITLE
pythainlp.tokenize.sent_tokenize ?

### ISSUE THREAD

**Issue by wannaphongcom** [PyThaiNLP/pythainlp#43]
เราจะแบ่งประโยคในภาษาไทยอย่างไร ?

ในการแบ่งประโยคต้องอาศัยไวยากรณ์มาแบ่งด้วย

**Comment by wannaphongcom** [comment]
- [ ] เพิ่ม API เอาไว้ โดยแบ่งเบื้องต้นจากช่องว่าง เว้นวางของประโยค https://github.com/wannaphongcom/pythainlp/commit/96cc0aa9915d640da76d573b2517b7188c20644a

**Comment by bact** [comment]
ขออนุญาตปิด issue นี้ เพื่อไปรวมกับ issue #73 ครับ
