### ISSUE TITLE
Downloading the 2010BEST dataset for thai tokenization

### ISSUE THREAD

**Issue by mingruimingrui** [PyThaiNLP/pythainlp#430]
I'm not a Thai speaker and I couldn't find the 2010 BEST dataset for Thai tokenization benchmarking on the NECTEC site. Please help!

**Comment by wannaphong** [comment]
@mingruimingrui You can download BEST2010 dataset from [nectec.or.th/corpus](https://www.nectec.or.th/corpus/index.php?league=pm). (It doesn't have english languages but you can using google translate.)

**Comment by mingruimingrui** [comment]
Thanks! I got to the download page. But there's a problem. It appears that the download button isn't working.

![Screenshot 2020-06-07 at 4 41 54 PM](https://user-images.githubusercontent.com/18568364/83964189-cdab0f00-a8dd-11ea-9875-a928a076ae63.png)

**Comment by wannaphong** [comment]
> 
> 
> Thanks! I got to the download page. But there's a problem. It appears that the download button isn't working.
> 
> ![Screenshot 2020-06-07 at 4 41 54 PM](https://user-images.githubusercontent.com/18568364/83964189-cdab0f00-a8dd-11ea-9875-a928a076ae63.png)

You try using vpn from Thailand to download dataset.

**Comment by mingruimingrui** [comment]
I'll have to verify some time in the future. Unfortunately, I don't have a Thai VPN atm...

**Comment by wannaphong** [comment]
@mingruimingrui You can download BEST I from [https://gist.github.com/korakot/abf6c18c71cefe7b9107689dd904751f](https://gist.github.com/korakot/abf6c18c71cefe7b9107689dd904751f).
