### ISSUE TITLE
thai_strftime: %O modifier failed to convert year to Thai digit

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#436]
`O` (capital Oh) modifier in `thai_strftime()` failed to convert %y and %Y to alternative numeric symbols (Thai digit).

Code: `thai_strftime(datetime.datetime(1976, 10, 6, 1, 40), "%Od %Ob %Oy")`
Expect: '๐๖ ต.ค. ๒๕๑๙'
Actual: '๐๖ ต.ค. 2519'

**Comment by wannaphong** [comment]
I found same bug on Windows 10. Python 3.7.6

```
>>> from pythainlp.util import thai_strftime
>>> import datetime
>>> thai_strftime(datetime.datetime(1976, 10, 6, 1, 40), "%Od %Ob %Oy")
'๐๖ ต.ค. 19'
```
