### ISSUE TITLE
TorchText for Thai datasets

### ISSUE THREAD

**Issue by p16i** [PyThaiNLP/pythainlp#440]
I've recently found TorchText, a module that provides various utilities functions for NLP.  One thing that I like is the module provides a very convenient way to download datasets.  Please see: https://pytorch.org/text/datasets.html.

As we already have several datasets and rely on PyTorch, it might be a useful if we implement TorchText for those datasets. We might start with the following datasets:
- Wisesight
- TrueVoice
- BEST-2010

**Comment by wannaphong** [comment]
Now, I thinks we can load thai dataset from [Huggingface](https://huggingface.co/datasets?search=thai). I thinks we should close this issue.
