### ISSUE TITLE
More open license for words_th.txt?

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#444]
Currently words_th.txt's license is Creative Commons Attribution-ShareALike License.

Looks like it is not permissive enough. (see, for example: https://github.com/unicode-org/icu/pull/763 )

May be we can re-license or dual-license the dataset?

**Comment by wannaphong** [comment]
I think we can re-license directly with the work of PyThaiNLP project.

**Comment by bact** [comment]
Done. 
Please check
- https://github.com/PyThaiNLP/pythainlp/blob/dev/README.md and
- https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/corpus/corpus_license.md
