### ISSUE TITLE
spacymoji support

### ISSUE THREAD

**Issue by DamienJacquemart** [PyThaiNLP/pythainlp#465]
Hi guys,

Thank you for the work in Thai !

Running spacymoji in a Spacy pipeline gives the following error (below the code). Do you know how could we overcome the problem ?

---------------------------------------------------------------------------

> AttributeError                            Traceback (most recent call last)
> <ipython-input-6-e23cb5e52b25> in <module>
>       1 from spacymoji import Emoji
>       2 nlp = spacy.blank('th')
> ----> 3 emoji = Emoji(nlp)
>       4 nlp.add_pipe(emoji, first=True)
> 
> ~/Library/DataScienceStudio/dss_home/code-envs/python/nlp_SpaCy/lib/python3.6/site-packages/spacymoji/__init__.py in __init__(self, nlp, merge_spans, lookup, pattern_id, attrs, force_extension)
>      58         self.lookup = lookup
>      59         self.matcher = PhraseMatcher(nlp.vocab)
> ---> 60         emoji_patterns = list(nlp.tokenizer.pipe(EMOJI.keys()))
>      61         self.matcher.add(pattern_id, None, *emoji_patterns)
>      62         # Add attributes
> 
> AttributeError: 'ThaiTokenizer' object has no attribute 'pipe'

```
from spacymoji import Emoji
nlp = spacy.blank('th')
emoji = Emoji(nlp)
nlp.add_pipe(emoji, first=True)
```

**Comment by bact** [comment]
@DamienJacquemart can we know which spacymoji and pythainlp versions that you use?

**Comment by DamienJacquemart** [comment]
spacy==2.3.2
spacymoji==2.0.0
pythainlp==2.2.3

Thanks @bact !

**Comment by wannaphong** [comment]
spacymoji not update since 2019. :(

**Comment by polm** [comment]
A new version of spacymoji with support for spaCy v3 was released in April and I think it resolved this issue 😎

**Comment by wannaphong** [comment]
> 
> 
> A new version of spacymoji with support for spaCy v3 was released in April and I think it resolved this issue 😎

Thank you for update!
