### ISSUE TITLE
Add emoji util

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#469]
I discovered that there is still no tool to manage emoji with Thai language (convert emoji to text or convert text to emoji). I think we might add to `pythainlp.util`.

**Comment by bact** [comment]
Any example?

**Comment by wannaphong** [comment]
> 
> 
> Any example?

`จะมานั่งรถเมล์เหมือนผมก็ได้นะครับ ใกล้ชิดประชาชนดี 😀` -> `จะมานั่งรถเมล์เหมือนผมก็ได้นะครับ ใกล้ชิดประชาชนดี :ใบหน้ายิ้มยิงฟัน:`

**Comment by ppirch** [comment]
#512  I hope this will help.
