### ISSUE TITLE
Document: Model card

### ISSUE THREAD

**Issue by p16i** [PyThaiNLP/pythainlp#471]
I've recently encountered a paper advocating the idea of "Model Card". I personally like the idea. and because we have quite a lot of models in our repository, it's something we should consider. 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1214890/90931506-17939380-e3fd-11ea-9fa9-352ed889ca27.png">

See: https://arxiv.org/pdf/1810.03993.pdf

**Comment by bact** [comment]
Transparency and accountability!

**Comment by bact** [comment]
Example cards from Google
https://modelcards.withgoogle.com/

**Comment by wannaphong** [comment]
Model Card https://github.com/PyThaiNLP/pythainlp/wiki/Model-Cards
