### ISSUE TITLE
Minimize PyThaiNLP Dependencies

### ISSUE THREAD

**Issue by BLKSerene** [PyThaiNLP/pythainlp#506]
Hi, thanks for the awesome project which I've used in mine.

But the `tinydb` dependency is only used in `\corpus\core.py` and `corpus\__init__.py`, so is it possible to remove this small dependency? (The reduction in the number of small dependencies helps me to package my program.)

**Comment by wannaphong** [comment]
Hello. I think there is no need to remove `tinydb` because tinydb is small size and it write in pure Python.
