### ISSUE TITLE
the accuracy between "AttaCut" and "newmm".

### ISSUE THREAD

**Issue by charlesfufu** [PyThaiNLP/pythainlp#515]
Why the accuracy of "AttaCut" model more worse than "newmm" throgh PyThaiNLP in TNHC(Thai National Historical Corpus) dataset?
Is there any problem that needs my attention？
![image](https://user-images.githubusercontent.com/33311822/103404783-cefc9b80-4b8f-11eb-9423-26e2489952bd.png)
And, do you what's the meaning of "<s>、#、$" in TNHC dataset？

**Comment by wannaphong** [comment]
I close this issues because https://github.com/PyThaiNLP/attacut/issues/26 is close.
