### ISSUE TITLE
Error romanization module

### ISSUE THREAD

**Issue by wasdee** [PyThaiNLP/pythainlp#52]
romanization("ณ ระนอง",engine='royin')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-f54f9c0ff0a4> in <module>()
----> 1 romanization("ณ ระนอง",engine='royin')

C:\ProgramData\Anaconda3\lib\site-packages\pythainlp\romanization\__init__.py in romanization(data, engine)
     15         elif engine=='pyicu':
     16                 from .pyicu import romanization
---> 17         return romanization(data)

C:\ProgramData\Anaconda3\lib\site-packages\pythainlp\romanization\royin.py in romanization(text)
    542             '''
    543             d=re.search(consonants_thai,text,re.U)
--> 544             text=re.sub(d.group(0),consonants[d.group(0)][0],text,flags=re.U)
    545         listtext=list(text)
    546         #print(listtext,0)

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by wannaphongcom** [comment]
```python
>>> from pythainlp.romanization import romanization
>>> romanization("แมว",engine='royin')
'maeo'
>>> romanization("ณ ระนอง",engine='royin')
'n ranong'
```
fix in https://github.com/wannaphongcom/pythainlp/commit/1c42ee1b3650279544a1c0613c42555b411f2044
