### ISSUE TITLE
Error Install pythainlp

### ISSUE THREAD

**Issue by TouchTci** [PyThaiNLP/pythainlp#525]
install แล้ว error  แก้ยังงัยครับ

 pip install pythainlp
Collecting pythainlp
  Using cached pythainlp-2.2.6-py3-none-any.whl (10.6 MB)
Requirement already satisfied: requests>=2.22.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pythainlp) (2.25.1)
Requirement already satisfied: tinydb>=3.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pythainlp) (4.3.0)
Collecting python-crfsuite>=0.9.6
  Using cached python-crfsuite-0.9.7.tar.gz (432 kB)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (4.0.0)    
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (1.26.2)
Using legacy 'setup.py install' for python-crfsuite, since package 'wheel' is not installed.
Installing collected packages: python-crfsuite, pythainlp
    Running setup.py install for python-crfsuite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-bsjzh0zi\\python-crfsuite_af85b2296a104bdc9419cf5f5b2a5ea9\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-bsjzh0zi\\python-crfsuite_af85b2296a104bdc9419cf5f5b2a5ea9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-s6my3e27\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python39\Include\python-crfsuite'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-bsjzh0zi\python-crfsuite_af85b2296a104bdc9419cf5f5b2a5ea9\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-bsjzh0zi\\python-crfsuite_af85b2296a104bdc9419cf5f5b2a5ea9\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-bsjzh0zi\\python-crfsuite_af85b2296a104bdc9419cf5f5b2a5ea9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-s6my3e27\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python39\Include\python-crfsuite' Check the logs for full command output.

**Comment by wannaphong** [comment]
ลองลง `pip install wheel` ก่อนติดตั้ง pythainlp ครับ

**Comment by TouchTci** [comment]
ลองแล้ว ยังคงไมได้ครับ

Collecting pythainlp
  Using cached pythainlp-2.2.6-py3-none-any.whl (10.6 MB)
Requirement already satisfied: tinydb>=3.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pythainlp) (4.3.0)
Requirement already satisfied: requests>=2.22.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pythainlp) (2.25.1)
Collecting python-crfsuite>=0.9.6
  Using cached python-crfsuite-0.9.7.tar.gz (432 kB)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (1.26.2)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (4.0.0)    
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (2020.12.5)
Building wheels for collected packages: python-crfsuite
  Building wheel for python-crfsuite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5m6bch83\\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5m6bch83\\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-ncj8rlvc'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-5m6bch83\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for python-crfsuite
  Running setup.py clean for python-crfsuite
Failed to build python-crfsuite
Installing collected packages: python-crfsuite, pythainlp
    Running setup.py install for python-crfsuite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5m6bch83\\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5m6bch83\\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-gnh7ser9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python39\Include\python-crfsuite'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-5m6bch83\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5m6bch83\\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5m6bch83\\python-crfsuite_5eebe0749b55459a9deb727d2fa8f482\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-gnh7ser9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python39\Include\python-crfsuite' Check the logs for full command output.

**Comment by wannaphong** [comment]
เหมือนว่า python-crfsuite ยังไม่มี build สำหรับ Python 3.9 ใน windows ครับ https://pypi.org/project/python-crfsuite/#files

ลองตั้งค่า Build Tools ให้เรียบร้อยก่อนครับ

**Comment by TouchTci** [comment]
ได้แล้วครับ ขอบคุณมากๆครับ
