### ISSUE TITLE
Cannot install pythainlp in Mac

### ISSUE THREAD

**Issue by leky40** [PyThaiNLP/pythainlp#528]
<I cannot install pythainlp in Mac-->

## Description
I cannot install pythainlp in Mac. I am using MacBook Air (macOS Catalina, version 10.15.7; and python 2.7.16.

I got this error when I tried to install:

ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x5/hdhrw3tj30jf90d5djmy8mdr0000gn/T/pip-install-S6Bf1d/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/x5/hdhrw3tj30jf90d5djmy8mdr0000gn/T/pip-install-S6Bf1d/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/x5/hdhrw3tj30jf90d5djmy8mdr0000gn/T/pip-record-UWApXl/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Could you please suggest me what to do?

Thank you

**Comment by wannaphong** [comment]
Hello. We doesn't support python 2.7. PyThaiNLP support python 3.6+ or higher.

**Comment by leky40** [comment]
Thank you
