### ISSUE TITLE
word_tokenize กิน memory 

### ISSUE THREAD

**Issue by pp7sec** [PyThaiNLP/pythainlp#529]
ผมอยากสอบถามเรื่องตัดคำไทยหน่อยครับ

ผมใช้ word_tokenize ของ pythainlp ทำเป็น api แล้ว deploy ขึ้น heroku
แต่เกิดปัญหา mem เกิน `heroku[web.1]: Process running mem=540M(105.6%)`
พอเอา from pythainlp.tokenize import word_tokenize ออก ไม่เจอปัญหาเรื่อง mem เต็มแบบนี้มีทางแก้ไหมครับ

ขอบคุณมากครับ

**Comment by wannaphong** [comment]
ไม่ทราบว่า ใช้ engine ตัวไหนตัดคำใน `word_tokenize` ครับ
ถ้าไม่ได้ระบุ แสดงว่าใช้ newmm ให้ลองใช้ `word_tokenize(text, engine="newmm-safe")` ครับ

**Comment by pp7sec** [comment]
คือมันใช้ mem ตั้งแต่เริ่มทำงานเลยครับ

```python
from flask import Flask, request
from pythainlp.tokenize import word_tokenize

app = Flask(__name__)

@app.route('/')
def home():
    return 'Hello API'
```

`source=web.1 dyno=heroku.xxxxxxxxxxxxxxxx sample#memory_total=458.32MB sample#memory_rss=458.26MB sample#memory_cache=0.06MB sample#memory_swap=0.00MB sample#memory_pgpgin=130499pages sample#memory_pgpgout=13681pages sample#memory_quota=512.00MB
`
.
.
.

```python
from flask import Flask, request
#from pythainlp.tokenize import word_tokenize

app = Flask(__name__)

@app.route('/')
def home():
    return 'Hello API'
```
`source=web.1 dyno=heroku.xxxxxxxxxxxxxxxx sample#memory_total=44.59MB sample#memory_rss=42.36MB sample#memory_cache=2.23MB sample#memory_swap=0.00MB sample#memory_pgpgin=18050pages sample#memory_pgpgout=6635pages sample#memory_quota=512.00MB`

.
.
เห็นได้ชัดเลยว่าแค่มี `from pythainlp.tokenize import word_tokenize` mem ถูกใช้งานไป 400+MB แบบนี้พอมีทางแก้ไหมครับ 
ขอบคุณมากครับ

**Comment by wannaphong** [comment]
ไม่น่าจะกินถึง 400+MB นะครับ เพราะผม test เครื่องผมกับบน Colab

ก่อนรัน
```
              total        used        free      shared  buff/cache   available
Mem:          13021         529       10101           0        2389       12218
Swap:             0           0           0
```
หลังรัน
```
              total        used        free      shared  buff/cache   available
Mem:          13021         741        9856           0        2422       12022
Swap:             0           0           0
```

Colab: https://colab.research.google.com/drive/1BVooQf8-ALkvRqOa3fbh6lu7XjOtoiPM?usp=sharing

**Comment by pp7sec** [comment]
นั้นซิครับผมก็ลอง ใน colab แล้วก็ได้พอๆกับคุณ @wannaphong เลย 
แต่ทำไมใน heroku โดดไปได้ขนาดนั้น แล้วให้ mem มาแค่ 512 ผมเลยงงเลย

**Comment by wannaphong** [comment]
ลองปรับแต่งดูนะครับ https://devcenter.heroku.com/articles/optimizing-dyno-usage

**Comment by pp7sec** [comment]
ขอบคุณมากครับ
