### ISSUE TITLE
ERROR: Failed building wheel for obspy ตอน pip install บน Windows10 ค่ะ

### ISSUE THREAD

**Issue by saowapakbp** [PyThaiNLP/pythainlp#541]
พิมคำสั่ง pip install obspy แล้วขึ้นแบบนี้อ่ะค่ะ 
![Screenshot (5)](https://user-images.githubusercontent.com/60190957/109666014-5d49c980-7ba1-11eb-8588-02ae5f730f7b.png)
![Screenshot (6)](https://user-images.githubusercontent.com/60190957/109666069-676bc800-7ba1-11eb-961c-fa10c804cf19.png)

**Comment by wannaphong** [comment]
ทำตามนี้นะครับ https://www.youtube.com/watch?v=jZI-hex41WM
