### ISSUE TITLE
ERROR: Command errored out with exit status 1: 

### ISSUE THREAD

**Issue by Bunny1421** [PyThaiNLP/pythainlp#542]
ใช้ python 3.9 ค่ะ
ติดตั้งตัว PyICU-2.6-cp39-cp39-win_amd64.whl เรียบร้อยแล้ว 
![Capture](https://user-images.githubusercontent.com/68907141/111902425-f452c480-8a6f-11eb-88db-4ce1905d4428.PNG)

แล้วก็ pip install pythainlp ต่อ ค่ะ
![image](https://user-images.githubusercontent.com/68907141/111902534-82c74600-8a70-11eb-9fce-91895399543f.png)

![image](https://user-images.githubusercontent.com/68907141/111902540-878bfa00-8a70-11eb-9972-4e406ba2cfbc.png)

แล้วมันก็เป็นแบบนี้ค่ะ รบกวนช่วยด้วยนะคะ

**Comment by wannaphong** [comment]
เหมือนว่า python-crfsuite ยังไม่มี Build สำหรับ python 3.9 ครับ รุ่นล่าสุด สนับสนุนถึงแค่ python 3.8 ครับ

**Comment by Thiraphat-K** [comment]
> เหมือนว่า python-crfsuite ยังไม่มี Build สำหรับ python 3.9 ครับ รุ่นล่าสุด สนับสนุนถึงแค่ python 3.8 ครับ

แล้วต้องใช้ crfsuite vers. ไหนถึงจะรองรับกับ python 3.9 ครับ
![image](https://user-images.githubusercontent.com/69136273/126692391-5825066b-1045-483d-b139-bbf9c46e2d8f.png)
คือ ผมต้องเลือก vers. ล่าสุด(cp38)หรอครับ

**Comment by Thiraphat-K** [comment]
ERROR: python_crfsuite-0.9.7-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

ผมลองลง vers. ล่าสุดแล้วก็ขึ้นแบบนี้เลยครับ
