### ISSUE TITLE
ใช้ Bahttext หลังจาก build exe แล้ว error

### ISSUE THREAD

**Issue by TouchTci** [PyThaiNLP/pythainlp#554]
## Steps to reproduce

1.
2.
3.

```python
```

## Your environment
* PyThaiNLP version:
* Python version:
* Operating system and version (distro, 32/64-bit):
* More info (Docker, VM, etc.):

## Files

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> #

**Comment by wannaphong** [comment]
ช่วยบอกรายละเอียดเพิ่มเติมได้ไหมครับ

**Comment by TouchTci** [comment]
![S__1728518](https://user-images.githubusercontent.com/77578457/117907258-b0a66980-b300-11eb-894b-840f45ae6bfe.jpg)

หลังจาก compile เป็น EXE ด้วย pyinstaller รันโปรแกรมแล้ว error ตามภาพครับ

**Comment by bact** [comment]
ไม่พบแฟ้ม stopwords_th.txt

ตอนนี้ใช้ pythainlp รุ่นอะไรอยู่ครับ

**Comment by TouchTci** [comment]
pythainlp 2.3.1 ครับ

**Comment by bact** [comment]
ในข้อความแสดงความผิดพลาด แจ้งว่าจำเป็นต้องใช้แฟ้ม stopwords_th.txt 

ผมไม่แน่ใจว่า ตอน build เป็น exe ตัว build ได้รวมแฟ้มนี้ และแฟ้มอื่นๆ ที่จำเป็นต้องใช้ รวมเข้าไปใน exe หรือแฟ้มนี้อยู่ในเครื่องที่รันโปรแกรมไหมครับ

ปกติแฟ้มนี้จะถูกติดตั้ง เมื่อมีการลง PyThaiNLP ที่เป็น library ในเครื่อง ซึ่งควรจะอยู่ใน `lib/site-packages` แต่ในข้อความแสดงความผิดพลาดตามรูปที่แนบว่า แจ้งว่าตัวโปรแกรมไปค้นหาใน  `C:\Users\User\AppData\Local\Temp\_....` เข้าใจว่าอันนี้เป็นกลไกของตัว exe น่าจะต้องลองตรวจสอบทางนั้นดูครับ

**Comment by jirng1234** [comment]
@TouchTci มีวิธีแก้ไขไหมครับ ผมกำลังติดปัญหานี้อยู่เลย ขอบคุณครับ

**Comment by TouchTci** [comment]
ใช้ 

bahttext · PyPI ครับ
