### ISSUE TITLE
Misspellings and errors in dictionary for word tokenization

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#557]
## Description
Some errors are found in the tokenization dictionary like `คู่ทุกขู์คู่ยาก`.

This issue is open to get input on those.

## Your environment
* PyThaiNLP version: 2.3.1

## Files
- pythainlp/corpus/words_th.txt

**Comment by wannaphong** [comment]
Colab for test: https://colab.research.google.com/drive/1Nc0CwIlfuPazVYxYDCnOCFyWHIOfzs6A?usp=sharing

**Comment by bact** [comment]
อิทธิปาฎิหาริย์

**Comment by bact** [comment]
กรมอุตินิยมวิทยา
กรมอุติฯ

**Comment by bact** [comment]
ถือเน้อถือตัว

**Comment by bact** [comment]
อักษรศาตรดุษฎีบัณฑิต
อักษรศาตรบัณฑิต
อักษรศาตรมหาบัณฑิต
อักษรสาสตรบัณฑิต

**Comment by bact** [comment]
เลธิการสหประชาชาติ

**Comment by bact** [comment]
ศูนย์ปฎิบัติการ

**Comment by bact** [comment]
นักปฎิวัติ

**Comment by bact** [comment]
ปฎิกรปรมาณู
ปฎิกิริยา
ปฎิกูล
ปฎิคม
ปฎิชีวนะ
ปฎิทิน
ปฎิบัติ
ปฎิปักษ์
ปฎิรูป

**Comment by bact** [comment]
ระเบียบปฎิบัติ
ภาคปฎิบัติ

**Comment by bact** [comment]
เภสัชศาตรบัณฑิต
เภสัชศาตรมหาบัณฑิต
รองศาตราจารย์
รัฐประศาสนศาตรบัณฑิต
รัฐประศาสนศาตรมหาบัณฑิต
รัฐประสานสนศาตร์
รัฐศาตรดุษฎีบัณฑิต
รัฐศาตรบัณฑิต
รัฐศาตรมหาบัณฑิต
วิทยาศาตรดุษฎีบัณฑิต
วิทยาศาตรบัณฑิต
วิทยาศาตรมหาบัณฑิต
วิทยาศาตร์
วิทยาศาสตร์มหาบัณฑิต
วิศวกรรมศาตรดุษฎีบัณฑิต
วิศวกรรมศาตรบัณฑิต
วิศวกรรมศาตรมหาบัณฑิต
สถาปัตยกรรมศาตรบัณฑิต
สถาปัตยกรรมศาตรมหาบัณฑิต
สถาปัตยกรรมศาสตรดุษฎีบัณฑิต
ประวัติศาตร์
พยาบาลศาตรบัณฑิต
พยาบาลศาตรมหาบัณฑิต
แพทย์ศาสตร์
สัตวแพทย์ศาสตร์
คณะทันตแพทย์ศาสตร์
คนธรรมพศาสตร์
คุรุศาสตร์
คุรุศาสตรดุษฎีบัณฑิต
คุรุศาสตรบัณฑิต
คุรุศาสตรมหาบัณฑิต
ดุษฏี
สงวนลิขสิทธื์
ส่วนตั้วส่วนตัว
อุดมการทางการเมือง
ฮ่องกงฟู้ต
สมาชิกสภาผู้แทนราษฏร
สุราษฏร์ธานี
คณะราษฏร์
ราษฏร์
สภาผู้แทนราษฏร
มงกุฏวัฒนะ

**Comment by bact** [comment]
ปาฎิหารย์
ปาฎิหาริย์

**Comment by bact** [comment]
ติดยาเสพย์ติด
พระราชานุญาติ
เครื่องสำอางค์
ดับเครื่องยนตร์
เศรฐกิจพอเพียง

**Comment by bact** [comment]
กุฏุมพี
แก็งค์
แก๊งค์
แกงค์
แกลลอรี่
มิ้ตติ้ง
มีฝืมือ
เมตาบอลิสม
โลกาภิวัฒน์
วรางคนา
วันปิยะมหาราช
วิจารณญาน
สัญญานไฟ
วิญญาน
สหัชญาน
สนุ้กเกอร์
สวิสเซอร์แลนด์
สหรัฐอาหรับเอมิเรสต์

**Comment by bact** [comment]
อุตสาห์
ติดยาเสพย์ติด
พระราชานุญาติ
เครื่องสำอางค์
ดับเครื่องยนตร์
เศรฐกิจพอเพียง

**Comment by bact** [comment]
คร๊าบบบ
คร้าบบบบ
คาร์โบฮัยเดรท
คาร์โบโฮเดรต
ฉานนน
ซู๊ดดดดดดดดดดด
ธุรกิจบันฑิตย์
น้านนนนนน
เนติบัณฑิตสภา
เนเธอแลนด์
เนี๊ยบ
ปรากฎการณ์ธรรมชาติ
ปรากฎการณ์
ปรากฎ
ผ่านฟ้าภิภพลีลา
ฤิทธิ์เดช
วองชิงตัน ดี.ซี.
วัฎจักร
สถานบันการศึกษา
สมเด็จพระมหิตลาธิเบศร์ อดุลยเดชวิกรม พระบรมราชชนก
สมบูรณาญาสิทธิราช
สัมฤิทธิ์
สายไฟฟ้า.
สารทุกข์สุขดิบ
อิทธิฤิทธิ์

**Comment by bact** [comment]
โซเดียมไฮดรอกไซค์
เตอร์กเมนิสถาน
เวิร์ลด์
เวิร์ลไวด์เว็บ
ไวตามิลค์
สารขันฑ์

**Comment by bact** [comment]
นอรเวย์
ฮิลตันอะคาเดีย
ฮิวแมนแพบพิลโลมา
ฮิวแมนเพ็บพิโลม่าไทป์
ฮุนเซ็น
ซับพอร์ท
ซ็อกเกอร์
ซีคอนแสควร์
ซีไรท์
เซอร์ไพร์ส
ญีปุ่น

**Comment by bact** [comment]
คณสถาปัตยกรรมศาสตร์
โพธิ์สัมพันธ์
ไพโตสเตอรอยด์
มิดเดิ้ลสโบรห์
เมตาลอลิซึ่ม

**Comment by wannaphong** [comment]
I think we need to reopen a issues until It's fixed.

**Comment by bact** [comment]
แมนเชเตอร์ยูไนเต๊ด
องค์การส่งเสริมกิจการโคมนมแห่งประเทศไทย

**Comment by bact** [comment]
สมเด็จเจ้าฟ้ากรมพระยานริศรานุวัติวงศ์
ราชสิทธิธารามวรวิหาร
ไฮโดรคอรติโซน

**Comment by bact** [comment]
แก็สซิฟิเคชั่น
ไม่รู้จักเสือเอาเรือเข้ามาจอดไม่รู้จักมอดเอาไม้เข้
บำรุงระวิวรรณวิทยา

**Comment by bact** [comment]
ความจำเปง
ความปราณี
ไร้ความปราณี
