### ISSUE TITLE
Cannot install pythainlp

### ISSUE THREAD

**Issue by Zayajung** [PyThaiNLP/pythainlp#56]
ไม่สามารถ install pythainlp ได้ค่ะ
ใช้คำสั่ง pip install pythainlp

ขึ้น Error ว่า
 During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\sine\AppData\Local\Temp\pip-build-ffw6hyzb\pyicu\setup.py", line 33, in <module>
        ''')
    RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in D:\Users\sine\AppData\Local\Temp\pip-build-ffw6hyzb\pyicu\

ปล.โหลดPyICU-1.9.7-cp36-cp36m-win_amd64 ไม่ทราบว่าต้องไว้ตรงไหน

**Comment by wannaphongcom** [comment]
ตามนี้ครับ https://github.com/PyThaiNLP/pythainlp/blob/dev/docs/pythainlp-1-5-thai.md#คู่มือการใช้งาน-pythainlp-15

**Comment by Zayajung** [comment]
ลอง install แล้ว ขึ้นว่าแบบนี้ค่ะ
Requirement 'PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl' looks like a filename, but the file does not exist
PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl is not a valid wheel filename.
วางไฟล์ whl ไว้ที่ folder เดียวกับ coding แล้วค่ะ

ตอนนี้ใช้ เวอร์ชัน
The version of the notebook server is 5.0.0 and is running on:
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]

Current Kernel Information:

Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

**Comment by wannaphongcom** [comment]
ไม่ทราบว่าเก็บไฟล์ PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl ไว้ที่ไหนครับ

**Comment by Zayajung** [comment]
Folder Path : D:\Users\sine\Desktop\Python

เก็บไว้ที่เดียวกับ Coding ที่เขียนค่ะ

**Comment by wannaphongcom** [comment]
ลองโหลด PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl  ใหม่อีกรอบทับไฟล์เดิมครับ เพราะถ้าไฟล์ไม่สมบูรณ์ pip มันจะไม่ติดตั้งให้ครับ

**Comment by Zayajung** [comment]
ลองโหลดใหม่แล้ว ก็ยังไม่ได้ค่ะ ;____;

D:\Users\sine\Documents>pip install PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl
Requirement 'PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl' looks like a filename, but the file does not exist
PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl is not a valid wheel filename.

![image](https://user-images.githubusercontent.com/33190740/32141314-d81bf4d0-bcaf-11e7-8ffd-70755e13813e.png)

**Comment by wannaphongcom** [comment]
cd D:\Users\sine\Desktop\Python
pip install PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl

**Comment by Zayajung** [comment]
D:\Users\sine\Desktop\Python>pip install PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl
Requirement 'PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl' looks like a filename, but the file does not exist
PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl is not a valid wheel filename.

(;_______________;)

**Comment by wannaphongcom** [comment]
ลอง rename ไฟล์ PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl เป็นชื่ออื่นดูครับ

**Comment by Zayajung** [comment]
Success แล้วค่ะ 
ตอนแรกลอง rename แล้วไม่ได้ เลยลองเปลี่ยนกลับมาชื่อไฟล์เดิม ดันได้ค่ะ

ขอบคุณมากๆเลยค่ะ

**Comment by wannaphongcom** [comment]
@Zayajung ขอบคุณเช่นกันครับ ที่เลือกใช้ PyThaiNLP :) ในเวชั่นถัดไป PyThaiNLP 1.6 พวกเราจะแก้ไขให้ PyThaiNLP ติดตั้งให้ง่ายขึ้นกว่าเดิมครับ
