### ISSUE TITLE
Retrained Model for PyThaiNLP 2.4

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#581]
After #557 & #562, We needs to retrained all model in PyThaiNLP before we release PyThaiNLP 2.4 because dict & newmm has update.

**List model to retrained**

- [x] ThaiNER 1.5
- [x] CRFcut

**Comment by bact** [comment]
May related to #437 as well, for thai2fit.

**Comment by wannaphong** [comment]
Done ThaiNER 1.5 https://github.com/PyThaiNLP/pythainlp/commit/6027175fab6ba5a822b79c37e0190f832a37bef3

**Comment by wannaphong** [comment]
CRFcut: In progressing.
