### ISSUE TITLE
Deprecated some funtion in pythainlp.word_vector

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#586]
After #583, I think we would to deprecated some funtion in pythainlp.word_vector and we should move to `pythainlp.word_vector.WordVector`.

**List Deprecated funtion in pythainlp.word_vector**
- `pythainlp.word_vector.doesnt_match` move to `pythainlp.word_vector.WordVector.doesnt_match `
- `pythainlp.word_vector.get_model` move to `pythainlp.word_vector.WordVector.get_model`
- `pythainlp.word_vector.most_similar_cosmul` move to `pythainlp.word_vector.WordVector.most_similar_cosmul`
- `pythainlp.word_vector.sentence_vectorizer` move to `pythainlp.word_vector.WordVector.sentence_vectorizer `
- `pythainlp.word_vector.similarity` move to `pythainlp.word_vector.WordVector.similarity`

**Comment by p16i** [comment]
I have a quick question. It seems to me that `word_vector` and `WordVector` are semantically similar. Would you mind explaining what is the reason behind this depreciation (or reorganization)?

**Comment by wannaphong** [comment]
> I have a quick question. It seems to me that `word_vector` and `WordVector` are semantically similar. Would you mind explaining what is the reason behind this depreciation (or reorganization)?

OK. for `WordVector` class, It can have many word2vec model and it can add new word2vec model in the future. for `pythainlp.word_vector` old, It is thai2fit word2vec only.
