### ISSUE TITLE
Error: pip install pythainlp

### ISSUE THREAD

**Issue by pongsakorntochue** [PyThaiNLP/pythainlp#593]
ต้องแก้ไขอย่างไรครับ

pip install pythainlp
Collecting pythainlp
  Using cached pythainlp-2.3.1-py3-none-any.whl (11.0 MB)
Requirement already satisfied: tinydb>=3.0 in c:\program files\python39\lib\site-packages (from pythainlp) (4.5.1)
Collecting python-crfsuite>=0.9.6
  Using cached python-crfsuite-0.9.7.tar.gz (432 kB)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python39\lib\site-packages (from pythainlp) (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\program files\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (2.0.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python39\lib\site-packages (from requests>=2.22.0->pythainlp) (2021.5.30)
Building wheels for collected packages: python-crfsuite
  Building wheel for python-crfsuite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pongsakorn\\AppData\\Local\\Temp\\pip-install-5txieqgt\\python-crfsuite_b68f22dda75d457d85ab7e9620179784\\setup.py'"'"'; __file__='"'"'C:\\Users\\pongsakorn\\AppData\\Local\\Temp\\pip-install-5txieqgt\\python-crfsuite_b68f22dda75d457d85ab7e9620179784\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\pongsakorn\AppData\Local\Temp\pip-wheel-80ssds27'
       cwd: C:\Users\pongsakorn\AppData\Local\Temp\pip-install-5txieqgt\python-crfsuite_b68f22dda75d457d85ab7e9620179784\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for python-crfsuite
  Running setup.py clean for python-crfsuite
Failed to build python-crfsuite
Installing collected packages: python-crfsuite, pythainlp
    Running setup.py install for python-crfsuite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pongsakorn\\AppData\\Local\\Temp\\pip-install-5txieqgt\\python-crfsuite_b68f22dda75d457d85ab7e9620179784\\setup.py'"'"'; __file__='"'"'C:\\Users\\pongsakorn\\AppData\\Local\\Temp\\pip-install-5txieqgt\\python-crfsuite_b68f22dda75d457d85ab7e9620179784\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pongsakorn\AppData\Local\Temp\pip-record-i6a08nbf\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python39\Include\python-crfsuite'
         cwd: C:\Users\pongsakorn\AppData\Local\Temp\pip-install-5txieqgt\python-crfsuite_b68f22dda75d457d85ab7e9620179784\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pongsakorn\\AppData\\Local\\Temp\\pip-install-5txieqgt\\python-crfsuite_b68f22dda75d457d85ab7e9620179784\\setup.py'"'"'; __file__='"'"'C:\\Users\\pongsakorn\\AppData\\Local\\Temp\\pip-install-5txieqgt\\python-crfsuite_b68f22dda75d457d85ab7e9620179784\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pongsakorn\AppData\Local\Temp\pip-record-i6a08nbf\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python39\Include\python-crfsuite' Check the logs for full command output.

**Comment by wannaphong** [comment]
ขณะนี้ python-crfsuite ยังไม่มี build สำหรับ python 3.9 กับ windows ครับ แนะนำให้ติดตั้งตาม https://www.scivision.dev/python-windows-visual-c-14-required/ ก่อนติดตั้ง pythainlp ครับ

**Comment by pongsakorntochue** [comment]
ยอดเยี่ยมมากเลยครับ ได้แล้วครับ
ขอบคุณมากครับ
