### ISSUE TITLE
Skip to PyThaiNLP 3.0

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#604]
Hello! After we were release PyThaiNLP 2.4.0-dev0. In Thai NLP group, We have feedback that advice release PyThaiNLP 3.0 instead of PyThaiNLP 2.4.

What are you thinking? @bact @heytitle @cstorm125 @korakot @Gorlph

**Comment by wannaphong** [comment]
post https://web.facebook.com/groups/thainlp/posts/1390690147979138

**Comment by p16i** [comment]
Skipping to v3.0 seems reasonable given the list of changes we have introduced in the main branch; I personally don't have any opposing opinion to stay at v2.4.x. Given several changes (in different components) have been introduced, we might also consider extending the pre-release testing to be longer.

For the future, we might have a road map indicating on which (major) features we would introduce in each release. (maybe we already have the roadmap and I'm not aware of).

**Comment by Gorlph** [comment]
I have read the changes. I don't know much about how advanced these new features are, but there is **a lot** of new features and a few of breaking changes. Most importantly, as Ekapol commented, the main tokenizer's behavior has already been changed.

So, I think skipping to v3.0 is reasonable.

**Comment by korakot** [comment]
If we want to skip to 3.0, I have a change to newmm I want to add.
Now, we use 1 trie for both searching for normal tokens and OOV words. I want to use 2 different tries. The OOV can use a smaller trie so it won't match too easily and split the OOV words.

**Comment by wannaphong** [comment]
OK. I think we may skip tp PyThaiNLP 3.0 and we want to write the roadmap for PyThaiNLP 3.0.

**Comment by wannaphong** [comment]
The roadmap of PyThaiNLP 3.0 #605
