### ISSUE TITLE
Add dependency parsing to PyThaiNLP

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#606]
After NECTEC released Blackboard Treebank, We want to add dependency parsing from Blackboard Treebank to PyThaiNLP 3.0.

Facebook: https://web.facebook.com/dancearmy/posts/10158423653343284
bitbucket: https://bitbucket.org/kaamanita/blackboard-treebank/

**Comment by wannaphong** [comment]
@bact Can I use pickle for serializing function? I found my code's not working with json serialize.

**Comment by bact** [comment]
Pickle is fine, just be careful:
- if the data is downloaded from the network, check the signature before unpickle it
- if the data is from local, set a proper access permission to the file/folder

**Comment by wannaphong** [comment]
I moved it to future because I don't have free-time to do this issues. If you interest this, you can comment this issues and fork pythainlp to do it.
