### ISSUE TITLE
ผลลง pythainlp ไม่ได้ครับ แก้ไขยังไงดีครับ 

### ISSUE THREAD

**Issue by TeerawatTK** [PyThaiNLP/pythainlp#616]
Building wheels for collected packages: python-crfsuite
  Building wheel for python-crfsuite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ToPfrEeTK\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ToPfrEeTK\\AppData\\Local\\Temp\\pip-install-jz3byjfw\\python-crfsuite_88890a5e952347c5a1971d51155cf24c\\setup.py'"'"'; __file__='"'"'C:\\Users\\ToPfrEeTK\\AppData\\Local\\Temp\\pip-install-jz3byjfw\\python-crfsuite_88890a5e952347c5a1971d51155cf24c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ToPfrEeTK\AppData\Local\Temp\pip-wheel-0qjc6_2j'
       cwd: C:\Users\ToPfrEeTK\AppData\Local\Temp\pip-install-jz3byjfw\python-crfsuite_88890a5e952347c5a1971d51155cf24c\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
  copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for python-crfsuite
  Running setup.py clean for python-crfsuite
Failed to build python-crfsuite
Installing collected packages: python-crfsuite, pythainlp
    Running setup.py install for python-crfsuite ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ToPfrEeTK\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ToPfrEeTK\\AppData\\Local\\Temp\\pip-install-jz3byjfw\\python-crfsuite_88890a5e952347c5a1971d51155cf24c\\setup.py'"'"'; __file__='"'"'C:\\Users\\ToPfrEeTK\\AppData\\Local\\Temp\\pip-install-jz3byjfw\\python-crfsuite_88890a5e952347c5a1971d51155cf24c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ToPfrEeTK\AppData\Local\Temp\pip-record-nyb_l7s_\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\ToPfrEeTK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\python-crfsuite'
         cwd: C:\Users\ToPfrEeTK\AppData\Local\Temp\pip-install-jz3byjfw\python-crfsuite_88890a5e952347c5a1971d51155cf24c\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\_logparser.py -> build\lib.win-amd64-3.9\pycrfsuite
    copying pycrfsuite\__init__.py -> build\lib.win-amd64-3.9\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\ToPfrEeTK\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ToPfrEeTK\\AppData\\Local\\Temp\\pip-install-jz3byjfw\\python-crfsuite_88890a5e952347c5a1971d51155cf24c\\setup.py'"'"'; __file__='"'"'C:\\Users\\ToPfrEeTK\\AppData\\Local\\Temp\\pip-install-jz3byjfw\\python-crfsuite_88890a5e952347c5a1971d51155cf24c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ToPfrEeTK\AppData\Local\Temp\pip-record-nyb_l7s_\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\ToPfrEeTK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\python-crfsuite' Check the logs for full command output.

**Comment by wannaphong** [comment]
แนะนำให้ลง Microsoft C++ Build Tools ก่อนติดตั้งครับ https://www.youtube.com/watch?v=rcI1_e38BWs

**Comment by wannaphong** [comment]
หากยังพบปัญหาให้กด reopen นะครับ
