### ISSUE TITLE
`python-crfsuite` dependency fails to build under python 3.10

### ISSUE THREAD

**Issue by banagale** [PyThaiNLP/pythainlp#626]
This is a downstream issue. 

## Description

It appears that `python-crfsuite` is not building under python 3.10.  Discovered when trying to run 3.10 in `newspaper3k`. See [issue here](https://github.com/codelucas/newspaper/issues/920).

## Expected results
pythainlp should install via pip under python 3.10

## Current results
```
    Running setup.py install for python-crfsuite ... error
    ERROR: Command errored out with exit status 1:
     command: python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/51/z2bf1rq1007gxp1c2s6qvzym0000gn/T/pip-install-3gclwu1c/python-crfsuite_91f6baa39d2642cbbf813fb119fb497b/setup.py'"'"'; __file__='"'"'/private/var/folders/51/z2bf1rq1007gxp1c2s6qvzym0000gn/T/pip-install-3gclwu1c/python-crfsuite_91f6baa39d2642cbbf813fb119fb497b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/51/z2bf1rq1007gxp1c2s6qvzym0000gn/T/pip-record-yrta9d9z/install-record.txt --single-version-externally-managed --compile --install-headers .../.virtualenvs/xyz/python3.10/python-crfsuite
         cwd: /private/var/folders/51/z2bf1rq1007gxp1c2s6qvzym0000gn/T/pip-install-3gclwu1c/python-crfsuite_91f6baa39d2642cbbf813fb119fb497b/
```

## Your environment
* PyThaiNLP version:
* Python version: 3.10
* Operating system and version (distro, 32/64-bit):
* More info (Docker, VM, etc.):

## Possible solution
It looks like there is a PR for a workaround in `python-crfsuite` but it may not be a complete solution.

**Comment by wannaphong** [comment]
It is the bug of python-crfsuite. Now, python-crfsuite have this pull request. [Add Python 3.10 support #131](https://github.com/scrapinghub/python-crfsuite/pull/131)

**Comment by garfieldnate** [comment]
The linked PR only attempts to add Python 3.10 to CI (GitHub Action). No actual fix has been created yet.

**Comment by garfieldnate** [comment]
I've opened a PR in `python-crfsuite` which fixes the underlying problem. If anyone is having trouble building pythainlp, you can depend on my branch for now. I'm using Poetry to manage dependencies, so in my pyproject.toml dependencies section I have the lines below:

    # TODO: temporarily use forked version of python-crfsuite for Python 3.10 compatibility
    # (needed by pythainlp). See https://github.com/scrapinghub/python-crfsuite/pull/136
    python-crfsuite = { git = "https://github.com/garfieldnate/python-crfsuite.git", branch = "fix-python-3.10" }
    pythainlp = "^2.3.2"

**Comment by qathom** [comment]
Hello, I'm also getting this error when I'm running tests based on a Github Action - Running Python 3.8.12

```
 >   from pycrfsuite import Tagger as CRFTagger
E   ModuleNotFoundError: No module named 'pycrfsuite'

/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pythainlp/tag/thainer.py:10: ModuleNotFoundError
=========================== short test summary info ============================
```

**Comment by wannaphong** [comment]
> Hello, I'm also getting this error when I'm running tests based on a Github Action - Running Python 3.8.12
> 
> ```
>  >   from pycrfsuite import Tagger as CRFTagger
> E   ModuleNotFoundError: No module named 'pycrfsuite'
> 
> /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pythainlp/tag/thainer.py:10: ModuleNotFoundError
> =========================== short test summary info ============================
> ```

You can install `pip install python-crfsuite` or `pip install pythainlp[all]` to solve this error.

**Comment by qathom** [comment]
Hi @wannaphong, thanks a lot for your prompt reply and sorry for my late message.
I tried to install `pythainlp[all]` from requirements.txt but it didn't work, Nevertheless, adding `python-crfsuite` as a dependency fixed the issue!
Thanks again :-)

**Comment by luc-vocab** [comment]
hi, why not add pycrfsuite as a dependency in setup.py ?
see this code in `han_solo.py`
```
try:
    import pycrfsuite
except ImportError:
    raise ImportError("ImportError; Install pycrfsuite by pip install python-crfsuite")
```

**Comment by wannaphong** [comment]
> hi, why not add pycrfsuite as a dependency in setup.py ? see this code in `han_solo.py`
> 
> ```
> try:
>     import pycrfsuite
> except ImportError:
>     raise ImportError("ImportError; Install pycrfsuite by pip install python-crfsuite")
> ```

Thank you for report bug!
