### ISSUE TITLE
cannot import name 'dict_trie' from 'pythainlp.tokenize'

### ISSUE THREAD

**Issue by thetorque** [PyThaiNLP/pythainlp#627]
I'm trying to use tokenizer with custom dict and I'm following this tutorial

https://www.bualabs.com/archives/3740/python-word-tokenize-pythainlp-example-algorithm-deepcut-newmm-longest-python-pythainlp-ep-2/

However, when doing

```python
from pythainlp.tokenize import dict_trie
```
there is an error
```python
cannot import name 'dict_trie' from 'pythainlp.tokenize'
```
I'm using pythainlp 2.3.2

**Comment by wannaphong** [comment]
Since PyThaiNLP 2.2, We change `dict_trie` to `pythainlp.util.Trie`. You can read https://pythainlp.github.io/tutorials/notebooks/pythainlp_get_started.html#Tokenization-and-Segmentation.

**Comment by thetorque** [comment]
Understood. Thank you so much.
