### ISSUE TITLE
Tone detector for syllables - Determine Thai tone rule for syllable?

### ISSUE THREAD

**Issue by sferrka** [PyThaiNLP/pythainlp#63]
Hello! How could I determine tone rule for syllable? Thank you

**Comment by wannaphongcom** [comment]
@sferrka http://www.thai-language.com/ref/tone-rules

**Comment by sferrka** [comment]
@wannaphongcom Thank you, it is possible to do with your module?

**Comment by wannaphongcom** [comment]
@sferrka No. PyThaiNLP can't determine thai tone rule for syllable.

**Comment by wannaphongcom** [comment]
but, we have thai syllable tokenize.

**Comment by bact** [comment]
Determine a tone of a syllable from its consonants, vowels, and tone marks.
Interesting enhancement.

**Comment by alexgolod** [comment]
+1 haven't found any solution so far

**Comment by wannaphong** [comment]
Now, It is work-in-processing.

**Comment by korakot** [comment]
> Now, It is work-in-processing.

**Comment by korakot** [comment]
Maybe, we can use SpellWord's _find_tone() and _find_tone_info() here:

https://github.com/cakimpei/khanaa/blob/main/src/khanaa/thai_spelling.py#L310

**Comment by wannaphong** [comment]
> Maybe, we can use SpellWord's _find_tone() and _find_tone_info() here:
> 
> https://github.com/cakimpei/khanaa/blob/main/src/khanaa/thai_spelling.py#L310

It is word-level. I think it should have error from word-level and the code is hard to understand.

**Comment by wannaphong** [comment]
You can try the tone detector for Thai word/syllable by https://github.com/PyThaiNLP/pythainlp/pull/690.
