### ISSUE TITLE
Confusing warning message in pythainlp.tag.thainer

### ISSUE THREAD

**Issue by BLKSerene** [PyThaiNLP/pythainlp#644]
The warning issued in `pythainlp.tag.thainer` reads:

ThaiNameTagger class is change from
pythainlp.tag.named_entity.ThaiNameTagger
to
pythainlp.tag.thainer.ThaiNameTagger.
**This old class** will be deprecated in PyThaiNLP version 2.5.

As `ThaiNameTagger` has already been moved to `pythainlp.tag.thainer.ThaiNameTagger` and whenever the module is imported, `pytest` always prompt the warning, this is quite confusing.

## Expected results
The warning should be put in `pythainlp.tag.named_entity` or it should be removed from `pythainlp.tag.thainer`.

## Your environment
* PyThaiNLP version: 3.0.0
* Python version: 3.8.10 x64
* Operating system and version (distro, 32/64-bit): Windows 10 x64

**Comment by wannaphong** [comment]
I think that It should be removed from `pythainlp.tag.thainer`.
