### ISSUE TITLE
"newmm" tokenizes white spaces

### ISSUE THREAD

**Issue by YannDubs** [PyThaiNLP/pythainlp#65]
Hi,

First of all thanks for the great package 💯 

I just came across a very thing I think should be changed:

```python
from pythainlp import word_tokenize
print(word_tokenize('ข้อความภาษาไทย some english'))
# ['ข้อความ', 'ภาษาไทย', ' ', 'some', ' ', 'english']

print(word_tokenize('ข้อความภาษาไทย some english',engine='icu'))
# ['ข้อความ', 'ภาษา', 'ไทย', 'some', 'english']
```
The `icu` way of doing seems more logical. Of course I can simply use `" ".join(txt).split()` but I think not putting whitespaces in the list by default makes more sense.

Also a quick note about `newmm`, it seems way better than `icu` but in practice it cannot really be used because it is so slow. Because it's the new default I think it could be interesting to try making it faster, have you tested making all the loops faster with Cython ?

**Comment by cstorm125** [comment]
Hi YannDubs,

Agreed we can probably optimize more for performance. But for white spaces, I think preserving them makes more sense because in Thai, white spaces can have more nuances than just splitting words.

**Comment by YannDubs** [comment]
I'll have a look if I can get some quick performance improvements, because currently I have to use `icu` because of that. Just to know, is Cython something that you are willing to use or not really because of compilation ? I saw an open issue talking about a possible use of Jython.

Makes sense, it's strange that `icu` doesn't do that then!

**Comment by wannaphongcom** [comment]
@YannDubs Did you try out PyThaiNLP 1.6 ? https://github.com/PyThaiNLP/pythainlp/releases/tag/1.6a1

**Comment by wannaphongcom** [comment]
https://github.com/PyThaiNLP/pythainlp/commit/b7c624c9fa650cfc6f973634ec4f6c82407a0a3e

**Comment by YannDubs** [comment]
@wannaphongcom thanks for the quick answer (and nice library). Unfortunately I don't see any improvements in version 1.6.

Here is what I ran for a reproducibility:

``` python
# I simply copy pasted the whole thai wikipedia page of thai language : 
# https://th.wikipedia.org/wiki/%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2

txt = """...paste wiki..."""

print(len(txt.splitlines()))
# 539

### PYTHAINLP V1.5 - NEWMM ###
%%timeit
out1 = [pythainlp.tokenize.word_tokenize(line,engine="newmm") for line in txt.splitlines()]
# 36.6 s ± 192 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### PYTHAINLP V1.5 - ICU ###
%%timeit
out2 = [pythainlp.tokenize.word_tokenize(line,engine="icu") for line in txt.splitlines()]
# 67.3 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### PYTHAINLP V1.6 - NEWMM ###
%%timeit
out3 = [pythainlp.tokenize.word_tokenize(line,engine="newmm") for line in txt.splitlines()]
# 38.3 s ± 188 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Am I missing something ?

**Comment by YannDubs** [comment]
Ohh I just realized why after running 

```python
%lprun -m pythainlp.tokenize.newmm [word_tokenize(line,engine="newmm") for line in txt.splitlines()]
```
It just spend all the time reading the file ;)  I should have read the code more in detail ! Sorry if you talk about this in the docs.

Total time: 38.2493 s
File: /Users/dubois.yann/Desktop/mlu2/venv-test/lib/python3.6/site-packages/pythainlp/tokenize/newmm.py
Function: onecut at line 78

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    78                                           def onecut(text,data=['']):
    79       539        595.0      1.1      0.0    if(data!=['']):
    80                                                 trie = Trie(data)
    81                                             else:
    82       539   37896783.0  70309.4     99.1        trie = Trie(get_data())
    83       539       4375.0      8.1      0.0    words_at = defaultdict(list)  # main data structure
    84       539     147939.0    274.5      0.4    allow_pos = tcc_pos(text)     # ตำแหน่งที่ตัด ต้องตรงกับ tcc
    85                                             
    86       539        517.0      1.0      0.0    q = [0]       # min-heap queue
    87       539        375.0      0.7      0.0    last_p = 0    # last position for yield
    88     10014       8055.0      0.8      0.0    while q[0] < len(text):
    89      9475       7283.0      0.8      0.0        p = heappop(q)
    90                                           
    91     18952      41859.0      2.2      0.1        for w in trie.prefixes(text[p:]):
    92      9477       7141.0      0.8      0.0            p_ = p + len(w)
    93      9477       6094.0      0.6      0.0            if p_ in allow_pos:  # เลือกที่สอดคล้อง tcc
    94      7640       7916.0      1.0      0.0              words_at[p].append(w)
    95      7640       4900.0      0.6      0.0              if p_ not in q:
    96      6074       4787.0      0.8      0.0                heappush(q, p_)   
    97                                           
    98                                                 # กรณี length 1 คือ ไม่กำกวมแล้ว ส่งผลลัพธ์ก่อนนี้คืนได้
    99      9475       7325.0      0.8      0.0        if len(q)==1:
   100      3065       3040.0      1.0      0.0            paths = serialize(words_at, last_p, q[0])
   101      6195      54281.0      8.8      0.1            for w in min(paths, key=len):
   102      3130       1806.0      0.6      0.0              yield w
   103      3065       2079.0      0.7      0.0            last_p = q[0]
   104                                           
   105                                                 # กรณี length 0  คือ ไม่มีใน dict
   106      9475       6809.0      0.7      0.0        if len(q)==0:
   107      3401       6307.0      1.9      0.0            m = pat_eng.match(text[p:])
   108      3401       2270.0      0.7      0.0            if m: # อังกฤษ, เลข, ว่าง
   109      2285       2140.0      0.9      0.0                i = p + m.end()
   110                                                     else: # skip น้อยที่สุด ที่เป็นไปได้
   111      1700       2507.0      1.5      0.0                for i in range(p+1, len(text)):
   112      1528       1104.0      0.7      0.0                    if i in allow_pos:   # ใช้ tcc ด้วย
   113      1431       2996.0      2.1      0.0                        ww = trie.prefixes(text[i:])
   114      1431       2305.0      1.6      0.0                        m = pat_eng.match(text[i:])
   115      1431       1048.0      0.7      0.0                        if ww or m:
   116       944        635.0      0.7      0.0                            break
   117                                                         else:
   118       172        120.0      0.7      0.0                    i = len(text)
   119      3401       2706.0      0.8      0.0            w = text[p:i]
   120      3401       4349.0      1.3      0.0            words_at[p].append(w)
   121      3401       1938.0      0.6      0.0            yield w
   122      3401       2125.0      0.6      0.0            last_p = i
   123      3401       2763.0      0.8      0.0            heappush(q, i)

**Comment by wannaphongcom** [comment]
@YannDubs Can you help me improve code for more efficiency? We need contributor to PyThaiNLP. (https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md)

**Comment by YannDubs** [comment]
There are 2 ways I see we can change this:
1. Define `word_tokenize` as a callable object. Pros : nice and clean. Cons : you have to change the API for the end user.
2. Define a constant global variable `THAI_WORDS = Trie(get_data())` in `tokenize.newmm`. Pros : very easy, nearly no changes. Cons : not extremely pythonic + people who give their own data would still have to load the default one once (but I think it's neglectable)

I went with the second point as changing the API is probably not a good idea for other users.

 ```python
txt = """...paste wiki..."""

print(len(txt.splitlines()))
# 539

### Global Variable - NEWMM ###
%%timeit
out1 = [pythainlp.tokenize.word_tokenize(line,engine="newmm") for line in txt.splitlines()]
# 68 ms ± 374 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

So it's now the same speed as ICU when tokenizing lists (with only one line added) 👍 

Pull request : #66

PS: 

* I don't understand because your `tox.ini` only tests 2 different version of python 3 but not python 2.7 
* `test_segment_newmm` passes the tests in both versions but `test_segment_longest_matching` and `test_segment_mm` fail in python2.7 (before any changes from me, I didn't even change these).

**Comment by wannaphongcom** [comment]
@YannDubs  Thank you. 👍

**Comment by YannDubs** [comment]
@wannaphongcom BTW there's an other minor issue:

```python
%%time
word_tokenize('ส'*30,engine='newmm')
# Wall time: 3min 43s
# ['สสส', 'สสส', 'สสส', 'สสส', 'สสส', 'สสส', 'สสส', 'สสส', 'สสส', 'สสส']
```

I agree that having 30 times the same character is pretty rare but still it should not be `O(exp(n))`. The problem is in : 

```python
def serialize(words_at, p, p2):
    # find path ทั้งหมด แบบ depth first
    for w in words_at[p]:
        p_ = p + len(w)
        if p_ == p2:
            yield [w]
        elif p_ < p2:
            for path in serialize(words_at, p_, p2):
                yield [w] + path
```

I don't completely understand what you are checking but you must be missing a simple edge case to stop your depth first search. If it's really a simple edge case you might want to put it.

**Comment by korakot** [comment]
The code has this problem when there are multiple segmentation pathways.
Currently, it try to list all paths then find the shortest (=maximal
matching).
It does this stupidly by go depth-first (recursively) then rank them all.
I wrote a version that go breath-first and find just the shortest path,
also faster around 7% in my test case.
The code is somewhat longer, so for readibility sake, I choose the slower
version.
But for your ‘สสสสสสสสสสส’ case, it will surely be much much faster.

You can see the faster version here.
https://colab.research.google.com/drive/14Ibg-ngZXj15RKwjNwoZlOT32fQBOrBx
Look at onecut_bfs() which call bfs_paths()
It’s my first time doing code profiling, so I don’t have much experience in
optimizing for speed.

-- 
Korakot Chaovavanich

**Comment by YannDubs** [comment]
Ohh I see : makes a lot of sens now !
I agree with you that readability is important, and this case is very rare so shouldn't really be an issue. Personally I will simply continue using `word_tokenize(rm_triplicates(txt))` so that I don't have this issue. I might have a closer look to see if there's an edge case we can add to prune DFS.

Thanks for you work :) 

BTW I just did some evaluation and I get 1.5 % better F1 scores on some classification tasks (unfortunately cannot share the data 👎 ) using `ICU` than `newmm`. I don't understand anything to thai, and it might be only in my special case (+ having better results doesn't mean that the tokenization is more understandable by humans) but just wanted to share that.

**Comment by korakot** [comment]
My guess about accuracy is probably due to the word list used.
ICU will likely segment into shorter words than NEWMM. You cannot supply
your own word list.
NEWMM will try to choose the longest word from the word list, and there are
some long compound words there, so it may not fit the expectation.

My suggestion would be to look for those errors, and remove those long
words from the word list.

-- 
Korakot Chaovavanich

**Comment by wannaphongcom** [comment]
Now , PyICU has white spaces. in https://github.com/PyThaiNLP/pythainlp/commit/8d0081aac2f8da966ae11ccbfd42c13c527a519c I will to add api not putting whitespaces in word_tokenize.

**Comment by wannaphongcom** [comment]
fixed tokenizes white spaces https://github.com/PyThaiNLP/pythainlp/commit/57719e9f680728c96d3e0c0db7a36cc54af5fcdf
