### ISSUE TITLE
newmm has problem about " ์ "

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#662]
## Description

I try to tokenize text with `"ทดสอบตัดคำภาษาไทยจอก์น"`.

## Expected results
`['ทดสอบ', 'ตัด', 'คำ', 'ภาษาไทย', 'จอก์', 'น']`

## Current results
`['ทดสอบ', 'ตัด', 'คำ', 'ภาษาไทย', 'จอก', '์น']`

## Steps to reproduce

```python
from pythainlp.tokenize import word_tokenize
word_tokenize("ทดสอบตัดคำภาษาไทยจอก์น")
```

## Your environment
* PyThaiNLP version: 3.0.5
* Python version: 3.8
* Operating system and version (distro, 32/64-bit): Linux 64 bit
* More info (Docker, VM, etc.): Ubuntu 20.04 Docker

**Comment by wannaphong** [comment]
It's look like tcc. I think we can ignore this issues.

**Comment by wannaphong** [comment]
@bact How do you think about this issues?

I didn't found more error look like `"จอก์น"`. I think we can ignore this issues.

**Comment by bact** [comment]
hmmm.. intuitively, it should be at least 'ก์'

but currently PyThaiNLP's TCC regex doesn't cover that case

**Comment by wannaphong** [comment]
@bact  I found the cause. We forget `C์ ` rule from `<Cons> <TCC1> <Karan>` rule. The `<TCC1>` can be `NULL`. It mean ก์ should be 'ก์'.
