### ISSUE TITLE
"nercut" result not printed in a specific sentence

### ISSUE THREAD

**Issue by kmining** [PyThaiNLP/pythainlp#666]
## Description

I try to tokenize text with `ทุ๊กกโคนน` , `อือหือ`, `อย่าลืมอัพการ์ดนะจ๊ะ` using nercut tokenizer.

## Expected results

Something should be printed..

## Current results

Result not printed
![image](https://user-images.githubusercontent.com/58632771/168486898-0317e339-03f6-4d1c-a7f6-01454e2f6d4f.png)
![image](https://user-images.githubusercontent.com/58632771/168486934-8c5ab37d-2989-48a7-80ae-4ff84ae54dd7.png)

## Steps to reproduce

```python
import pythainlp
from pythainlp import word_tokenize
word_tokenize("ทุ๊กกโคนน", engine="nercut")
```

## Your environment
* PyThaiNLP version: 3.0.5
* Python version: 3.7.3
* Operating system and version (distro, 32/64-bit): 64
* More info (Docker, VM, etc.):

**Comment by wannaphong** [comment]
@kmining Thank you for reporting. I was fix this issue and I will release PyThaiNLP 3.0.6 to fix.

**Comment by kmining** [comment]
@wannaphong, Thanks for the quick response.
The error with no result has been resolved, but it seems that there is a duplicate of the extracted tokens.
In version 3.0.5, there were no duplicate tokens.

```python 
import pythainlp
from pythainlp import word_tokenize
word_tokenize("ทันแน่ๆ", engine="nercut")
word_tokenize("%1ครั้ง", engine="nercut")
```

![image](https://user-images.githubusercontent.com/58632771/168642379-d30925b8-5c0f-4c9e-867a-e46c96fbeb4d.png)
![image](https://user-images.githubusercontent.com/58632771/168643216-e35a09c3-0464-4e57-b98b-287069c37912.png)

**Comment by wannaphong** [comment]
> @wannaphong, Thanks for the quick response. The error with no result has been resolved, but it seems that there is a duplicate of the extracted tokens. In version 3.0.5, there were no duplicate tokens.
> 
> ```python
> import pythainlp
> from pythainlp import word_tokenize
> word_tokenize("ทันแน่ๆ", engine="nercut")
> word_tokenize("%1ครั้ง", engine="nercut")
> ```
> 
> ![image](https://user-images.githubusercontent.com/58632771/168642379-d30925b8-5c0f-4c9e-867a-e46c96fbeb4d.png) ![image](https://user-images.githubusercontent.com/58632771/168643216-e35a09c3-0464-4e57-b98b-287069c37912.png)

Thank you for report. I was rewrite code, so if it be done, I will release PyThaiNLP v3.0.8 to fix this issue.

**Comment by wannaphong** [comment]
@kmining It's done. Thank you for reporting.
