### ISSUE TITLE
Add Thai-English transliteration and more...

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#681]
Now, PyThaiNLP support only romanization by the Royal Thai General System of Transcription (RTGS) but we still doesn't support Thai-English/English-Thai transliteration.

- [x] Add Wunsen to PyThaiNLP for Japanese-to-thai, Korean-to-thai, and Vietnamese ([Wunsen GitHub](https://github.com/cakimpei/wunsen)) 
- [ ] Add Thai-English transliteration

**Comment by wannaphong** [comment]
Thai-English transliteration dictionary https://github.com/wannaphong/thai-english-transliteration-dictionary

**Comment by cakimpei** [comment]
FYI I've added Mandarin-to-thai and new system for Japanese-to-thai in Wunsen. Would you like a PR for this?

**Comment by wannaphong** [comment]
> FYI I've added Mandarin-to-thai and new system for Japanese-to-thai in Wunsen. Would you like a PR for this?

Yes, I want. Thank you!

**Comment by noppayut** [comment]
> Thai-English transliteration dictionary https://github.com/wannaphong/thai-english-transliteration-dictionary

Hi, can I take this issue?

**Comment by wannaphong** [comment]
> > Thai-English transliteration dictionary https://github.com/wannaphong/thai-english-transliteration-dictionary
> 
> Hi, can I take this issue?

Hello!

Yes, you can! 😄
