### ISSUE TITLE
[Feature Request] Thai word detokenizer

### ISSUE THREAD

**Issue by BLKSerene** [PyThaiNLP/pythainlp#696]
## Detailed description
Hi, are there any plans to add Thai word detokenizers (put list of tokens back to string)?

## Context
There are some cases where the users need to convert list of tokens back to string after applying some post-processing operations to the list of tokens returned by the tokenizer.

## Possible implementation
No idea.

## Your environment
* PyThaiNLP version: 3.0.8
* Python version: 3.8.10 x64
* Operating system and version (distro, 32/64-bit): Windows 10 x64

**Comment by wannaphong** [comment]
I don't sure about your feature. I think It just use `' '.join(the words list from the tokenizer)`.

**Comment by BLKSerene** [comment]
@wannaphong There are no spaces between Thai words, only between sentences, am I right?
I do not speak Thai, so I can't give examples here. But when Thai words are going to be put back into complete sentences, spaces need to be added only after the last word of each sentence (or clause/phrase?).

Tokenized **(type: list)**:
`['ภาษาไทย', 'หรือ', 'ภาษาไทย', 'กลาง', 'เป็น', 'ภาษา', 'ใน', 'กลุ่ม', 'ภาษา', 'ไท', 'ซึ่ง', 'เป็น', 'กลุ่มย่อย', 'ของ', 'ตระกูล', 'ภาษา', 'ข', 'ร้า', '-', 'ไท', 'และ', 'เป็น', 'ภาษาราชการ', 'และ', 'ภาษาประจำชาติ', 'ของ', 'ประเทศ', 'ไทย']`

Original sentence (expected output; **type: str**):
`'ภาษาไทย หรือ ภาษาไทยกลาง เป็นภาษาในกลุ่มภาษาไท ซึ่งเป็นกลุ่มย่อยของตระกูลภาษาขร้า-ไท และเป็นภาษาราชการ และภาษาประจำชาติของประเทศไทย'`

**Comment by wannaphong** [comment]
@BLKSerene OK. I will try to add this feature.

**Comment by wannaphong** [comment]
@BLKSerene You can try #697.

```python
from pythainlp.tokenize import word_detokenize,clause_tokenize
text_list=['ภาษาไทย', 'หรือ', 'ภาษาไทย', 'กลาง', 'เป็น', 'ภาษา', 'ใน', 'กลุ่ม', 'ภาษา', 'ไท', 'ซึ่ง', 'เป็น', 'กลุ่มย่อย', 'ของ', 'ตระกูล', 'ภาษา', 'ข', 'ร้า', '-', 'ไท', 'และ', 'เป็น', 'ภาษาราชการ', 'และ', 'ภาษาประจำชาติ', 'ของ', 'ประเทศ', 'ไทย']
print(word_detokenize(clause_tokenize(text_list)))
```

output: ภาษาไทยหรือภาษาไทยกลางเป็นภาษาในกลุ่มภาษาไท ซึ่งเป็นกลุ่มย่อยของตระกูลภาษาขร้า - ไท และเป็นภาษาราชการ และภาษาประจำชาติของประเทศไทย

**Comment by BLKSerene** [comment]
@wannaphong Is `clause_tokenize` required to get the correct detokenized string? If so, perhaps `clause_tokenize` could be called implicitly inside `word_detokenize`?

**Comment by wannaphong** [comment]
> @wannaphong Is `clause_tokenize` required to get the correct detokenized string? If so, perhaps `clause_tokenize` could be called implicitly inside `word_detokenize`?

I don't think like this because PyThaiNLP maybe has more `clause_tokenize` engines in the future that I need to write engine to this function if I add `clause_tokenize` inside `word_detokenize`, and I think some users want to use `sent_tokenize`, not `clause_tokenize`.

**Comment by BLKSerene** [comment]
Since I do not speak Thai, I'm a bit confused about some points.
The input of `word_detokenize` could be either list of tokens (strings) or list of sub-lists of strings (the output of `clause_tokenize`), am I right?

> I don't think like this because PyThaiNLP maybe has more `clause_tokenize` engines in the future that I need to write engine to this function if I add `clause_tokenize` inside `word_detokenize`, and I think some users want to use `sent_tokenize`, not `clause_tokenize`.

So what's the difference between applying `word_detokenize` directly to a list of strings, `word_detokenize(clause_tokenize(input_list))`, and `word_detokenize(sent_tokenize(input_list))`? And how do I know which one should I use?

Another more practical issue is that if I want to detokenize all lines in a text file, and apparently I have no idea about whether each line is a single clause (sentence segment) / multiple clauses / multiple sentences. So what's the best practice in these cases (detokenize multiple lists of Thai words in batch)?

**Comment by BLKSerene** [comment]
And, how are English words (and words in other Indo-European languages) handled in `word_detokenize` (spaces added between Thai and English words or not)?

**Comment by wannaphong** [comment]
> Since I do not speak Thai, I'm a bit confused about some points. The input of `word_detokenize` could be either list of tokens (strings) or list of sub-lists of strings (the output of `clause_tokenize`), am I right?

Yes

> So what's the difference between applying `word_detokenize` directly to a list of strings, `word_detokenize(clause_detokenize(input_list))`, and `word_detokenize(sent_tokenize(input_list))`? And how do I know which one should I use?

I advice you should try `sent_tokenize` and `clause_tokenize` and choise the tokenizer for your work. for `sent_tokenize`, It needs to input in string `sent_tokenize(str)` but `clause_detokenize` input is list of words.

sent_tokenize (CRFcut is default) is trained from Ted + Orchid + Fake review dataset and clause_tokenize is trained from LST20 corpus.

CRFcut: https://pythainlp.github.io/Model-Cards/CRFcut/
LST20 CLS: https://pythainlp.github.io/Model-Cards/LST20%20CLS/

If the text is general, I will use CRFcut because It is in the domain of CRFcut.

> 
> Another more practical issue is that if I want to detokenize all lines in a text file, and apparently I have no idea about whether each line is a single clause (sentence segment) / multiple clauses / multiple sentences. So what's the best practice in these cases (detokenize multiple lists of Thai words in batch)?

Yes, detokenize multiple lists of Thai words in batch is the best.

**Comment by wannaphong** [comment]
> And, how are English words (and words in other Indo-European languages) handled in `word_detokenize` (spaces added between Thai and English words or not)?

Yes, It is spaces added between Thai and English words.

**Comment by wannaphong** [comment]
This url is the Thai space suggest from The Royal Society of Thailand but The people doesn't use. http://legacy.orst.go.th/?page_id=629

**Comment by wannaphong** [comment]
The "small spaces", "Big spaces" and other rules are hard to write the coding because the document doesn't clear. I will add just few rule to the function.
