### ISSUE TITLE
My .exe program compiled from python code in which some modules from thaipynlp were imported cannot be started.

### ISSUE THREAD

**Issue by mon54126** [PyThaiNLP/pythainlp#698]
## Description
 After import some module from pythainlp into my python project, The EXE program compiled from the project cannot be started. Before those modules have been imported and used for some features, the EXE program can work with no problem. However, the program still worked well when it was python code.
(โปรแกรมยังทำงานได้ตามปกติตอนที่ยังเป็น code python แต่มีปัญหาพอ compile เป็น EXE)
Modules which were imported into my project are:
pythainlp.tokenize
pythainlp.corpus
pythainlp.tag
*The exe was compiled by using **pyinstaller**.
 Before the modules from pythainlp had been imported, every EXE compiled from my project usually started and worked properly. 

## Expected results
 The EXE should be able to start and work like it did before modules had been included.

## Current results
 The EXE is unable to start. [It looks like pyinstaller could not find some dependencies related to some of those module I imported from pythainlp....This is just my presume so I will attached warning text from pyinstaller.]

![image](https://user-images.githubusercontent.com/60461650/189051001-a5b856cd-b569-4010-adf1-3e84f7e8ff4d.png)

## Steps to reproduce

1. I think there is nothing wrong between the modules and my algorithm since the code work well but the issue might just occured during EXE compling.

2.
3.

``` 
# These below code are the import lines where pythainlp modules were included.
import pythainlp.tokenize as ptk
from pythainlp.corpus import thai_stopwords 
from pythainlp.tag import pos_tag
```

## Context
 I cannot use my code/program on other device in which python or pythainlp is not installed.
 

## Your environment
* PyThaiNLP version: 3.0.8
* Python version: 3.7.13
* Operating system and version (distro, 32/64-bit): 64-bit operating system, x64-based processor
* More info (Docker, VM, etc.):

## Files

[warn-test.txt](https://github.com/PyThaiNLP/pythainlp/files/9524175/warn-test.txt)

**Comment by BLKSerene** [comment]
This concerns with the usage of `PyInstaller`, not an issue concerning `PyThaiNLP`.
You may refer to: https://pyinstaller.org/en/stable/when-things-go-wrong.html#recipes-and-examples-for-specific-problems

Basically, you need to handle data files and hidden imports. `PyInstaller` ships with community-maintained hooks for some popular modules (`NumPy`, `SciPy`, `PyQt`, `NLTK`, etc.), but of course it won't work automatically with all 3rd-party libraries.

Or, you can check [my spec file](https://github.com/BLKSerene/Wordless/blob/main/utils/wl_packaging.spec).
