### ISSUE TITLE
Benchmark for tools in repository

### ISSUE THREAD

**Issue by petetanru** [PyThaiNLP/pythainlp#70]

**Comment by bact** [comment]
Related to issue #62 ?

**Comment by wannaphongcom** [comment]
Thai text classification benchmarks https://github.com/PyThaiNLP/classification-benchmarks by @cstorm125

**Comment by cstorm125** [comment]
A little bit too vague. Will create separate issues for each type of benchmark.

**Comment by bact** [comment]
For benchmark on word segmentation, see https://github.com/heytitle/thai-word-tokenisation-benchmark/
