### ISSUE TITLE
can not import process_thai function from pythainlp.ulmfit

### ISSUE THREAD

**Issue by DarinKumarnsit** [PyThaiNLP/pythainlp#700]
## Description

จะเทรน sentiment โดยใช้คำของตัวเองค่ะ จาก [sentiment_analysis.ipynb](https://pythainlp.github.io/tutorials/notebooks/sentiment_analysis.html#Wisesight-Sentiment-Analysis) รันบน Colab ใช้ได้ปกตินะคะ แต่พอรันบน Vscode ก็ขึ้น JSONDecodeError ตอน import fuction จาก pythainlp ค่ะ สามารถแก้ไขได้อย่างไรบ้างคะ ขอบคุณค่ะ

## Current results

![image](https://user-images.githubusercontent.com/58914019/189479417-b0e36ecd-3f7d-4e07-99ce-3fb26e31651e.png)

## Your environment
* PyThaiNLP version: 3.1.0.dev1
* Python version: 3.9.7 64bit
* Operating system and version (distro, 32/64-bit): Windows 10 x64

**Comment by wannaphong** [comment]
บนเครื่องได้ติดตั้ง PyThaiNLP รุ่นก่อนหน้าไหมครับ

**Comment by DarinKumarnsit** [comment]
ติดตั้งเป็น pythainlp 3.1.0.dev1 รุ่นเดียวเลยค่ะ

**Comment by wannaphong** [comment]
@DarinKumarnsit ลองลบแล้วติดตั้งตามนี้นะครับ ได้ผลอย่างไร รบกวนแจ้งด้วยนะครับ
```
pip uninstall --y pythainlp
pip install https://github.com/PyThaiNLP/pythainlp/archive/refs/heads/dev.zip
```

**Comment by DarinKumarnsit** [comment]
![image](https://user-images.githubusercontent.com/58914019/189494305-34e03100-9a35-4383-8ff4-4bb46aa6399f.png)

ลองลบแล้วติดตั้งใหม่แล้วได้ผลตามนี้ค่ะ

**Comment by wannaphong** [comment]
ลองติดตั้งตามข้างบนใหม่อีกรอบได้ไหมครับ @DarinKumarnsit

**Comment by DarinKumarnsit** [comment]
![image](https://user-images.githubusercontent.com/58914019/189877976-8e261a69-7633-4a63-bef9-a56ae7c249f9.png)
@wannaphong ลองติดตั้งใหม่อีกรอบแล้ว ได้ JSONDecodeError ค่ะ

**Comment by wannaphong** [comment]
@DarinKumarnsit แปลกนะครับ ลองตรวจสอบตามนี้ได้ไหมครับ
```
from pythainlp import __version__
print(__version__)
```

**Comment by DarinKumarnsit** [comment]
![image](https://user-images.githubusercontent.com/58914019/190217413-e6ef30d0-746a-4a58-98c4-9299aaa3244a.png)

@wannaphong ได้ค่ะ

**Comment by wannaphong** [comment]
@DarinKumarnsit  ลองลบแล้วติดตั้งใหม่ตามนี้อีกรอบนะครับ
```
pip uninstall --y pythainlp
pip install https://github.com/PyThaiNLP/pythainlp/archive/refs/heads/dev.zip
```

**Comment by DarinKumarnsit** [comment]
![image](https://user-images.githubusercontent.com/58914019/190336775-d4297233-39c5-48ae-ba17-c2c191636e2f.png)

@wannaphong ได้ผลเป็น JSONDecodeError ค่ะ

**Comment by wannaphong** [comment]
> ![image](https://user-images.githubusercontent.com/58914019/190336775-d4297233-39c5-48ae-ba17-c2c191636e2f.png)
> 
> @wannaphong ได้ผลเป็น JSONDecodeError ค่ะ

@DarinKumarnsit ลองรันโค้ดตามนี้นะครับ แล้วจากนั้นลองรันใหม่อีกรอบครับ

```python
from pythainlp.corpus import corpus_db_path
import os
os.remove(corpus_db_path())
```

**Comment by DarinKumarnsit** [comment]
![image](https://user-images.githubusercontent.com/58914019/190352088-5e227ee5-5141-450d-9f56-13ab6c47c48e.png)

อันนี้หลังจากรัน os.remove(corpus_db_path()) ค่ะ เลยลองเพิ่มไฟล์ [db.json](https://github.com/PyThaiNLP/pythainlp-corpus/blob/master/db.json)  เข้าไปดู  ก็ได้ผลเป็น KeyError: '_default' ค่ะ

![image](https://user-images.githubusercontent.com/58914019/190354191-51a7ea44-1aa8-4982-9615-0f79307ca09d.png)

**Comment by wannaphong** [comment]
@DarinKumarnsit ไม่ต้องเพิ่มไฟล์ db.json ครับ ให้รันโค้ดลบไฟล์ db.json จากนั้น restart kernel รันใหม่ตั้งแต่ต้นของโค้ด จะได้ครับ

```
from pythainlp.corpus import corpus_db_path
import os
os.remove(corpus_db_path())
```

**Comment by wannaphong** [comment]
ไฟล์ db.json ในเครื่องกับบน GitHub เป็นคนละตัวกันครับ

**Comment by DarinKumarnsit** [comment]
ได้แล้วค่ะ ขอบคุณมากๆค่ะ เป็นโปรเจ็คที่มีประโยชน์มาก เป็นกำลังใจให้นะคะ :)
