### ISSUE TITLE
Sphinx-style documentation for the entire library

### ISSUE THREAD

**Issue by petetanru** [PyThaiNLP/pythainlp#71]
To let [Sphinx](https://www.sphinx-doc.org/) build the docs, go inside `docs/` directory, and run:

```sh
./build_docs.sh
```

Ideally, the official docs should also be updated at https://www.thainlp.org/pythainlp/docs/2.0/

**Comment by bact** [comment]
Current documentation efforts:
- via examples in Jupyter notebooks: https://github.com/PyThaiNLP/pythainlp/tree/dev/notebooks 
- comments in the code
  - these comments, if put in proper format, can be use to generate API docs by Sphinx
    - see generated API docs: https://github.com/PyThaiNLP/pythainlp/tree/dev/docs
    - index file for API docs: https://github.com/PyThaiNLP/pythainlp/blob/dev/docs/index.rst
    - additional notes can be put here: https://github.com/PyThaiNLP/pythainlp/tree/dev/docs/notes

**Comment by artificiala** [comment]
06/06/2019 @artificiala started working on this issue. Changes are in the branch named issue71_add_documentation.

Todos

1. pythainlp.tokenize
- [x]  todo_tokenize_1: provide example for `sent_tokenize`
- [x]  todo_tokenize_2: provide example for `word_tokenize`
- [x]  todo_tokenize_3: provide example for `syllabus_tokenize`
- [x]  todo_tokenize_4: provide example for `subword_tokenize`
- [x]  todo_tokenize_5: briefly explain the algorithm of maximum matching (`newmm`)and cite the reference
- [x]  todo_tokenize_6: briefly explain the algorithm of `pyicu` and cite the reference
- [x]  todo_tokenize_7: briefly explain the algorithm of `etcc` and cite the reference
- [x]  todo_tokenize_8: briefly explain the algorithm of `deepcut` and cite the reference
- [x]  todo_tokenize_9: briefly explain the algorithm of `multicut` and cite the reference
- [x]  todo_tokenize_10: briefly explain the algorithm of longest matching (`longest`) and cite the reference
- [x]  todo_tokenize_11: Fix docstring formatt in [tcc.py](http://tcc.py) (see figure 1)

2. pythainlp.tag
- [x] todo_tag_1: provide lists of NER, POS tags
- [ ]  todo_tag_2: provide examples for  `pos_tag`
- [ ]  todo_tag_3: provide examples for  `pos_tag_sents`
- [ ]  todo_tag_4: provide examples for `pos_tag_provinces`
- [ ]  todo_tag_5: formatting docstring examples for `named_entity.ThaiNameTagger`
- [ ]  todo_tag_6: briefly explain `unigram` engine and cite the reference
- [ ]  todo_tag_7: briefly explain `perceptron` engine and cite the reference
- [ ]  todo_tag_8: briefly explain `artagger` engine and cite the reference
- [ ]  todo_tag_9: briefly explain `orchid` and cite the reference
- [ ]  todo_tag_10: briefly explain `orchid_ud` and cite the reference
- [ ]  todo_tag_11: briefly explain `pud` and cite the reference

3. pythainlp.word_vector
4. pythainlp.ulmfit
5. pythainlp.util
6. pythainlp.soundex
7. pythainlp.spell
8. pythainlp.transliterate
8. pythainlp.corpus
9. pythainlp.tools
10. pythainlp.summarize
11. pythainlp.spell

**Comment by wannaphongcom** [comment]
Done

**Comment by bact** [comment]
Close?

**Comment by artificiala** [comment]
Yes, this issue hould be closed.
