### ISSUE TITLE
PyThaiNLP join Hacktoberfest 2022!!!

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#717]
PyThaiNLP join Hacktoberfest 2022!!!

You can contribute to PyThaiNLP and get the Hacktoberfest 2022 reward.

If you don't found the topic that you want to do, you can create own issues and ask we before contribute in the Hacktoberfest 2022.

GitHub: https://github.com/PyThaiNLP/pythainlp
Hacktoberfest 2022: https://hacktoberfest.com/

**Thai**
PyThaiNLP เข้าร่วม Hacktoberfest 2022

ท่านใดต้องการรับรางวัล Hacktoberfest 2022 สามารถเข้ามามีส่วนร่วมในการโค้ด PyThaiNLP แล้วรับรางวัลของ Hacktoberfest 2022 ได้

หากท่านไม่พบหัวข้อที่สนใจ สามารถตั้ง issue ใหม่ที่ GitHub ของ PyThaiNLP เพื่อสอบถามก่อนลงมือโค้ดได้

GitHub: https://github.com/PyThaiNLP/pythainlp
Hacktoberfest 2022: https://hacktoberfest.com/

![ภาพ](https://user-images.githubusercontent.com/8536487/192863096-ab18b25b-9c29-499f-aa93-9ee4bd902b8a.png)

**Comment by Akshatmish** [comment]
please assign me this project

**Comment by wannaphong** [comment]
> please assign me this project

Hello! You can see https://github.com/PyThaiNLP/pythainlp/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest or create new issues if you don't see issues that interested.
