### ISSUE TITLE
Improve PyThaiNLP documentation

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#720]
Hello! PyThaiNLP needs to improve the documentation (e.g. fixed missing words, and other) and needs to improve the config documentation.

Now, PyThaiNLP documentation isn't fit the window. from https://pythainlp.github.io/dev-docs/
![ภาพ](https://user-images.githubusercontent.com/8536487/194747387-af6d5041-82af-466c-863d-345af3bcabc5.png)

You can fix the config css.

PyThaiNLP use this packages
- sphinx
- sphinx-rtd-theme

the config is in https://github.com/PyThaiNLP/pythainlp/tree/dev/docs

**Comment by LXZE** [comment]
Should it look like this?

![pythainlp github io_dev-docs_notes_command_line html](https://user-images.githubusercontent.com/3458544/197318660-c6df3438-455c-46a4-be12-1170aad92597.png)

If you are agree with this change, I will try to submit PR for that.

**Comment by wannaphong** [comment]
> Should it look like this?
> 
> ![pythainlp github io_dev-docs_notes_command_line html](https://user-images.githubusercontent.com/3458544/197318660-c6df3438-455c-46a4-be12-1170aad92597.png)
> 
> If you are agree with this change, I will try to submit PR for that.

Yes 👍
