### ISSUE TITLE
Sentence tokenizer for Thai - การตัดประโยคที่ไม่ได้คั่นด้วย whitespace

### ISSUE THREAD

**Issue by PhatSriwichai** [PyThaiNLP/pythainlp#73]
pythainlp รองรับการตัดประโยคที่ไม่ได้คั่นด้วย whitespace ไหมครับ
ตัวอย่าง
input: "อยากติดต่อสอบถามเรื่องเช่าพื้นที่ขายของของตลาดนัด" 
output: ["อยากติดต่อสอบถาม", "เรื่องเช่าพื้นที่ขายของของตลาดนัด"]

**Comment by wannaphongcom** [comment]
ตอนนี้ยังไม่รองรับครับ แต่มีแผนที่จะทำในอนาคตครับ ตอนนี้ยังต้องการ contributors ทำเรื่องนี้ครับ

**Comment by bact** [comment]
Same as an enhancement request in #43

**Comment by cstorm125** [comment]
#337 can do this but original example are not two sentences
