### ISSUE TITLE
sentence_vectorizer didn't work

### ISSUE THREAD

**Issue by Samach21** [PyThaiNLP/pythainlp#740]
## Description
ทำตาม documentation แล้ว รัน code example ไม่ได้

## Expected results
array([[-0.00421414, -0.08881307,  0.05081136, -0.05632929,
     -0.06607185, 0.03059357, -0.113882  , -0.00074836,  0.05035743,
     0.02914307,
     ...
    0.02893357,  0.11327957,  0.04562086, -0.05015393,  0.11641257,
    0.32304936, -0.05054322,  0.03639471, -0.06531371,  0.05048079]])

## Current results
AttributeError                            Traceback (most recent call last)
[<ipython-input-21-6dbb49067096>](https://localhost:8080/#) in <module>
      1 wv = WordVector()
      2 sentence = 'อ้วนเสี้ยวเข้ายึดแคว้นกิจิ๋ว ในปี พ.ศ. 735'
----> 3 wv.sentence_vectorizer(sentence, use_mean=True)

[/usr/local/lib/python3.7/dist-packages/pythainlp/word_vector/core.py](https://localhost:8080/#) in sentence_vectorizer(self, text, use_mean)
    307                 word = _TK_EOL
    308 
--> 309             if word in self.model.index_to_key:
    310                 vec += self.model.get_vector(word)
    311 

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'index_to_key'

## Steps to reproduce

1.
2.
3.

```python
from pythainlp.word_vector import WordVector

wv = WordVector()
sentence = 'อ้วนเสี้ยวเข้ายึดแคว้นกิจิ๋ว ในปี พ.ศ. 735'
wv.sentence_vectorizer(sentence, use_mean=True)
```

## Your environment
* PyThaiNLP version: 3.1.0
* Python version: 3.7
* Operating system and version (distro, 32/64-bit): Linux
* More info (Docker, VM, etc.):

**Comment by wannaphong** [comment]
สวัสดีครับ ต้องอัปเดต gensim เป็นรุ่น 4.0 ขึ้นไปสำหรับใช้งาน wav2vec ครับ

> pip install -U gensim
