### ISSUE TITLE
Add DeprecationWarning LST20 model to PyThaiNLP 3.1.1

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#749]
After we delete all LST20 model https://github.com/PyThaiNLP/pythainlp/pull/728 from dev, I think we should release PyThaiNLP 3.1.1 to add DeprecationWarning about LST20 model.

**Comment by noppayut** [comment]
Which action would you like when LST20-related options are chosen? Since they're gone we can either

1. Throw an error, ask users to choose a new option.
2. Fire a DeprecationWarning and use a default option for an API.

I personally prefer 2.

**Comment by wannaphong** [comment]
Yes, It will be 2 for PyThaiNLP 3.1.1 that it in 3.1 branch. Now, dev branch is 4.0.

**Comment by noppayut** [comment]
Cool. Let me work on this.

**Comment by wannaphong** [comment]
> Cool. Let me work on this.

Thank you! You can do this work. Don't forget doing in 3.1 branch.
