### ISSUE TITLE
syllable_tokenize cannot be imported

### ISSUE THREAD

**Issue by ghost** [PyThaiNLP/pythainlp#760]
### Description

When I imported syllable_tokenize from pythainlp.tokenize
ImportError will be raised.

### Expected results

syllable_tokenize can be imported normally.

### Current results

ImportError: cannot import name 'syllable_tokenize' from 'pythainlp.tokenize'

### Steps to reproduce

1. pip install pythainlp
2. pip install epitran
3. import syllable_tokenize from pythainlp.tokenize

```
from pythainlp.tokenize import syllable_tokenize

text = "อับดุลเลาะ อีซอมูซอ สมองบวมรุนแรง"

syllable_tokenize(text) 
```

### PyThaiNLP version

3.1.1

### Python version

3.7.15

### Operating system and version

Windows 11 Pro 21H2

**Comment by wannaphong** [comment]
@oat-tanutchakorn Hello! `syllable_tokenize` is deprecated. You can use `pythainlp.tokenize.subword_tokenize` instead.

PyThaiNLP 3.1 change log #643 

`pythainlp.tokenize.subword_tokenize` docs: https://pythainlp.github.io/docs/3.1/api/tokenize.html#pythainlp.tokenize.subword_tokenize

**Comment by wannaphong** [comment]
For syllable segmenter, you can use 3 engines
- dict - newmm word tokenizer with a syllable dictionary
- ssg - CRF syllable segmenter for Thai
- tltk - syllable tokenizer from tltk
