### ISSUE TITLE
bug: (potential) tokenization of ๆ

### ISSUE THREAD

**Issue by kepler** [PyThaiNLP/pythainlp#764]
### Description

When tokenizing a sentence with `ๆ`, I found an example where it doesn't become a token, but instead is joined with left and right symbols.

I can't figure out whether this is a linguistic feature or an actual bug. Could you please point out whether this is a proper word and so should be a proper token?

Here is the example:
```
>>> word_tokenize("ละตำแหน่งผู้อำนวยการโครงการกลุ่มบริษัทเมื่อเร็ว ๆ นี้ คุณ Mr. John ได้ตัดสินใจลาออกจาก The Company", keep_whitespace=False)
['ละ',
 'ตำแหน่ง',
 'ผู้อำนวยการ',
 'โครงการ',
 'กลุ่ม',
 'บริษัท',
 'เมื่อ',
 'เร็ว ๆ นี้',  # THIS TOKEN
 'คุณ',
 'Mr',
 '.',
 'John',
 'ได้',
 'ตัดสินใจ',
 'ลา',
 'ออกจาก',
 'The',
 'Company']
```

Here is a counter-example, where it works as (I) expected:
```
>>> word_tokenize("หลังจากที่ดำรงตำแหน่งกรรมการฝ่ายปฏิบัติการของกลุ่มบริษัท ๆ นี้ คุณ Mr. John ได้ตัดสินใจลาออกจาก The Company", keep_whitespace=False)
['หลังจากที่',
 'ดำรงตำแหน่ง',
 'กรรมการ',
 'ฝ่าย',
 'ปฏิบัติการ',
 'ของ',
 'กลุ่ม',
 'บริษัท',
 'ๆ',  # TOKEN BY ITSELF
 'นี้',
 'คุณ',
 'Mr',
 '.',
 'John',
 'ได้',
 'ตัดสินใจ',
 'ลา',
 'ออกจาก',
 'The',
 'Company']
```

### Expected results

I was expecting `ๆ` to always be a token by itself, but I lack knowledge in Thai to be sure about that.

### Current results

Instead it forms part of a token with inner whitespaces: ` เร็ว ๆ นี้`.

### Steps to reproduce

```
from pythainlp import word_tokenize


word_tokenize("ละตำแหน่งผู้อำนวยการโครงการกลุ่มบริษัทเมื่อเร็ว ๆ นี้ คุณ Mr. John ได้ตัดสินใจลาออกจาก The Company", keep_whitespace=False)
```

### PyThaiNLP version

3.1.1

### Python version

3.8.4

### Operating system and version

Ubuntu 22.04.1 LTS

**Comment by wannaphong** [comment]
Thank you for reporting. It's not a bug because "เมื่อเร็ว ๆ นี้" mean "recently". If you don't want the repetition character  (ๆ), you can use custom_dict.

```python
from pythainlp.util import Trie
from pythainlp.tokenize import word_tokenize
from pythainlp.corpus import thai_words # load the dict

list_thai_words_without_potential = [i for i in list(thai_words()) if "ๆ" not in i]
thai_words_without_potential = Trie(list_thai_words_without_potential)

# use custom_dict from https://pythainlp.github.io/docs/3.1/api/tokenize.html#pythainlp.tokenize.word_tokenize
word_tokenize("ละตำแหน่งผู้อำนวยการโครงการกลุ่มบริษัทเมื่อเร็ว ๆ นี้ คุณ Mr. John ได้ตัดสินใจลาออกจาก The Company", keep_whitespace=False, custom_dict=thai_words_without_potential)
# output: ['ละ', 'ตำแหน่ง', 'ผู้อำนวยการ', 'โครงการ', 'กลุ่ม', 'บริษัท', 'เมื่อ', 'เร็ว', 'ๆ', 'นี้', 'คุณ', 'Mr', '.', 'John', 'ได้', 'ตัดสินใจ', 'ลา', 'ออกจาก', 'The', 'Company']
```

**Comment by wannaphong** [comment]
Thai writing use "ๆ" as the repetition character for repetition of the previous word but It can change the meaning of word of use it. http://www.thai-language.com/ref/special-symbols and https://lingopolo.org/thai/word/symbol-for-repeat

**Comment by kepler** [comment]
So it means it's totally valid to sometimes have "ๆ" as a token and sometimes as part of another. Thanks for the clarification.

Related to this, would it mean anything different if "ๆ" was preceded by two white spaces or a longer white space? In the tokenizer, for the case of "recently", it causes "ๆ" to be split into a separate token.

**Comment by wannaphong** [comment]
> So it means it's totally valid to sometimes have "ๆ" as a token and sometimes as part of another. Thanks for the clarification.
> 
> Related to this, would it mean anything different if "ๆ" was preceded by two white spaces or a longer white space? In the tokenizer, for the case of "recently", it causes "ๆ" to be split into a separate token.

No. Today, Most Thai people in social network doesn't likes use any white space for "ๆ"  but the [Royal Society of Thailand](https://en.wikipedia.org/wiki/Royal_Society_of_Thailand) still recommend use a white spaces before and after used "ๆ".

**Comment by wannaphong** [comment]
If you see "เมื่อเร็วๆนี้"/"เมื่อเร็ว  ๆนี้"/"เมื่อเร็วๆ  นี้" then it has the same meaning as "เมื่อเร็ว ๆ นี้". All are same meaning. The longer white space doesn't change the meaning.

**Comment by kepler** [comment]
Thanks a lot, Wannaphong. This is very informative.

So despite all those forms meaning the same thing, the reason they don't get tokenized the same way is because of the dictionary?

```
>>> word_tokenize("เมื่อเร็วๆนี้", keep_whitespace=False)
['เมื่อ', 'เร็ว', 'ๆ', 'นี้']

>>> word_tokenize("เมื่อเร็วๆ นี้", keep_whitespace=False)
['เมื่อ', 'เร็ว', 'ๆ', 'นี้']

>>> word_tokenize("เมื่อเร็ว ๆนี้", keep_whitespace=False)
['เมื่อ', 'เร็ว ๆ', 'นี้']

>>> word_tokenize("เมื่อเร็ว ๆ นี้", keep_whitespace=False)
['เมื่อ', 'เร็ว ๆ นี้']
```

**Comment by wannaphong** [comment]
> Thanks a lot, Wannaphong. This is very informative.
> 
> So despite all those forms meaning the same thing, the reason they don't get tokenized the same way is because of the dictionary?

Yes, newmm is a dictionary-based tokenizer. You can custom the dictionary or try the [deep learning method](https://pythainlp.github.io/docs/3.1/api/tokenize.html#pythainlp.tokenize.word_tokenize).

This is the all open source resource for Thai: https://nlpforthai.com/

**Comment by kepler** [comment]
Thanks again. Appreciate the help.
