### ISSUE TITLE
bug: IndexError when romanizing 

### ISSUE THREAD

**Issue by maddyobrienjones** [PyThaiNLP/pythainlp#769]
### Description

When running `pythainlp.romanize("ไกรฤกษ์ โชติวุฒิวินิจ")`, throws an `IndexError`

### Expected results

Should return something like Krairiksh Chotiwutwinit (approximately)

### Current results

```
>>> pythainlp.romanize("ไกรฤกษ์ โชติวุฒิวินิจ")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maddyobrienjones/opt/anaconda3/envs/graph-env/lib/python3.8/site-packages/pythainlp/transliterate/core.py", line 59, in romanize
    return romanize(text)
  File "/Users/maddyobrienjones/opt/anaconda3/envs/graph-env/lib/python3.8/site-packages/pythainlp/transliterate/royin.py", line 216, in romanize
    romanized_words = [_romanize(word) for word in words]
  File "/Users/maddyobrienjones/opt/anaconda3/envs/graph-env/lib/python3.8/site-packages/pythainlp/transliterate/royin.py", line 216, in <listcomp>
    romanized_words = [_romanize(word) for word in words]
  File "/Users/maddyobrienjones/opt/anaconda3/envs/graph-env/lib/python3.8/site-packages/pythainlp/transliterate/royin.py", line 200, in _romanize
    word = _replace_consonants(word, consonants)
  File "/Users/maddyobrienjones/opt/anaconda3/envs/graph-env/lib/python3.8/site-packages/pythainlp/transliterate/royin.py", line 184, in _replace_consonants
    mod_chars.append(_CONSONANTS[consonants[j]][1])
IndexError: list index out of range
```

more detailed traceback:
```
word = 'ฤก', consonants = ['ก']

    def _replace_consonants(word: str, consonants: str) -> str:
        _HO_HIP = "\u0e2b"  # ห
        _RO_RUA = "\u0e23"  # ร
        _DOUBLE_RO_RUA = _RO_RUA + _RO_RUA
    
        if not consonants:
            return word
    
        skip = False
        mod_chars = []
        j = 0  # j is the index of consonants
        for i in range(len(word)):
            if skip:
                skip = False
                j += 1
            elif word[i] not in _CONSONANTS:  # word[i] is not a Thai consonant.
                mod_chars.append(word[i])
            elif (
                len(mod_chars) == 0 and word[i] == _HO_HIP and len(consonants) != 1
            ):  # Skip HO HIP except that HO HIP is the only one consonant
                j += 1
            elif (
                len(mod_chars) == 0
            ):  # The first character must be an initial consonant.
                mod_chars.append(_CONSONANTS[consonants[j]][0])
                j += 1
            elif word[i:] == _DOUBLE_RO_RUA:  # Double RO RUA is in end of word
                skip = True
                mod_chars.append("a")
                mod_chars.append("n")
                j += 1
            elif word[i : i + 2] == _DOUBLE_RO_RUA:
                skip = True
                mod_chars.append("a")
                j += 1
            else:  # Assume that the rest are final consonants.
>               mod_chars.append(_CONSONANTS[consonants[j]][1])
E               IndexError: list index out of range
```

### Steps to reproduce

`pythainlp.romanize("ไกรฤกษ์ โชติวุฒิวินิจ")`

### PyThaiNLP version

3.1.1

### Python version

3.8.15

### Operating system and version

MacOS Monterey

**Comment by wannaphong** [comment]
Hello @maddyobrienjones, Thank you for your report!

I suggest you should use word segmentation before give the word to the function. I wll improve the document.

**Comment by maddyobrienjones** [comment]
thanks @wannaphong! what would you suggest using for word segmentation? and would segmentation methods differ based on whether it's a word or a name being segmented? the inputs i have are all names

**Comment by wannaphong** [comment]
> thanks @wannaphong! what would you suggest using for word segmentation? and would segmentation methods differ based on whether it's a word or a name being segmented? the inputs i have are all names

You can use newmm to [segment words](https://pythainlp.github.io/docs/3.1/api/tokenize.html#pythainlp.tokenize.word_tokenize) and use ssg to [segment syllable](https://pythainlp.github.io/docs/3.1/api/tokenize.html#pythainlp.tokenize.subword_tokenize) before use romanize or trying to change [engine](https://pythainlp.github.io/docs/3.1/api/transliterate.html#pythainlp.transliterate.romanize).

**Comment by maddyobrienjones** [comment]
hi, this raised a different issue. when romanizing `ไกรฤกษ์ โชติวุฒิวินิจ`, i ended up getting `KairฤKs Chotiwuthiwinich`. here's my output from testing.
```
>>> from pythainlp.transliterate import romanize
>>> from pythainlp import tokenize
>>> name = "ไกรฤกษ์ โชติวุฒิวินิจ"
>>> syllables = [tokenize.subword_tokenize(w) for w in tokenize.word_tokenize(name)]
>>> new_words = []
>>> for s in syllables:
...     romanized = [romanize(syll) for syll in s]
...     new_words.append("".join(romanized))
... 
>>> " ".join(new_words).title()
'Kair ฤKs   Choti Wuthi Winich'
>>> parts = name.split()
>>> syllables = [tokenize.subword_tokenize(w) for w in parts]
>>> new_words = []
>>> for s in syllables:
...     romanized = [romanize(syll) for syll in s]
...     new_words.append("".join(romanized))
... 
>>> " ".join(new_words).title()
'KairฤKs Chotiwuthiwinich'
```

**Comment by wannaphong** [comment]
> hi, this raised a different issue. when romanizing `ไกรฤกษ์ โชติวุฒิวินิจ`, i ended up getting `KairฤKs Chotiwuthiwinich`. here's my output from testing.
> 
> ```
> >>> from pythainlp.transliterate import romanize
> >>> from pythainlp import tokenize
> >>> name = "ไกรฤกษ์ โชติวุฒิวินิจ"
> >>> syllables = [tokenize.subword_tokenize(w) for w in tokenize.word_tokenize(name)]
> >>> new_words = []
> >>> for s in syllables:
> ...     romanized = [romanize(syll) for syll in s]
> ...     new_words.append("".join(romanized))
> ... 
> >>> " ".join(new_words).title()
> 'Kair ฤKs   Choti Wuthi Winich'
> >>> parts = name.split()
> >>> syllables = [tokenize.subword_tokenize(w) for w in parts]
> >>> new_words = []
> >>> for s in syllables:
> ...     romanized = [romanize(syll) for syll in s]
> ...     new_words.append("".join(romanized))
> ... 
> >>> " ".join(new_words).title()
> 'KairฤKs Chotiwuthiwinich'
> ```

Can you try change the engine? https://pythainlp.github.io/docs/3.1/api/transliterate.html#pythainlp.transliterate.romanize

**Comment by wannaphong** [comment]
This issues don't have any update, so I will close this issue.
