### ISSUE TITLE
bug: sklearn error when install pythainlp

### ISSUE THREAD

**Issue by GenCharisma** [PyThaiNLP/pythainlp#774]
### Description

probably 'sklearn' PyPI package is now 'scikit-learn'
![image](https://user-images.githubusercontent.com/57989434/219960615-34ebafef-29e6-4fc1-bcfc-32e0ee6453ec.png)

for the time being, this will error sometime only

Reference
https://github.com/scikit-learn/sklearn-pypi-package

### Expected results

pythainlp install successfully

### Current results

installing pythainlp will only sometime successfully

### Steps to reproduce

by installing pythainlp
the writer uses `!pip install pythainlp[full]`

### PyThaiNLP version

3.1.1

### Python version

3.7.12

### Operating system and version

Kaggle

### Possible solution

use `pip install scikit-learn` instead

**Comment by wannaphong** [comment]
PyThaiNLP doesn't has scikit-learn in the [requirements.txt](https://github.com/PyThaiNLP/pythainlp/blob/dev/requirements.txt) or [setup.py](https://github.com/PyThaiNLP/pythainlp/blob/dev/setup.py). I don't sure where is sklearn in the requirements libraries.

**Comment by GenCharisma** [comment]
i try to install again with
`!pip install pythainlp[full]`

the full texts are these
![image](https://user-images.githubusercontent.com/57989434/221175121-f5ab21b5-5a75-4187-b423-0e3c53e3da0b.png)

note: `!pip install --upgrade pythainlp[full]` will install successfully
edit: sometime `!pip install --upgrade pythainlp[full]` will still got the error

it also said "This is an issue with the package mentioned above, not pip." so it probably not came from PyThaiNLP itself
(sorry for not screenshotted all of it last time)

**Comment by GenCharisma** [comment]
![image](https://user-images.githubusercontent.com/57989434/225153553-7cceeb1c-6b5b-4bd9-9f91-090566f12b08.png)

Turn out it came from `!pip install tltk>=1.3.8` because their [setup.py](https://github.com/attapol/tltk/blob/master/setup.py) use `!pip install sklearn` instead of `!pip install scikit-learn`.
Since pythainlp use tltk, it will pop error occasionally according to [scikit-learn's brownout schedule](https://github.com/scikit-learn/sklearn-pypi-package#brownout-schedule)

Things to be cleared from last time
- `!pip install --upgrade pythainlp[full]` will still got the error
- the current [scikit-learn's brownout schedule](https://github.com/scikit-learn/sklearn-pypi-package#brownout-schedule) is between first 00 to 10 minutes of every hour so it will only error on said time for the time being

vvv wrong button sorry vvv

**Comment by wannaphong** [comment]
Now, I removed tltk from `pythainlp[full]`.
