### ISSUE TITLE
Thai data and license

### ISSUE THREAD

**Issue by leky40** [PyThaiNLP/pythainlp#775]
สวัสดีค่ะ

เรากำลังหา Thai data เอาไป annotate แต่ที่ปรึกษาเขาพูดถึงเรื่อง CC License เขาบอกว่า ให้เช็คเรื่องนี้ เอาจริง ๆ เราไม่รู้เลยว่า อันไหนมีไม่มี ปกติเวลาทำโปรเจคเล็ก ๆ ในคลาสเรียน เราก็เอาบทความข่าวที่หาได้ในเนทหรือเว็บสำนักข่าวมาใช้ สามสี่บทความ ทำส่ง ได้เกรด

แต่อันนี้เราจะเอามาใช้ใน ธีสิสปอเอกเรา แล้วอาจารย์เขาติงมา เพราะเขาก็จะเอาไปใช้ในโปรเจคเขาด้วย 

เลยอยากทราบว่า จะสามารถเช็คได้อย่างไรว่า บทความประเภทนี้มี CC License ไหม หรือบทความประเภทไหนที่สามารถเอามาใช้ได้เลยไหม แบบสามารถ redistributed ได้ 

แล้วใน Thai National Corpus หรือ SketchEngine นี่สามารถเอามาใช้ได้เลยไหมคะ หรือต้องเช็ค license ก่อนมาใช้อีกที

ขอบคุณค่ะ

**Comment by wannaphong** [comment]
แนะนำให้ดูคำประกาศของเว็บไซต์แต่ละแหล่งเป็นหลักครับ เช่น [Blognone](https://www.blognone.com/about) อันนี้ประกาศ CC BY 3.0 ชัดเจนครับ ส่วน Thai National Corpus ผมเข้าใจว่าเขาไปตกลงกับเจ้าของลิขสิทธิ์แล้วครับ แต่ไม่ได้เผยแพร่ข้อความเต็ม ๆ ในชุดข้อมูลออกมา อาจเพราะข้อตกลงของเขาครับ แนะนำให้เช็กโดยการติดต่อเว็บไซต์นั้น ๆ โดยตรงเกี่ยวกับเรื่อง License ครับ แต่เอาเข้าจริง ๆ พ.ร.บ.ลิขสิทธิ์ พ.ศ. 2537 มีข้อยกเว้น ไม่ถือว่าเป็นงานอันมีลิขสิทธิ์ตามพระราชบัญญัติอยู่ครับ

```
มาตรา ๗ สิ่งต่อไปนี้ไม่ถือว่าเป็นงานอันมีลิขสิทธิ์ตามพระราชบัญญัตินี้
(๑) ข่าวประจาวัน และข้อเท็จจริงต่าง ๆ ที่มีลักษณะเป็นเพียงข่าวสารอันมิใช่งานในแผนกวรรณคดี แผนกวิทยาศาสตร์ หรือแผนกศิลปะ
(๒) รัฐธรรมนูญ และกฎหมาย
(๓) ระเบียบ ข้อบังคับ ประกาศ คำสั่ง คำชี้แจง และหนังสือโต้ตอบของกระทรวง ทบวง กรมหรือหน่วยงานอื่นใดของรัฐหรือของท้องถิ่น
(๔) คำพิพากษา คำสั่ง คำวินิจฉัย และรายงานของทางราชการ
(๕) คำแปลและการรวบรวมสิ่งต่าง ๆ ตาม (๑) ถึง (๔) ที่กระทรวง ทบวง กรม หรือหน่วยงานอื่นใดของรัฐหรือของท้องถิ่นจัดทำขึ้น
```

กับ มาตรา ๓๒
```
ภายใต้บังคับบทบัญญัติในวรรคหนึ่ง การกระทำอย่างใดอย่างหนึ่งแก่งานอันมีลิขสิทธิ์ตาม วรรคหนึ่ง มิให้ถือว่าเป็นการละเมิดลิขสิทธิ์ ถ้าได้กระทำดังต่อไปนี้
...
(๑) วิจัยหรือศึกษางานนั้น อันมิใช่การกระทำเพื่อหากำไร
...
```

อ่านเพิ่มเติมได้ที่  [พระราชบัญญัติลิขสิทธิ์ พ.ศ. 2537 และที่แก้ไขเพิ่มเติม](https://www.ipthailand.go.th/th/dip-law-2/item/copyright_act2_th.html)  ครับ

**Comment by leky40** [comment]
@wannaphong ขอบคุณมากค่ะ

เราก็ดูใน PyThaiNLP นี้ แบบใช้ data อะไร เก็บข้อมูลประเภทไหน เห็นมีแปะ LICENSE ไว้ เราก็อ่าน ไม่ค่อยแน่ใจ แต่ใจอยากได้หลากหลายประเภทบทความ ไม่ใช่แค่ข่าว หรือบทความทางการมาก ๆ เพราะจะเอามาใช้ analyze Thai grammar, basing on the Thai corpus

**Comment by wannaphong** [comment]
> @wannaphong ขอบคุณมากค่ะ
> 
> เราก็ดูใน PyThaiNLP นี้ แบบใช้ data อะไร เก็บข้อมูลประเภทไหน เห็นมีแปะ LICENSE ไว้ เราก็อ่าน ไม่ค่อยแน่ใจ แต่ใจอยากได้หลากหลายประเภทบทความ ไม่ใช่แค่ข่าว หรือบทความทางการมาก ๆ เพราะจะเอามาใช้ analyze Thai grammar, basing on the Thai corpus

ใช้ชุดข้อมูลนี้ได้ครับ https://github.com/mrpeerat/OSKut/tree/main/VISTEC-TP-TH-2021

**Comment by leky40** [comment]
@wannaphong  ขอบคุณมากค่ะ พอจะแนะนำ spoken corpora ของไทย ได้ไหมคะ จะไปหาได้ที่ไหน หรือเก็บ spoken Thai data กันยังไง มีใครทำไหม

**Comment by wannaphong** [comment]
ลองดูใน https://nlpforthai.com/tasks/speech-recognition/ ได้ครับ

**Comment by leky40** [comment]
@wannaphong ขอบคุณมากค่ะ
