### ISSUE TITLE
ทดลองเรียกใช้ Thai2vec แล้วเจอ Error

### ISSUE THREAD

**Issue by ammiiamm** [PyThaiNLP/pythainlp#78]
สวัสดีค่ะ 

พอดีทดลองเรียกใช้ Thai2vec ดู ตามคำสั่งด้านล่าง 
`thai2vec.similarity("แมว","ปลา")`

ปรากฏว่าโปรแกรมขึ้น error : ValueError: invalid literal for int() with base 10: 'version'

ไม่แน่ใจว่าเกี่ยวข้องกับไฟล์ .vec รึเปล่านะคะ รบกวนช่วยตรวจสอบด้วยค่ะ ทั้งนี้ขอแนบไฟล์ Notebook ที่ทดสอบมาด้วยค่ะ https://drive.google.com/file/d/1BhbM59K1CHm9PJa-PYgq_x7QRnXnDWdY/view?usp=sharing

ขอบคุณค่ะ

**Comment by wannaphongcom** [comment]
ได้ลอง thai2vec.download() ยังครับ

**Comment by ammiiamm** [comment]
ลองเพิ่มเติมแล้วค่ะ(ใน Link Notebook เดิมข้างบน) สิ่งที่ download มาไม่ใช่ vector แต่เป็นข้อมูลตามด้านล่างค่ะ

> version https://git-lfs.github.com/spec/v1
oid sha256:fc262c3be0a5db8198c1f58a41a56d84ef96163009ccbbd8c94775f231df0e9d
size 147622245

ปล. พอดีเห็นคำว่า git-lfs เลยลองไป `git lfs clone` ตรงๆที่ Repo ของ Thai2vec ก็เจอปัญหา Repo Over Data Quota แทนค่ะ ^^"

**Comment by cstorm125** [comment]
อัพเกรด data pack ของ lfs แล้วครับ 
ต่อไปอาจจะเปลี่ยนไปเก็บที่อื่นแทน 
@wannaphongcom ถ้าได้ที่ใหม่เดี๋ยววานอัพเดท thai2vec.download() ด้วยนะครับ

**Comment by wannaphongcom** [comment]
ลอง thai2vec.download()  ใหม่อีกรอบครับ

**Comment by cstorm125** [comment]
Google drive link:
https://drive.google.com/drive/folders/1_vZr_iR_LqIX4rEi7i5spN_6QDgj5r81?usp=sharing

**Comment by ammiiamm** [comment]
ทดลอง download อีกรอบแล้ว ใช้ได้แล้วค่ะ ขอบคุณนะคะ :)

**Comment by wannaphongcom** [comment]
fix in PyThaiNLP 1.6.0.4
