### ISSUE TITLE
bug: Cant find Marttra in word ends with tone mark

### ISSUE THREAD

**Issue by S2P2** [PyThaiNLP/pythainlp#790]
### Description

For module pythainlp.khavee
There are some bugs (logic error) when using function check_marttra with word that ending with tone mark (ไม้เอก, ไม้โท, ไม้ตรี, ไม้จัตวา; ่ ้ ๊ ๋)

### Expected results

```
from pythainlp.khavee import KhaveeVerifier
kv = KhaveeVerifier()
# สี่ (four in Thai, ending with ไม้เอก ' ่')
print(kv.check_marttra('สี่'))
```
กา

### Current results

Cant find Marttra in this word

### Steps to reproduce

```
from pythainlp.khavee import KhaveeVerifier
kv = KhaveeVerifier()
# สี่ (four in Thai, ending with ไม้เอก ' ่')
print(kv.check_marttra('สี่'))
# any word that end with tone mark
```

### PyThaiNLP version

4.0.0

### Python version

3.9.16

### Operating system and version

Ubuntu 20.04.5 LTS

### More info

Running via Google Colab

### Possible solution

use pythainlp.util.remove_tonemark to remove tone mark before input in check_marttra (as a workaround for now)
maybe add more statement in the function to deal with these cases

**Comment by wannaphong** [comment]
@kangkengkhadev @HRNPH I don't sure about this bug.

**Comment by HRNPH** [comment]
well I think remove tone mark should work but I'm also not sure yet
I'll take a look at this tmrw just assign it to me
