### ISSUE TITLE
bug: wrong output of check_marttra in case of 'มนตร์' and 'พักตร์'

### ISSUE THREAD

**Issue by S2P2** [PyThaiNLP/pythainlp#791]
### Description

wrong output of check_marttra in case of 'มนตร์' and 'พักตร์'

### Expected results

```
from pythainlp.khavee import KhaveeVerifier
kv = KhaveeVerifier()

print(kv.check_marttra('มนตร์'))
```
กน

`print(kv.check_marttra('พักตร์'))`
กก

### Current results

```
from pythainlp.khavee import KhaveeVerifier
kv = KhaveeVerifier()

print(kv.check_marttra('มนตร์'))
```
กด

`print(kv.check_marttra('พักตร์'))`
กด

### Steps to reproduce

```
from pythainlp.khavee import KhaveeVerifier
kv = KhaveeVerifier()

print(kv.check_marttra('มนตร์'))
```
or
```
from pythainlp.khavee import KhaveeVerifier
kv = KhaveeVerifier()

print(kv.check_marttra('พักตร์'))
```

### PyThaiNLP version

4.0.0

### Python version

3.9.16

### Operating system and version

Ubuntu 20.04.5 LTS

### Possible solution

add these special cases in logic chain

...
```
        if word[-1] == 'ร' and word[-2] in ['ต','ท'] :
            word = word[:-1]
        if '์' in word[-1]:
            if 'ต' in word[-3] and 'ร' in word[-2]:
                word = word[:-4]
            if 'ิ' in word[-2] or 'ุ' in word[-2]:
                word = word[:-3]
            else:
                word = word[:-2]
```
...

total function code below
```
    def check_marttra(self, word: str) -> str:
        """
        Check the Thai spelling Section in the Thai word.

        :param str word: Thai word
        :return: name spelling Section of the word.
        :rtype: str

        :Example:
        ::

            from pythainlp.khavee import KhaveeVerifier

            kv = KhaveeVerifier()

            print(kv.check_marttra('สาว'))
            # output: 'เกอว'
        """
        if word[-1] == 'ร' and word[-2] in ['ต','ท'] :
            word = word[:-1]
        if '์' in word[-1]:
            if 'ต' in word[-3] and 'ร' in word[-2]:
                word = word[:-4]
            if 'ิ' in word[-2] or 'ุ' in word[-2]:
                word = word[:-3]
            else:
                word = word[:-2]
        if 'ำ' in word or ('ํ' in word and 'า' in word) or 'ไ' in word or 'ใ' in word:
            return 'กา'
        elif word[-1] in ['า','ะ','ิ','ี','ุ','ู','อ'] or ('ี' in word and 'ย' in word[-1]) or ('ื' in word and 'อ' in word[-1]):
            return 'กา'
        elif word[-1] in ['ง']:
            return 'กง'
        elif word[-1] in ['ม']:
            return 'กม'
        elif word[-1] in ['ย']:
            if 'ั' in word:
                return 'กา'
            else:
                return 'เกย'
        elif word[-1] in ['ว']:
            return 'เกอว'
        elif word[-1] in ['ก','ข','ค','ฆ']:
            return 'กก'
        elif word[-1] in ['จ','ช','ซ','ฎ','ฏ','ฐ','ฑ','ฒ','ด','ต','ถ','ท','ธ','ศ','ษ','ส'] :
            return 'กด'
        elif word[-1] in ['ญ',', ณ' ,'น' ,'ร' ,'ล' ,'ฬ']:
            return 'กน'
        elif word[-1] in ['บ', 'ป', 'พ', 'ฟ', 'ภ']:
            return 'กบ'
        else:
           if '็' in word:
               return 'กา'
           else:
               return 'Cant find Marttra in this word'
```

**Comment by wannaphong** [comment]
@kangkengkhadev @HRNPH I think you can fix.

**Comment by HRNPH** [comment]
> @kangkengkhadev @HRNPH I think you can fix.

I'll take a look at this today assign this to me

**Comment by HRNPH** [comment]
the reason is khavee matra checker only check LAST character AKA. ตัวสะกด
for example 'มนตร์' will return กด because the karun handled text by old cleaner is มนต 
```python
word = 'พักตร'
if '์' in word[-1]:
    if 'ิ' in word[-2] or 'ุ' in word[-2]:
        word = word[:-3]
    else:
        word = word[:-2]
    print(word)
> มนต

print(handle_karun_sound_silence(word))
> มน
```

I propose this fix, By handling Karun sound silence according to [This](https://www.facebook.com/manamaneepitichuejai/posts/%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2-%E0%B8%97%E0%B8%B1%E0%B8%93%E0%B8%91%E0%B8%86%E0%B8%B2%E0%B8%95-%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD-%E0%B9%84%E0%B8%A1%E0%B9%89%E0%B8%97%E0%B8%B1%E0%B8%93%E0%B8%91%E0%B8%86%E0%B8%B2%E0%B8%95-%E0%B8%A1%E0%B8%B5%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B9%80%E0%B8%81%E0%B8%93%E0%B8%91%E0%B9%8C%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%94%E0%B8%B1%E0%B8%87%E0%B8%99%E0%B8%B5%E0%B9%89%E0%B9%91-%E0%B8%AA%E0%B8%A1%E0%B8%B1%E0%B8%A2%E0%B8%81%E0%B9%88%E0%B8%AD%E0%B8%99%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B9%80%E0%B8%82%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B9%83%E0%B8%99%E0%B8%A0/1370863443069441/)

we can now have a function that stripped (ลดรูป) silenced words and I'll use this to replace the old karun cleaning line

```python
  def handle_karun_sound_silence(text: str) -> str:
      """
      Handle sound silence in Thai word using '์' character (Karun)
      by stripping all the characters before the 'Karun' character that should be silenced

      :param str text: Thai word
      :return: Thai word with silence word stripped
      :rtype: str
      """
      sound_silenced = True if word.endswith('์') else False
      if not sound_silenced:
          return text
      thai_consonants = "กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรลวศษสหฬอฮ"
      locate_silenced = word.rfind('์') - 1
      can_silence_two = True if word[locate_silenced-2] in thai_consonants else False
      cut_off = 2 if can_silence_two else 1
      word = word[:locate_silenced + 1 - cut_off]
      return word
  ```
  
  Full function should look like this
  
  ```python
      def check_marttra(self, word: str) -> str:
        """
        Check the Thai spelling Section in the Thai word.

        :param str word: Thai word
        :return: name spelling Section of the word.
        :rtype: str

        :Example:
        ::

            from pythainlp.khavee import KhaveeVerifier

            kv = KhaveeVerifier()

            print(kv.check_marttra('สาว'))
            # output: 'เกอว'
        """
        if word[-1] == 'ร' and word[-2] in ['ต','ท'] :
            word = word[:-1]
        word = self.handle_karun_sound_silenced(word) # changed 
        if 'ำ' in word or ('ํ' in word and 'า' in word) or 'ไ' in word or 'ใ' in word:
            return 'กา'
        elif word[-1] in ['า','ะ','ิ','ี','ุ','ู','อ'] or ('ี' in word and 'ย' in word[-1]) or ('ื' in word and 'อ' in word[-1]):
            return 'กา'
        elif word[-1] in ['ง']:
            return 'กง'
        elif word[-1] in ['ม']:
            return 'กม'
        elif word[-1] in ['ย']:
            if 'ั' in word:
                return 'กา'
            else:
                return 'เกย'
        elif word[-1] in ['ว']:
            return 'เกอว'
        elif word[-1] in ['ก','ข','ค','ฆ']:
            return 'กก'
        elif word[-1] in ['จ','ช','ซ','ฎ','ฏ','ฐ','ฑ','ฒ','ด','ต','ถ','ท','ธ','ศ','ษ','ส'] :
            return 'กด'
        elif word[-1] in ['ญ',', ณ' ,'น' ,'ร' ,'ล' ,'ฬ']:
            return 'กน'
        elif word[-1] in ['บ', 'ป', 'พ', 'ฟ', 'ภ']:
            return 'กบ'
        else:
           if '็' in word:
               return 'กา'
           else:
               return 'Cant find Marttra in this word'
 ```
 @wannaphong may I ask you to take a look if this fix look LGTM to you? before I'll make a PR

**Comment by wannaphong** [comment]
> the reason is khavee matra checker only check LAST character AKA. ตัวสะกด for example 'มนตร์' will return กด because the karun handled text by old cleaner is มนต
> 
> ```python
> word = 'พักตร'
> if '์' in word[-1]:
>     if 'ิ' in word[-2] or 'ุ' in word[-2]:
>         word = word[:-3]
>     else:
>         word = word[:-2]
>     print(word)
> > มนต
> 
> print(handle_karun_sound_silence(word))
> > มน
> ```
> 
> I propose this fix, By handling Karun sound silence according to [This](https://www.facebook.com/manamaneepitichuejai/posts/%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2-%E0%B8%97%E0%B8%B1%E0%B8%93%E0%B8%91%E0%B8%86%E0%B8%B2%E0%B8%95-%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD-%E0%B9%84%E0%B8%A1%E0%B9%89%E0%B8%97%E0%B8%B1%E0%B8%93%E0%B8%91%E0%B8%86%E0%B8%B2%E0%B8%95-%E0%B8%A1%E0%B8%B5%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B9%80%E0%B8%81%E0%B8%93%E0%B8%91%E0%B9%8C%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%94%E0%B8%B1%E0%B8%87%E0%B8%99%E0%B8%B5%E0%B9%89%E0%B9%91-%E0%B8%AA%E0%B8%A1%E0%B8%B1%E0%B8%A2%E0%B8%81%E0%B9%88%E0%B8%AD%E0%B8%99%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B9%80%E0%B8%82%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B9%83%E0%B8%99%E0%B8%A0/1370863443069441/)
> 
> we can now have a function that stripped (ลดรูป) silenced words and I'll use this to replace the old karun cleaning line
> 
> ```python
>   def handle_karun_sound_silence(text: str) -> str:
>       """
>       Handle sound silence in Thai word using '์' character (Karun)
>       by stripping all the characters before the 'Karun' character that should be silenced
> 
>       :param str text: Thai word
>       :return: Thai word with silence word stripped
>       :rtype: str
>       """
>       sound_silenced = True if word.endswith('์') else False
>       if not sound_silenced:
>           return text
>       thai_consonants = "กขฃคฅฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรลวศษสหฬอฮ"
>       locate_silenced = word.rfind('์') - 1
>       can_silence_two = True if word[locate_silenced-2] in thai_consonants else False
>       cut_off = 2 if can_silence_two else 1
>       word = word[:locate_silenced + 1 - cut_off]
>       return word
> ```
> 
> Full function should look like this
> 
> ```python
>     def check_marttra(self, word: str) -> str:
>       """
>       Check the Thai spelling Section in the Thai word.
> 
>       :param str word: Thai word
>       :return: name spelling Section of the word.
>       :rtype: str
> 
>       :Example:
>       ::
> 
>           from pythainlp.khavee import KhaveeVerifier
> 
>           kv = KhaveeVerifier()
> 
>           print(kv.check_marttra('สาว'))
>           # output: 'เกอว'
>       """
>       if word[-1] == 'ร' and word[-2] in ['ต','ท'] :
>           word = word[:-1]
>       word = self.handle_karun_sound_silenced(word) # changed 
>       if 'ำ' in word or ('ํ' in word and 'า' in word) or 'ไ' in word or 'ใ' in word:
>           return 'กา'
>       elif word[-1] in ['า','ะ','ิ','ี','ุ','ู','อ'] or ('ี' in word and 'ย' in word[-1]) or ('ื' in word and 'อ' in word[-1]):
>           return 'กา'
>       elif word[-1] in ['ง']:
>           return 'กง'
>       elif word[-1] in ['ม']:
>           return 'กม'
>       elif word[-1] in ['ย']:
>           if 'ั' in word:
>               return 'กา'
>           else:
>               return 'เกย'
>       elif word[-1] in ['ว']:
>           return 'เกอว'
>       elif word[-1] in ['ก','ข','ค','ฆ']:
>           return 'กก'
>       elif word[-1] in ['จ','ช','ซ','ฎ','ฏ','ฐ','ฑ','ฒ','ด','ต','ถ','ท','ธ','ศ','ษ','ส'] :
>           return 'กด'
>       elif word[-1] in ['ญ',', ณ' ,'น' ,'ร' ,'ล' ,'ฬ']:
>           return 'กน'
>       elif word[-1] in ['บ', 'ป', 'พ', 'ฟ', 'ภ']:
>           return 'กบ'
>       else:
>          if '็' in word:
>              return 'กา'
>          else:
>              return 'Cant find Marttra in this word'
> ```
> 
> @wannaphong may I ask you to take a look if this fix look LGTM to you? before I'll make a PR

I think It's OK.

**Comment by wannaphong** [comment]
Fixed https://github.com/PyThaiNLP/pythainlp/pull/793
