### ISSUE TITLE
Twitter 

### ISSUE THREAD

**Issue by leky40** [PyThaiNLP/pythainlp#794]
มีใครเคยใช้ข้อมูล หรือโพสต่าง ๆ ใน Twitter ภาษาไทยไหมคะ เราสามารถนำมาใช้ได้เลยไหม ติดเรื่องลิขสิทธิ์ไหมคะ

หรือพอจะแนะนำ ข้อมูล / ข้อความ ที่เป็นโพสแชทภาษาไทย ที่สามารถทำมาใช้ได้เลยไหมคะ

**Comment by wannaphong** [comment]
ตอนนี้ Twitter กำลังเปลี่ยนแปลงนโยบายหลายอย่างอยู่ครับ แต่ถ้าใช้ในงานวิจัย กฎหมายลิขสิทธิ์ของประเทศไทยมีข้อยกเว้นสำหรับงานวิจัยอยู่แล้วครับ

**Comment by leky40** [comment]
@wannaphong สามารถเลือก Post จาก twitter account ของไทย แล้ว copy มาใช้ได้เลยเหรอคะ แล้วมีวิธีไหนที่จะเก็บ metadata ของแต่ละโพสไหมคะ แล้วจะเช็คนโยบายที่กำลังเปลี่ยนแปลงได้ที่ไหนคะ

**Comment by wannaphong** [comment]
มีวิธีไหนที่จะเก็บ metadata ของแต่ละโพส

> แนะนำเขียนโปรแกรมตามไลบารีที่ใช้ครับ

จะเช็คนโยบายที่กำลังเปลี่ยนแปลงได้ที่ไหน

> https://developer.twitter.com/en/developer-terms/commercial-terms
