### ISSUE TITLE
Add sentence segmentation with 'wtpsplit'

### ISSUE THREAD

**Issue by Querela** [PyThaiNLP/pythainlp#803]
## Detailed description

Recently, [`wtpsplit`](https://github.com/bminixhofer/wtpsplit) was published and it also support multi-lingual sentence segmentation (with Thai being one of the languages). I'm not sure how it compares to the existing [`crfcut`](https://github.com/PyThaiNLP/pythainlp/blob/36002363657560065ea4a3fb2929ebadff595809/pythainlp/tokenize/core.py#L343) method as I'm not too familiar with the Thai language to check segmentation results but it might be a good addition.

## Context

- We automatically create statistical text corpora from crawled web texts. "Sentence" is a common segmentation unit we use in this case, especially to deduplicate common sentences. Paragraphs (often containing multiple sentences) hinder deduplication efforts.

- Benefit: Another possible (robust?) option to "sentence" segment Thai text. Since not all texts mark sentences boundaries with whitespaces (e.g. social media?). More options seem to be better (if the options work well) and might support different text genres and formats.

## Possible implementation

- https://github.com/bminixhofer/wtpsplit
  - with language code `th`
  - different models seem to exists (small and large ones)

**Comment by wannaphong** [comment]
Thank you! We are working to add sentence segmentation with 'wtpsplit'.

**Comment by wannaphong** [comment]
Done!

`wtpsplit` will include in PyThaiNLP 4.1.
