### ISSUE TITLE
Add alpha value in `wtpsplit`

### ISSUE THREAD

**Issue by pavaris-pm** [PyThaiNLP/pythainlp#807]
According to the original paper **'Where's the Point? Self-Supervised Multilingual Punctuation-Agnostic Sentence Segmentation,'** we have an option to adjust the paragraph threshold using the `paragraph_threshold` argument in `wtpsplit`. This threshold corresponds to the `alpha` value mentioned in the paper's method section. I already made a PR at #806 include the usage and output example of using that alpha value, with that, we can specify the paragraph threshold for wtpsplit if we want. What do you think ?

**Comment by wannaphong** [comment]
I agree. :+1:
