### ISSUE TITLE
simple tf-idf for thai document (after tokenize)? 

### ISSUE THREAD

**Issue by mikephul** [PyThaiNLP/pythainlp#81]
มีใครทำไปรึยังครับ พอดีผมลองใช้ของ scikit-learn แล้วออกมามั่วมาก

**Comment by cstorm125** [comment]
I think the best solution is to use the tokenizer from pyThaiNLP, then use many available solutions such as nltk, spacy, gensim, etc. (for python) or tm and quanteda (for R) for document frequency matrices.

**Comment by mikephul** [comment]
Thanks for the suggestion! Get it to work with gensim. 
From my quick try in python (for future reference)
1. [nltk doesn't support tf-idf ](https://www2.cs.duke.edu/courses/spring14/compsci290/assignments/lab02.html)
2. sklearn TfidfVectorizer gives weird result for Thai 
`from sklearn.feature_extraction.text import TfidfVectorizer
 documents = ['เดี๋ยว', 'ไป', 'ส่ง', 'นะ']
 tfidf_vectorizer = TfidfVectorizer()
 tfidf = tfidf_vectorizer.fit_transform(documents)
 tfidf_vectorizer.get_feature_names()
# this output ['นะ', 'ยว', 'เด', 'ไป']
`
