### ISSUE TITLE
Incorrect Sentiment analysis

### ISSUE THREAD

**Issue by san73** [PyThaiNLP/pythainlp#82]
from pythainlp.sentiment import sentiment
i = 'ผมมีความสุข'
sentiment(i)

Output : 'neg'

The following text has positive sentiment but the output is negative. Can someone help me please. Thanks

**Comment by wannaphongcom** [comment]
We are looking for a solution.

**Comment by wannaphongcom** [comment]
https://github.com/PyThaiNLP/pythainlp/issues/83

**Comment by san73** [comment]
Hello wassphongcom,

Hope you doing well. 

I have come across many positive keywords, which is classified as negative. I guess the keyword list has to be updated.

Also is it possible to have neutral sentiment for the text. I only see positive and negative sentiment. A text without positive or negative words can be classified as neutral. 

Thank you for your cooperation.

**Comment by wannaphongcom** [comment]
We doing a new sentiment analysis for PyThaiNLP. Coming Soon !!!

**Comment by wannaphongcom** [comment]
Close https://github.com/PyThaiNLP/pythainlp/commit/60daa0ec6a113ac524a53c59eacfe669157a0d10
Notebook : https://colab.research.google.com/drive/1ZZHAZhk15cHOeITVshhpcT9EYEiLbAyc
