### ISSUE TITLE
bug: ModuleNotFoundError: No module named 'pythainlp.chat'

### ISSUE THREAD

**Issue by tonezzz** [PyThaiNLP/pythainlp#828]
### Description

Hi,
I'm just starting to learn to build AI.  I stumbled to your project and it looks interesting.  So I'm trying to learn to create a chat bot out of your project now.  Starting from the test-chat.jpynb.  But I cannot run it.
Please let me know what've I missed or did wrong.
Thank you very much.
Cheers,
Tony.

### Expected results

A successful import of:
  from pythainlp.chat.core import ChatBotModel

### Current results

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-4-4fc4580c3e19>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from pythainlp.chat.core import ChatBotModel
      2 import torch
ModuleNotFoundError: No module named 'pythainlp.chat'
---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Steps to reproduce

1. Open test-chat.jpynb on Colab.
2. Add "!pip install --upgrade pythainlp[full]" on top & run.
3. Run the import block.

### PyThaiNLP version

4.1.0beta1

### Python version

3.10.6

### Operating system and version
(from Colab)
Linux version 5.15.109+ (builder@a1d285de7a25) (Chromium OS 15.0_pre458507_p20220602-r18 clang version 15.0.0 (/var/tmp/portage/sys-devel/llvm-15.0_pre458507_p20220602-r18/work/llvm-15.0_pre458507_p20220602/clang a58d0af058038595c93de961b725f86997cf8d4a), LLD 15.0.0) #1 SMP Fri Jun 9 10:57:30 UTC 2023

**Comment by tonezzz** [comment]
Here're two screen shots of the 1st block added by me and the 2nd block from test-chat.jpynb.

![s-02](https://github.com/PyThaiNLP/pythainlp/assets/12311839/9e8b2052-7109-4ae4-b353-0979770b0a14)
![s-01](https://github.com/PyThaiNLP/pythainlp/assets/12311839/bf81caeb-6275-45d2-9a66-062ad9eacb60)

**Comment by wannaphong** [comment]
Hello! PyThaiNLP v4.1.0beta1 still is in beta channel. You can install by `!pip install --pre --upgrade pythainlp[full]`

**Comment by tonezzz** [comment]
> Hello! PyThaiNLP v4.1.0beta1 still is in beta channel. You can install by `!pip install --pre --upgrade pythainlp[full]`

Thank you.  I'm quite sure I tried that before without success.  Anyway, I tried again and it works now.
Have a nice day & Cheers.
![image](https://github.com/PyThaiNLP/pythainlp/assets/12311839/e6f56b71-b971-4914-958c-5d9c60aafe62)

**Comment by tonezzz** [comment]
OK, now I'm using GPU instance.  And still got this error.  Could you help me again please?
![image](https://github.com/PyThaiNLP/pythainlp/assets/12311839/bdf99287-7e5d-4421-9866-1e93f748e69e)

**Comment by wannaphong** [comment]
I just released PyThaiNLP v.4.1.0-beta2 https://github.com/PyThaiNLP/pythainlp/commit/cc9139c3e19745c92e518bcb383da1daf0848207. Can you try again?

> OK, now I'm using GPU instance. And still got this error. Could you help me again please? ![image](https://user-images.githubusercontent.com/12311839/256505267-bdf99287-7e5d-4421-9866-1e93f748e69e.png)

**Comment by tonezzz** [comment]
> I just released PyThaiNLP v.4.1.0-beta2 [cc9139c](https://github.com/PyThaiNLP/pythainlp/commit/cc9139c3e19745c92e518bcb383da1daf0848207). Can you try again?

Nice!  It's working now Thank you.
![image](https://github.com/PyThaiNLP/pythainlp/assets/12311839/b751ce02-fe93-4cd5-bef9-03b04d7e69f8)
