### ISSUE TITLE
bug: Not enough memory when running on Kaggle

### ISSUE THREAD

**Issue by tonezzz** [PyThaiNLP/pythainlp#829]
### Description

In order to use free accelerator I'm trying to run it on https://kaggle.com with GPU T4x2 config but I've got load_model error, not enough memory.  Could you help me finding some solutions?

Is it possible to reduce some memory usage?
Is it possible to use TPU?  How?

Thanks,
Tony.

![image](https://github.com/PyThaiNLP/pythainlp/assets/12311839/d1249b57-9e21-47b8-817e-186d913b7c35)

### Expected results

Program load model & execute successfully.

### Current results

Program crashed, with error message:
- Your notebook tried to allocate too much memory and could not be recovered. You will need to start a new session.
- Your notebook tried to allocate more memory than is available. It has restarted.

### Steps to reproduce

Open a notebook at Kaggle.com, set options to GPU T4 x2 and run the following code.

!pip install --pre --upgrade pythainlp[full]

from pythainlp.chat.core import ChatBotModel
import torch

chatbot = ChatBotModel()
chatbot.load_model(device="cpu" ,torch_dtype=torch.bfloat16)

![image](https://github.com/PyThaiNLP/pythainlp/assets/12311839/be9f9f6e-f6f1-40b5-a939-795817b61196)

### PyThaiNLP version

4.1.0beta2

### Python version

3.10.12

### Operating system and version

Linux fc5394d1b557 5.15.120+ #1 SMP Fri Jul 21 03:39:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wannaphong** [comment]
Hello! You can use `load_in_8bit=True` in `ChatBotModel.load_model`.

**Comment by tonezzz** [comment]
Thanks, but there's still error.

![image](https://github.com/PyThaiNLP/pythainlp/assets/12311839/62dde03d-6873-49d0-bc4d-50d7d236cfea)

**Comment by wannaphong** [comment]
I think you should restart kernel after install bitsandbytes.
