### ISSUE TITLE
Impove document

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#840]
You can help me impove PyThaiNLP's document.

The PyThaiNLP's documentation is in https://github.com/PyThaiNLP/pythainlp/tree/dev/docs. It's use Sphinx to build the document.

The build tools can install by

> pip install boto smart_open sphinx sphinx-rtd-theme

and build by

> cd docs
> make html

(Don't forget install make tools)

For API Docs:

You can edit by source code in PyThaiNLP. It's use [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html) for writing API docs.

**Comment by wannaphong** [comment]
You can help me improve tutorials. see https://github.com/PyThaiNLP/tutorials/issues/22

**Comment by Saharshjain78** [comment]
Hey, I am interested in improving the documents, can you describe more about the issue?

**Comment by wannaphong** [comment]
> Hey, I am interested in improving the documents, can you describe more about the issue?

Some examples are missing, bad grammar, and missing necessary details.

Example: https://pythainlp.github.io/dev-docs/api/generate.html#pythainlp.generate.wangchanglm.WangChanGLM is missing necessary details about model and example.
