### ISSUE TITLE
bug: Duplicate key in dictionary

### ISSUE THREAD

**Issue by BLKSerene** [PyThaiNLP/pythainlp#846]
### Description

Two issues of duplicate keys in dictionary are found in the codebase:

https://github.com/PyThaiNLP/pythainlp/blob/73b17e326a459b0fbeb89a5e1e8631783d6696c2/pythainlp/transliterate/iso_11940.py#L108-L125

The key "ฯ" has been assigned two different values: "ǂ" and "ǀ".

https://github.com/PyThaiNLP/pythainlp/blob/73b17e326a459b0fbeb89a5e1e8631783d6696c2/pythainlp/util/phoneme.py#L123-L185

The key "j" has been assigned two different values: "y" and "i".

Since I do not speak Thai, I do not have the required knowledge to decide on which line should be removed.

### Expected results

No duplicate keys in dictionaries.

### Current results

Duplicate keys in dictionaries.

### Steps to reproduce

Check in the codebase.

### PyThaiNLP version

4.0.2

### Python version

3.10.13

### Operating system and version

Windows 11 22H2 x64

**Comment by bact** [comment]
For ฯ it's "by design".

From Wikipedia:

"ISO 11940:1998 distinguishes the abbreviation symbol paiyannoi (ฯ) from the sentence terminator angkhandiao (ฯ), even though neither the national character standard TIS 620-2533 nor Unicode Version 5.0 distinguishes them. Paiyannoi is transliterated as ǂ and angkhandiao is transliterated as ǀ. Note that paiyannoi, angkhandiao and angkhankhu (๚) are transliterated by the letters used for click consonants, not by double dagger, vertical bars or dandas."

https://en.wikipedia.org/wiki/ISO_11940

I would say we can just pick Paiyannoi and neglect Angkhandiao.

**Comment by BLKSerene** [comment]
@bact What is your opinion about the second one? While standards may differ in interpretations, it is meaningless to assign two values to the same key in Python dictionary. It only creates confusions to users/contributors.

**Comment by bact** [comment]
Agree that it will only create confusion if we have non-unique keys left around. Should remove them.

--

For the ISO 11940 paiyannoi/angkhandiao case, if we know the context we can actually tell if the surface ฯ should be paiyannoi (for abbreviation, tend to occurs at the end of a word) or angkhandiao (for end of sentence).

But for the current simple dictionary lookup implementation, I think we can for the time being commented out the line 112 of angkhandiao to disabled it - but still keep it in the code with some note so future contributors will not trying to add it in again (as they may have an impression that something is missing).

https://github.com/PyThaiNLP/pythainlp/blob/73b17e326a459b0fbeb89a5e1e8631783d6696c2/pythainlp/transliterate/iso_11940.py#L112

This case is a bit easier to remove/commented out the line 112, as angkhandiao is rarely used in modern Thai writing. (it may create problem if anyone use this for writings like poetry though).

--

For IPA to RTGS one, according to this table https://en.wikipedia.org/wiki/Help:IPA/Thai , `j` will get converted differently depends on where it occurs in the syllable (`j` as a syllable-initial consonant vs `j` as a syllable-final consonant).

This again a shortcoming of current simple dictionary lookup implementation.

Removing the line alone will not improve the code correctness but will surely improve the code 'deterministic' character from the point of view of contributor (having non-unique keys are just confusing).

In this case, it is more difficult to remove a particular line as both of them occur regularly.

Needs an algorithm update, I would say.

**Comment by bact** [comment]
ISO 11940 case is fixed (for now) by #851 
Phoneme still remains.

**Comment by BLKSerene** [comment]
@bact For the second issue, if both cases are common, and algorithm is not expected to be updated in the near future, I suggest for now we just comment out the first key-value pair and add a comment along with a link to the discussion in this issue, so that the behavior and output is unchanged (as the second key-value overrides the first one) but at least confusion is removed.

**Comment by bact** [comment]
@BLKSerene  I agree. We can put https://github.com/PyThaiNLP/pythainlp/issues/846 in the comment,
maybe also in the docstring as well. So it will be more transparent about the limitation to the users.

Do you feel like open a PR on this?
