### ISSUE TITLE
bug: test_khavee.py failed - Can't find rhyme between paragraphs

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#853]
### Description

A test in test_khavee.py failed.

### Expected results

It should passed.

### Current results

FAIL: test_check_klon (tests.test_khavee.TestKhaveePackage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pythainlp/pythainlp/tests/test_khavee.py", line 24, in test_check_klon
    self.assertEqual(
AssertionError: Lists differ: ["Can[42 chars]จอง')in paragraph 2", "Can't find rhyme betwee[39 chars]h 2"] != ["Can[42 chars]จอง') in paragraph 2", "Can't find rhyme betwe[40 chars]h 2"]

First differing element 0:
"Can't find rhyme between paragraphs ('หมา', 'จอง')in paragraph 2"
"Can't find rhyme between paragraphs ('หมา', 'จอง') in paragraph 2"

- ["Can't find rhyme between paragraphs ('หมา', 'จอง')in paragraph 2",
+ ["Can't find rhyme between paragraphs ('หมา', 'จอง') in paragraph 2",
?                                                     +

   "Can't find rhyme between paragraphs ('หมา', 'ทอง') in paragraph 2"]

### Steps to reproduce

Run test.

### PyThaiNLP version

dev latest

### Python version

3.8

### Operating system and version

n/a

### Files

pythainlp/pythainlp/tests/test_khavee.py

**Comment by BLKSerene** [comment]
This is a regression and I'll open a PR to fix it.
