### ISSUE TITLE
Error in romanization function

### ISSUE THREAD

**Issue by giggls** [PyThaiNLP/pythainlp#86]
I'm trying to use your romanization code for Thai romanization of Openstreetmap.
(see https://github.com/giggls/osml10n). As ICU library does not produce useful results.

Unfortunately while processing data this code crashes at some stage:

```python
from pythainlp.romanization import romanization
from pythainlp.tokenize import word_tokenize

for w in word_tokenize('ตรงข้ามหมู่บ้านกฤษดานคร'):
  print("%s: %s" % (w,romanization(w,engine='royin')))
```

The problem seems to boil down to the following:

```python
print(romanization('ฤ',engine='royin'))
```

The object we are talking about is the following bus-stop:
http://www.openstreetmap.org/node/1388399020

Sven

P.S.: I do not understand Thai language, I'm just producing a romanized map of the world.

**Comment by giggls** [comment]
Forgot to post the actual error:
```
>>> from pythainlp.romanization import romanization
>>> romanization('ฤ',engine='royin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pythainlp/romanization/__init__.py", line 22, in romanization
    listword.append(romanization(word_list[i]))
  File "/usr/local/lib/python3.5/dist-packages/pythainlp/romanization/royin.py", line 154, in romanization
    word2=consonants(word2,res)
  File "/usr/local/lib/python3.5/dist-packages/pythainlp/romanization/royin.py", line 120, in consonants
    word=word.replace(res[0],consonants_data[res[0]][0])
KeyError: 'ฤ'

```

**Comment by wannaphongcom** [comment]
PRINCIPLES OF ROMANIZATION FOR THAI SCRIPT BY TRANSCRIPTION METHOD http://www.arts.chula.ac.th/~ling/tts/principles_eng.pdf

**Comment by giggls** [comment]
Hm I do not really know how to get along with this answer.

Learning how thai transcription works is not an option for me.

Openstreetmap Objects may well contain spelling errors and even then I need to be able to use the library.

For now I just implemented an exception handler in my code which will fall back to generic libicu transliteration if the above code fails.
https://github.com/giggls/osml10n/commit/d17c8204b639f78a1d59b1de4ba7e73a8cb6943f

**Comment by wannaphongcom** [comment]
Try thai2rom https://colab.research.google.com/drive/1WOyza-lLprlrurg-GkBDJ4z6sQ4gV_Iy
