### ISSUE TITLE
bug: GitHub Workflows: macOS test always failed when os = "self-hosted"

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/pythainlp#864]
### Description

macOS test config matrix.os = "self-hosted" always failed.

[.github/workflows/macos-test.yml ](https://github.com/PyThaiNLP/pythainlp/blob/dev/.github/workflows/macos-test.yml)

### Expected results

If nothing is wrong with the code itself, the test should pass.

Can compare this with the results from Windows, Linux, and macOS os = "macos-latest" test configs.

### Current results

From one of the test, this is the result:
```
14: 51074 Killed: 9               python -m unittest discover
/Users/pythainlp/miniconda3/envs/pythainlp38/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Error: Process completed with exit code 137.
```
See in full: https://github.com/PyThaiNLP/pythainlp/actions/runs/6847071857/job/18614686269?pr=862

### Steps to reproduce

Commit any code that will trigger the unittest on GitHub workflow

### PyThaiNLP version

dev latest

### Python version

3.8

### Operating system and version

macOS

### Files

[.github/workflows/macos-test.yml ](https://github.com/PyThaiNLP/pythainlp/blob/dev/.github/workflows/macos-test.yml)

**Comment by konbraphat51** [comment]
Isn’t Lint a problem too?

**Comment by wannaphong** [comment]
I'm working on this problem. I have a problem. GitHub Actions can't work like containers.

It currently runs on a MacOS vm set up like MacOS, but without containers. I'm not sure what setup I should configure?

**Comment by bact** [comment]
How MacStadium get connected with GitHub Actions? Does it need a special hook or config? I may be able to take a look, but not sure where to start.

**Comment by wannaphong** [comment]
> How MacStadium get connected with GitHub Actions? Does it need a special hook or config? I may be able to take a look, but not sure where to start.

It use [github-hosted-runners](https://docs.github.com/en/actions/using-github-hosted-runners). MacStadium host Mac mini M1 like normal computer that can access by ssh or vnc and It can connect internet. The runners can running any script (even rm -rf /), so I host a macOS's Virtual Machine in subsystem to secured.

Config: https://github.com/PyThaiNLP/pythainlp/blob/dev/.github/workflows/macos-test.yml

**Comment by bact** [comment]
Thank you

**Comment by bact** [comment]
With new GitHub infrastructure that already support arm64, the necessity to rely on self-hosted is small now. 
It is removed in #947.

Feel free to add back if it works again.
