### ISSUE TITLE
Add PhayaThaiBERT model into PyThaiNLP [WIP]

### ISSUE THREAD

**Issue by pavaris-pm** [PyThaiNLP/pythainlp#868]
Due to an impressive result of the new released paper **PhayaThaiBERT: Enhancing a Pretrained Thai Language Model with Unassimilated Loanwords** for better handling with foreign words compared to former existing Thai encoder-based model. 

I think it is great to add it into supported downstream task of PyThaiNLP e.g. token classification etc. to strengthen the library. What do you think? If all of us agreed on this, I can help integrating it as a new engine asap.

## New features 
Here is the task that I found that it can be integrated in PyThaiNLP after reading a paper. The list below here is the current progress and contributors who put their efforts develop the model ( ✅  check mark means that it already added in the source code and will make a complete PR after complete all of it krub):

- [x] Part-of-speech tagging on blackboard corpus by @MpolaarbearM 
- [x] Named-entity-recognition on Thainer-v2 corpus by @pavaris-pm 
- [x] Tokenization by @pavaris-pm 
- [x] Data Augmentation (Text) by @pavaris-pm 
- [ ] Word Correction (currently under research and development)

etc ... (I will keep add more into the list based on what I have found during an experiment)

For those who interested, feel free to leave a comment below in case you want to develop a model in any of your interested task krub. After that, you can made a PR to the same brach as in PR #873

**Comment by wannaphong** [comment]
I think it is very good to see new fine tuning model that use new the state-of-the-art Thai encoder model. You can train new  model. I don't have freetime for training model. 😢  (reserach)

**Comment by pavaris-pm** [comment]
> I think it is very good to see new fine tuning model that use new the state-of-the-art Thai encoder model. You can train new  model. I don't have freetime for training model. 😢  (reserach)

that's worth to try. I will help working on this, then, you can take a review on my PR after it is completed 👍🏻

**Comment by bact** [comment]
See #871 by @MpolaarbearM

**Comment by pavaris-pm** [comment]
> See #871 by @MpolaarbearM 

@bact Thanks for your remind krub. I already took a look at the paper itself. Seems like PhayaThaiBERT brings a lot of new things up into the game with extra vocabulary expansion. However, big thanks for @MpolaarbearM for training POS tagging model krub. I'll take a deeper look and see if there has any functionality from PhayaThaiBERT that we can added up into this library.
