### ISSUE TITLE
Add ICU wordbreak dictionary (Thai)

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#877]
Since ICU are include to almost all web browser, so I think we should add ICU dictionary to PyThaiNLP to use same dictionary and can deploy any system that pythainlp/nlpo3 doesn't support.

Dictionary: https://raw.githubusercontent.com/unicode-org/icu/main/icu4c/source/data/brkitr/dictionaries/thaidict.txt

**Comment by pavaris-pm** [comment]
@wannaphong i've added ICU of Thai language into the corpus already. You can see and review it at PR #879 krub.
