### ISSUE TITLE
GUI for PyThaiNLP

### ISSUE THREAD

**Issue by wannaphongcom** [PyThaiNLP/pythainlp#88]
เพื่อการศึกษาสำหรับผู้สนใจการประมวลผลภาษาธรรมชาติและนักภาษาศาสตร์

- [ ] Design GUI

- [ ] build gui

- [ ] build exe for windows 32 bit & 64 bit

**Comment by sagelga** [comment]
น่าจะทำเป็นเว็บ แล้วก็สามารถลอง demo ตัว NLP ได้จากในเว็บครับ เดี๋ยวนี้ mobile-first กันแล้ว
ถ้าสามารถลองเล่นในเว็บได้ ก็จะได้เห็นว่า NLP มันน่าสนใจแค่ไหน

แล้วน่าจะมีฟังก์ชันให้กด report เพื่อการพัฒนาระบบ NLP ให้ยื่งแม่นยำยึ่งขึ้นครับ เผื่อว่าเออเข้าใจ context ในประโยคผิดอะไรแบบนี้ ก็จะได้มาปรับปรุงได้ในเวอร์ชันต่อๆไป

**Comment by heytitle** [comment]
ส่วนตัวคิดว่า ทำเป็นเว็บ / api น่าจะดีที่สุด แล้วก้อทำตัว app เป็น interface เสริม ซึ่งตัว app อาจจะใช้ [Electron][1] ในพัฒนา cross platform

[1]: https://electronjs.org

**Comment by wannaphongcom** [comment]
@heytitle สามารถ fork ตัวโปรเจค https://github.com/PyThaiNLP/pythainlp-webdemo ไปพัฒนาต่อแล้วส่ง pull requests กลับมาได้ครับ ไม่จำกัดเครื่องมือและภาษาที่ใช้งานครับ

**Comment by heytitle** [comment]
@wannaphongcom เดี๋ยวลองทำ Docker image ให้ละกันครับ

**Comment by heytitle** [comment]
because we already have the Docker container, we can possibly close this one? 

Nevertheless, I also think we have to update the Docker container, including features intoduced in version 2.1

**Comment by wannaphongcom** [comment]
@heytitle close.
