### ISSUE TITLE
Thai Tokenization

### ISSUE THREAD

**Issue by leky40** [PyThaiNLP/pythainlp#897]
มี Thai Tokenization ที่เป็น interface version หรือ online แบบไม่ต้อง install ไหมคะ สามารถ copy and paste Thai texts แล้วกด run ให้ segment Thai words ได้เลย มีแนะนำไหมคะ

ก่อนหน้านี้ใช้ ของ อาจารย์วิโรจน์ ทั้งตัว GUI และ online ตอนนี้ ทั้งสองตัวไม่ทำงาน ไม่แน่ใจว่า code ของ GUI มันมีปัญหาอะไร เลยเปลี่ยนมาใช้ออนไลน์ ตอนนี้ไม่ respond sever ไม่รู้จะทำไง 

อยากได้มา segment words ให้ก่อน มันช่วย speed up ระดับหนึ่ง หลังจากนั้นก็ค่อยมาแก้ตาม  context ด้วยมือทีหลัง 

ขอบคุณค่ะ

**Comment by pavaris-pm** [comment]
@leky40 ถ้าเป็น online ลองใช้ตัวนี้ก่อนก็ได้ครับ [Thai Word Tokenizer](https://thai-word-tokenizer.pages.dev/ ) โดยจะมี simple longest matching จาก dictionary เป็น algorithm สำหรับใช้ตัดคำครับ

ส่วนถ้าอยากแก้ gui เองก็สามารถ fork จาก repo นี้ไปแก้ไขได้เลยครับ [Thai Word Tokenizer on JavaScript](https://github.com/spicydog/thai-word-tokenizer?tab=readme-ov-file)

**Comment by wannaphong** [comment]
@leky40 ตามนี้ได้เลยครับสำหรับ newmm https://huggingface.co/spaces/pythainlp/newmm_online

**Comment by leky40** [comment]
@wannaphong @pavaris-pm  ขอบคุณค่ะ
