### ISSUE TITLE
Get List of words to sent_tokenize

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#906]
I think `sent_tokenize` should support input function from `List[str]` type. Now, sent_tokenize support `str` type only.

**Comment by ayaan-qadri** [comment]
Hey @wannaphong, I would like to work on it, can you please provide a bit more details, I'm new on this repo.

**Comment by wannaphong** [comment]
> Hey @wannaphong, I would like to work on it, can you please provide a bit more details, I'm new on this repo.

`pythainlp.tokenize.sent_tokenize` support string datatype for using the function only. It should support the list of words (string) for using the function too.

https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tokenize/core.py#L325
