### ISSUE TITLE
มี ตัวตัดคำไทย ด้วยภาษา c บ้างไหมครับ

### ISSUE THREAD

**Issue by TridentTD** [PyThaiNLP/pythainlp#913]
## Detailed description
MCU ระดับเล็กๆ มักใช้ภาษา c/c++ 
อยากให้มี ThaiNLP ภาษา c ด้วยจะดีมากๆครับ

**Comment by bact** [comment]
มี libthai ครับ
https://github.com/tlwg/libthai

**Comment by TridentTD** [comment]
@bact 
ขอบคุณมากครับ

**Comment by TridentTD** [comment]
@bact 

ตัว libthai ดูเหมือนว่า เป็น libthai ที่ต้องพึ่ง lib iconv ด้วย
ในขณะที่ MCU เล็กๆ โดยปกติ ไม่ support iconv ให้แปลงได้เลย
พอมีทางเป็นไปได้ไหม ที่ตัวตัดคำไทย จะมีสร้างเป็น c library แบบ mini 
เช่น mini_thaicut.c
เพื่อให้ สามารถยืดหยุ่น ในการเคลื่อนย้ายไปรันบน MCU ต่างๆได้ ครับ

ขอบคุณครับ

**Comment by wannaphong** [comment]
พอยกตัวอย่าง MCU ที่ใช้ได้ไหมครับ

**Comment by TridentTD** [comment]
ESP32 เป็นต้นครับ

**Comment by bact** [comment]
ลองถามดูใน libthai ไหมครับ ว่าปัจจุบันรองรับ arch ไหนบ้าง
