### ISSUE TITLE
docs: clarify output of tone_detector

### ISSUE THREAD

**Issue by kristw** [PyThaiNLP/pythainlp#918]
### Description

อยากให้ช่วยอธิบาย output ของ function `tone_detector` ใน `util` เพิ่มเติมครับ
ผมไม่คุ้นเคยกับตัวย่อพวกนี้มากนักเลยไม่แน่ใจว่า l, m, h, r, f คือเสียงอะไรบ้าง

### Expected results

updated docstring

### Current results

```
def tone_detector(syllable: str) -> str:
    """
    Thai tone detector for syllables

    :param str syllable: Thai syllable
    :return: syllable's tone (l, m, h, r, f or empty if it cannot be detected)
    :rtype: str
```

### Steps to reproduce

open the code

### PyThaiNLP version

current

### Python version

3.8

### Operating system and version

OS X Sonoma 14.5

**Comment by wannaphong** [comment]
เป็น Tonal Composition of Thai Syllables ครับ สามารถอ่านเพิ่มเติมได้ที่ http://www.thai-language.com/ref/tone-rules ครับ

**Comment by kristw** [comment]
ขอบคุณครับ
