### ISSUE TITLE
Sentence segmentation for Thai

### ISSUE THREAD

**Issue by leky40** [PyThaiNLP/pythainlp#921]
มีบทความชิ้นไหนทำเรื่อง sentence segmentation ของไทยไหมคะ อยากจะเอามาอ่านดูว่า เวลาเขาตัดประโยคของไทยใช้อะไรเป็นตัวกำหนดในเชิงภาษา ขอบคุณค่ะ

**Comment by wannaphong** [comment]
มีเยอะอยู่นะครับ ลองค้น Google ดูนะครับ
