### ISSUE TITLE
Split whitespace before romanize the text

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#922]
From https://github.com/PyThaiNLP/pythainlp-corpus/issues/26, I think `pythainlp.transliterate.romanize` should split whitespace before romanize the text. It can improve `romanize` funtion.

**Comment by pavaris-pm** [comment]
> From [PyThaiNLP/pythainlp-corpus#26](https://github.com/PyThaiNLP/pythainlp-corpus/issues/26), I think `pythainlp.transliterate.romanize` should split whitespace before romanize the text. It can improve `romanize` funtion.

@wannaphong I can help figure out on this krub.

**Comment by wannaphong** [comment]
Done #924
