### ISSUE TITLE
problem with marisa_trie 0.7.5 dependency

### ISSUE THREAD

**Issue by cocoza4** [PyThaiNLP/pythainlp#93]
Hi all,

I was able to install pythainlp successfully but once I ran word_tokenize("ชิงร้อยชิงล้าน")

I got ImportError: ENVs/ttv-web-crawler/lib/python3.6/site-packages/marisa_trie.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

When I downgraded marisa_trie from 0.7.5 to 0.7.4, it worked like a charm. I'm on Anaconda Python 3.6.1 :: Continuum Analytics, Inc., Ubuntu 16.04

thanks
Peeranat F.

**Comment by wannaphongcom** [comment]
Thank you. (y)

**Comment by surasakcho** [comment]
I happened to have the same version of marisa_trie (0.7.5) you mentioned but mine was on different environment as follow
-Python 3.6.3 :: Anaconda custom (64-bit)
- Win7-64. 

I found that the same phrase can be tokenized finely in my machine.
I think the cause of this issue may not be marisa_trie 0.7.5 dependency.

**Comment by which-one** [comment]
Hi,

I'm running Python3.6 on Ubuntu 16.04 and got the same problem. 

```
ImportError: /home/vichawan/Apps/anaconda3/lib/python3.6/site-packages/marisa_trie.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_
stringstreamIcSt11char_traitsIcESaIcEEE
```

I confirmed that downgrading marisa_trie from 0.7.5 to 0.7.4 solved the error.

Best,
Print
